meetup/meetup_test.py

Many naive implementations do not handle dates in December correctly, including my first attempt.

Added test case including December. 

---

luhn/luhn_test.py

The existing tests:
```python
class LuhnTests(unittest.TestCase):
def test_addends(self):
self.assertEqual([1, 4, 1, 4, 1], Luhn(12121).addends())
def test_addends_large(self):
self.assertEqual([7, 6, 6, 1], Luhn(8631).addends())
```
required the output of addends() to be a list. This specifies not just the values, but also their order. 
The changes in this PR pass the previous expected list and the output of `addends()` to `collections.Counter`, then compares those objects. This enforces the contents of the return value without specifying order (or even type! Any iterable containing the right number of the right values should work.)
```python
class LuhnTests(unittest.TestCase):
def test_addends(self):
self.assertEqual(Counter([1, 4, 1, 4, 1]),
Counter(Luhn(12121).addends()))
def …
```

luhn: avoid overspecification of addends

---

meetup/meetup_test.py

I proposed this at the end of last year based on what I was seeing in others' solutions (see discussion here https://github.com/exercism/exercism.io/issues/2142) and @kytrinyx gave the go-ahead. 
Let me know what you think. Thanks!

added tests for a real 5th Monday of a month and for a nonexistant 5th Monday

---

robot-name/example.py
robot-name/robot_name_test.py

The `test_rest_name` test seems to be written to catch whether the user is using collision detection, but since most people use RNG in their solutions, there's a minute probability of recognizing whether someone has implemented collision detection as currently written.
I rewrote the test to reset to a predefined seed before initialization and before resetting the name, which, if the same logic is used for generating the name in each case, will always result in identical names between the initialization and reset, which should force the need for collision detection.
I guess it'll still fail if there's a big enough difference between the initialization and reset logic (i.e. if they generate numbers first, then letters on the first run, and then do the reverse on the second), but it's a …

Forcing Collision Detection in robot-name Exercise

---

config.json

This puts bob after hamming, leap, and a few others that are fairly simple algorithmically, but before 'meetup', which seems like a bigger problem.

Move bob slightly later in the track

---

sieve/example.py

It runs orders of magnitude faster than the previous implementation, specially with large numbers (i.e.: with a value of `100000`, the old implementation took over 14 seconds, while this new one only takes 0.33 seconds).

New (faster and more efficient) implementation of the "sieve" exercise

---

sublist/example.py
sublist/sublist_test.py

This new implementation is much faster and cleaner. It does not
need to handle exceptions and it does not need to allocate nor zip
sublists at any point.
Also, a test was added to prevent the use of sets, which leads to incorrect results (although all the other tests pass).

sublist: New code example

---

word-count/example.py
word-count/word_count_test.py

Ruby, Elixir, Clojure, and others expect words to be normalized in
some way so that "Go", "go", "GO" are not considered different words.

Expect case normalized words

---

secret-handshake/example.py
secret-handshake/handshake_test.py

The exercise `secret-handshake` had some minor inconsistencies with PEP8 which I fixed except *E501 line too long (80 > 79 characters)*. I thought this might be a good small fix for me to make my first pull request ever and learn how this is done.
```
tmo$ flake8 secret-handshake/ --ignore=E501
secret-handshake/example.py:1:19: E231 missing whitespace after ','
secret-handshake/example.py:1:34: E231 missing whitespace after ','
secret-handshake/example.py:1:52: E231 missing whitespace after ','
secret-handshake/example.py:3:1: E302 expected 2 blank lines, found 1
secret-handshake/example.py:15:1: E302 expected 2 blank lines, found 1
secret-handshake/example.py:16:27: E226 missing whitespace around arithmetic operator
secret-handshake/example.py:22:1: W293 blank line contains whitespace …
```

Formatted to be PEP8 compliant except line length

---

.travis.yml
README.md

**Python 3.5.0** was released a month ago and all our tests run successfully with it. I added 3.5 to the travis-ci config and to the readme. Additionally I removed 3.3 which we could keep as the build doesn't take to long, but I don't think we really get something of it.
```
python3.5 test/check-exercises.py
......
----------------------------------------------------------------------
Ran 6 tests in 0.000s
[...]
.
----------------------------------------------------------------------
Ran 1 test in 0.000s
OK
SUCCESS!
```

Added support for Python 3.5

---

ocr-numbers/example.py
ocr-numbers/ocr_test.py

The exercise `ocr-numbers` had some minor inconsistencies with PEP8 which I fixed.
```
tmo$ flake8 ocr-numbers/
ocr-numbers/example.py:4:1: E302 expected 2 blank lines, found 1
ocr-numbers/example.py:5:24: E226 missing whitespace around arithmetic operator
ocr-numbers/example.py:5:30: E226 missing whitespace around arithmetic operator
ocr-numbers/example.py:5:33: E226 missing whitespace around arithmetic operator
ocr-numbers/example.py:6:1: E101 indentation contains mixed spaces and tabs
ocr-numbers/example.py:6:1: W191 indentation contains tabs
ocr-numbers/example.py:6:7: E128 continuation line under-indented for visual indent
ocr-numbers/example.py:7:1: W191 indentation contains tabs
ocr-numbers/example.py:7:2: E101 indentation contains mixed spaces and tabs
ocr-numbers/example.py:7:7: …
```

ocr-numbers: PEP8 compliance updated

---

minesweeper/example.py
minesweeper/minesweeper_test.py

The exercise `minesweeper ` had some minor inconsistencies with PEP8 which I fixed except E501 line too long.
```
tmo$ flake8 minesweeper/ --ignore=E501
minesweeper/example.py:10:25: E226 missing whitespace around arithmetic operator
minesweeper/example.py:10:31: E226 missing whitespace around arithmetic operator
minesweeper/example.py:10:36: E226 missing whitespace around arithmetic operator
minesweeper/example.py:11:21: E127 continuation line over-indented for visual indent
minesweeper/example.py:11:31: E226 missing whitespace around arithmetic operator
minesweeper/example.py:11:36: E226 missing whitespace around arithmetic operator
minesweeper/example.py:12:21: E127 continuation line over-indented for visual indent
minesweeper/example.py:12:27: E226 missing whitespace around arithmetic …
```

minesweeper: PEP8 compliance updated

---

nth-prime/nth_prime_test.py

The exercise `nth-prime` had some minor inconsistencies with PEP8 which I fixed.
```
tmo$ flake8 nth-prime/
nth-prime/nth_prime_test.py:14:28: E231 missing whitespace after ','
nth-prime/nth_prime_test.py:14:30: E231 missing whitespace after ','
nth-prime/nth_prime_test.py:14:32: E231 missing whitespace after ','
nth-prime/nth_prime_test.py:14:34: E231 missing whitespace after ','
nth-prime/nth_prime_test.py:14:37: E231 missing whitespace after ','
nth-prime/nth_prime_test.py:14:40: E231 missing whitespace after ','
nth-prime/nth_prime_test.py:14:43: E231 missing whitespace after ','
nth-prime/nth_prime_test.py:14:46: E231 missing whitespace after ','
nth-prime/nth_prime_test.py:14:49: E231 missing whitespace after ','
nth-prime/nth_prime_test.py:14:52: E231 missing whitespace after ',' …
```

nth-prime: PEP8 compliance updated

---

poker/example.py
poker/poker_test.py

The exercise `poker` had some minor inconsistencies with PEP8 which I fixed except E501 line too long. 
```
tmo$ flake8 poker/ --ignore=E501
poker/example.py:4:1: E302 expected 2 blank lines, found 1
poker/example.py:6:27: E231 missing whitespace after ':'
poker/example.py:15:1: E302 expected 2 blank lines, found 1
poker/poker_test.py:5:1: E302 expected 2 blank lines, found 1
```

poker: PEP8 compliance updated

---

word-count/word_count_test.py

The exercise `word-count` had some minor inconsistencies with PEP8 which I fixed (#214).
```
tmo$ flake8 word-count/ --ignore=E501
word-count/word_count_test.py:44:7: E111 indentation is not a multiple of four
word-count/word_count_test.py:52:13: E128 continuation line under-indented for visual indent
word-count/word_count_test.py:59:13: E128 continuation line under-indented for visual indent
```

word-count: PEP8 compliance updated

---

saddle-points/example.py

The exercise `saddle-points` had some minor inconsistencies with PEP8 which I fixed (#214).
```
tmo$ flake8 saddle-points/ --ignore=E501
saddle-points/example.py:4:18: E225 missing whitespace around operator
saddle-points/example.py:8:17: E231 missing whitespace after ','
saddle-points/example.py:9:1: W293 blank line contains whitespace
```

saddle-points: PEP8 compliance updated

---

simple-cipher/simple_cipher_test.py

The exercise `simple-cipher` had some minor inconsistencies with PEP8 which I fixed (#214).
```
tmo$ flake8 simple-cipher/
simple-cipher/simple_cipher_test.py:40:80: E501 line too long (116 > 79 characters)
simple-cipher/simple_cipher_test.py:49:80: E501 line too long (116 > 79 characters)
simple-cipher/simple_cipher_test.py:62:13: E128 continuation line under-indented for visual indent
simple-cipher/simple_cipher_test.py:64:13: E128 continuation line under-indented for visual indent
```

simple-cipher: PEP8 compliance updated

---

wordy/wordy_test.py

The exercise `wordy` had one minor inconsistency with PEP8 which I fixed (#214).
```
tmo$ flake8 wordy/ --ignore=E501
wordy/wordy_test.py:1:1: F401 'os' imported but unused
```

wordy: PEP8 compliance updated

---

meetup/meetup_test.py

The exercise `meetup` had one minor inconsistency with PEP8 which I fixed (#214).
```
tmo$ flake8 meetup/
meetup/meetup_test.py:11:1: E302 expected 2 blank lines, found 1
```

meetup: PEP8 compliance updated

---

bob/bob.py

The exercise `bob` had one minor inconsistency with PEP8 which I fixed (#214).
```
tmo$ flake8 bob/
bob/bob.py:4:1: E302 expected 2 blank lines, found 0
```

bob: PEP8 compliance updated

---

house/example.py

The exercise `house ` had one minor inconsistency with PEP8 which I fixed (#214).
```
tmo$ flake8 house/
house/example.py:18:31: E226 missing whitespace around arithmetic operator
```

house: PEP8 compliance updated

---

phone-number/example.py

The exercise `phone-number` had one minor inconsistency with PEP8 which I fixed (#214).
```
tmo$ flake8 phone-number/
phone-number/example.py:31:17: E126 continuation line over-indented for hanging indent
```

phone-number: PEP8 compliance updated

---

triangle/example.py

The exercise `triangle ` had one inconsistency with PEP8 which I fixed (#214). It could also be called *unreachable code*.
```
tmo$ flake8 triangle/
triangle/example.py:16:16: F821 undefined name 's'
```

triangle: PEP8 compliance updated

---

strain/strain_test.py

The exercise `strain ` had one minor inconsistency with PEP8 which I fixed (#214).
```
tmo$ flake8 strain/ --ignore=E501
strain/strain_test.py:42:53: E226 missing whitespace around arithmetic operator
```

strain: PEP8 compliance updated

---

sublist/sublist_test.py

The exercise `sublist ` had one minor inconsistency with PEP8 which I fixed (#214).
```
tmo$ flake8 sublist/ --ignore=E501
sublist/sublist_test.py:67:31: E226 missing whitespace around arithmetic operator
```

sublist: PEP8 compliance updated

---

pascals-triangle/example.py
pascals-triangle/pascals_triangle_test.py

The exercise `pascals-triangle ` had some inconsistency with PEP8 which I fixed (#214).
```
tmo$ flake8 pascals-triangle/
./pascals-triangle/example.py:2:38: E226 missing whitespace around arithmetic operator
./pascals-triangle/example.py:4:1: E302 expected 2 blank lines, found 1
./pascals-triangle/example.py:5:28: E226 missing whitespace around arithmetic operator
./pascals-triangle/example.py:8:1: E302 expected 2 blank lines, found 1
./pascals-triangle/example.py:10:21: E231 missing whitespace after ','
./pascals-triangle/example.py:10:25: E226 missing whitespace around arithmetic operator
./pascals-triangle/example.py:11:27: E226 missing whitespace around arithmetic operator
./pascals-triangle/example.py:11:32: E226 missing whitespace around arithmetic operator …
```

pascals-triangle: PEP8 compliance updated

---

secret-handshake/example.py

The exercise `secret-handshake` had some inconsistency with PEP8 which I fixed (#214).
```
tmo$ flake8 secret-handshake/
./secret-handshake/example.py:18:27: E226 missing whitespace around arithmetic operator
./secret-handshake/example.py:33:16: E226 missing whitespace around arithmetic operator
./secret-handshake/example.py:37:15: E226 missing whitespace around arithmetic operator
./secret-handshake/example.py:37:30: E226 missing whitespace around arithmetic operator
./secret-handshake/example.py:47:23: E226 missing whitespace around arithmetic operator
./secret-handshake/example.py:47:31: E226 missing whitespace around arithmetic operator
./secret-handshake/example.py:47:35: E226 missing whitespace around arithmetic operator
./secret-handshake/example.py:47:38: E226 missing whitespace …
```

secret-handshake: PEP8 compliance updated

---

nucleotide-count/nucleotide_count_test.py

The exercise `nucleotide-count` had one inconsistency with PEP8 which I fixed (#214).
```
tmo$ flake8 nucleotide-count/
./nucleotide-count/nucleotide_count_test.py:29:1: W293 blank line contains whitespace
```

nucleotide-count: PEP8 compliance updated

---

accumulate/accumulate_test.py
accumulate/example.py

The exercise `accumulate` had some inconsistency with PEP8 which I fixed (#214).
```
tmo$ flake8 accumulate/ --ignore=E501
./accumulate/accumulate_test.py:8:56: E226 missing whitespace around arithmetic operator
./accumulate/accumulate_test.py:12:37: E226 missing whitespace around arithmetic operator
./accumulate/accumulate_test.py:22:26: E226 missing whitespace around arithmetic operator
./accumulate/accumulate_test.py:22:31: E226 missing whitespace around arithmetic operator
./accumulate/accumulate_test.py:33:59: E226 missing whitespace around arithmetic operator
./accumulate/example.py:4:19: E231 missing whitespace after ','
```

accumulate: PEP8 compliance updated

---

.travis.yml

#215, #216, #217, #218, #219, #220, #222, #223, #224, #225, #226, #227, #228, #229, #230, #231, #232, #233, #235, #236, #237, #238
After all the pull requests to fix the **PEP8** compliance I would like to never have to do this again. So I added `flake8` to the travis-ci build process. I think especially in a project that is not run by one person alone a strict linting is needed.
I deliberately excluded `E501 line too long`. There would be the option `--max-line-length` to raise the PEP8 limit of 79 characters but there are some test cases that have very long string data.

Add flake8 to travis-ci build process

---

word-count/example.py
word-count/word_count_test.py

Change the separator as discussed in #177 to non alphanumeric as it is also done in the haskell track.

word-count: Change separator from whitespace to non alphanumeric

---

word-count/example.py
word-count/word_count_test.py

word-count: Add test case for unicode support

---

rna-transcription/rna_transcription_test.py

By using a more specific assertion method, we can improve the detail of the assertion error message. `assertMultiLineEqual` is used by default when Unicode strings are compared with assertEqual(). So this only effects Python 2.7 while Python 3 stays the same.
Now you can see which character is wrong, ...
```python
======================================================================
FAIL: test_transcribes_all_occurences (__main__.DNATests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/rna_transcription_test.py", line 21, in test_transcribes_all_occurences
self.assertMultiLineEqual('UGCACCAGAXUU', to_rna('ACGTGGTCTTAA'))
AssertionError: 'UGCACCAGAXUU' != 'UGCACCAGAAUU'
- UGCACCAGAXUU
?          ^
+ UGCACCAGAAUU
? …
```

rna-transcription: Improve assertion message

---

atbash-cipher/atbash_cipher_test.py

By using a more specific assertion method, we can improve the detail of the assertion error message. `assertMultiLineEqual` is used by default when Unicode strings are compared with assertEqual(). So this only effects Python 2.7 while Python 3 stays the same.
Now you can see which character is missing or wrong, ...
```python
======================================================================
FAIL: test_encode_long_word (__main__.AtbashCipherTest)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/atbash_cipher_test.py", line 21, in test_encode_long_word
self.assertMultiLineEqual("nrmwyoldrmtob", encode("mindblowingly"))
AssertionError: 'nrmwyoldrmtob' != 'nrmwy oldrm tob'
- nrmwyoldrmtob
+ nrmwy oldrm tob
?      +     + …
```

atbash-cipher: Improve assertion message

---

config.json
pig-latin/example.py
pig-latin/pig_latin_test.py

I implemented the **x-common/pig-latin** exercise ([README.md](https://github.com/exercism/x-common/blob/master/pig-latin.md). I placed it after `prime-factors` to alternate text and number exercises. Now after the commit I see it's followed by a *cipher* and *scrabble*, so we should search for a better spot in the track. Maybe between `nth-prime`and `saddle-points` might be a good spot.

pig-latin: Implemented exercise from x-common

---

config.json
pangram/example.py
pangram/pangram_test.py

Example solution for new proposed exercise https://github.com/exercism/x-common/pull/133
Will be updated later based on possible feedback there.

pangram: Implemented new exercise

---

.travis.yml

Migrate travis builds from legacy to container-based infrastructure. Details: [travis docs](https://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade)

Update travis to docker container

---

nucleotide-count/example.py

refactored by removing duplication of symbol 'NUCLEOTIDES'.
also removed 'U' because we're not considering it a valid nucleotide
for the purpose of this exercise.

nucleotide-count: refactor by removing duplication.

---

accumulate/accumulate_test.py

```
./exercises/accumulate/accumulate_test.py:21:9: E731 do not assign a lambda expression, use a def
./exercises/accumulate/accumulate_test.py:22:9: E731 do not assign a lambda expression, use a def
./exercises/accumulate/accumulate_test.py:33:9: E731 do not assign a lambda expression, use a def
```

accumulate: fix lambda usage (see #287)

---

series/example.py

```
./exercises/series/example.py:5:26: W503 line break before binary operator
```

series: fix pep8 compliance (see #287)

---

word-count/example.py

```
./exercises/word-count/example.py:13:5: E731 do not assign a lambda expression, use a def
```

word-count: fix lambda usage (see #287)

---

luhn/example.py

```
./exercises/luhn/example.py:7:9: E731 do not assign a lambda expression, use a def
```

luhn: fix lambda usage (see #287)

---

strain/strain_test.py

```
./exercises/strain/strain_test.py:27:9: E731 do not assign a lambda expression, use a def
```

strain: fix lambda usage (see #287)

---

largest-series-product/largest_series_product_test.py

As part of the work to have consistency between tracks as in https://github.com/exercism/todo/issues/104 and https://github.com/exercism/todo/issues/13. Comments are in individual commit messages.

largest-series-product corner cases

---

docs/LEARNING.md
docs/TESTS.md

[Here](https://github.com/exercism/xpython/pull/285) for reference, because I messed up and had to reset the fork.
@kytrinyx I'm sorry, this is the only solution that worked... I'll pay more attention next time.

Created LEARNING.md and TESTS.md.

---

exercises/luhn/example.py
exercises/luhn/luhn_test.py

I finally managed to do it. Issue #284 pointed out the wrong checksum values in the test cases for the `luhn` exercise. I corrected them and corrected the implementation.
There's something I have to point out regarding the implementation of the exercise (`example.py`) though. I didn't really correct it, I just replaced the old one with my implementation _slightly_ modified. It works and all tests pass, but it would be nice to first give it a look and highlight potential problems.
As for the _slightly_ differences with my implementation all I changed is:
- added the `(object)` part to the first line `class Luhn(object)`. I don't really have a precise idea what it does, but it was there in the old implementation so I added it.
- removed the comments.
- cleaned up the unnecessary white …

Fix luhn's checksum wrong test values and its implementation.

---

exercises/largest-series-product/largest_series_product_test.py

The slices functions is an internal implementation details and thus the
test case for the largest-series-product problem should not be concerned
with testing it.
Its presence may cause students to falsely think that their solution has
to use this function, instead of the alternative implementation of only
iterating through the digits once.
The series tests are already well-covered by the series exercise already
existing in this track.
If it is desired to give hints on how to approach this problem (which
was one advantage of having the slices test), then consider including a
hints file and/or directory in the largest-series-product directory.
This PR arises from discussion in
https://github.com/exercism/x-common/issues/192

largest-series-product: Do not test slices

---

exercises/pangram/pangram_test.py

I reviewed a solution that was passing the tests by coincidence - they were performing an alphabetic string comparison between sets of letters, and the only non empty False test case was passing because the string ('a quick movement...') is alphabetically less than 'abcdef...'. It seemed like another test case would help here!
(See http://exercism.io/submissions/c6790b9a65fe4c08b865e5eb621fe94d)

pangram: Add extra invalid pangram test case

---

docs/TESTS.md

Just add '\n' between `cd` and `py.test` commands

Fix py.test run in documentation

---

exercises/sublist/sublist_test.py

Adds a simple test for checking if the user-defined return values (SUBLIST, SUPERLIST, EQUAL, and UNEQUAL) have different values.
Simple fix to get around the problem raised in Issue #342

sublist: Adding test for unique return values

---

exercises/word-count/word_count_test.py

This test says "preserves_punction" when it's really testing that punctuation is being ignored (i.e. not included in the list of words being counted).

Word-count test name fix

---

config.json

addresses #353 
As I mentioned in #357 I was tempted to bump the difficulty up here as well, because I found there was a fair bit of research into classes involved, (`__repr__`, `__eq__`) even though it may not necessarily be difficult to implement. In the end I felt that having to research a problem doesn't make it more difficult. Again it's that fine line of a problem appearing difficult when we don't know the answer, and then losing some of that appearance of difficulty once solved.

add topics to clock exercise in config.json

---

config.json

Adds the exercise to the "exercises" key in the config.json (see #360).

binary-search: Add to "exercises" key in config

---

config.json
exercises/flatten-array/example.py
exercises/flatten-array/flatten_array_test.py

I'm not entirely sure whether I updated the `config.json` file appropriately.
One issue I have with this exercise currently: "array" is not a word we use in Python.  Could we rename this to "flatten-list" or just "flatten" (which I think would be best)?  Would that be problematic because the exercise is called something different for the other languages?

Add flatten array exercise

---

config.json
list-ops/example.py
list-ops/list_ops_test.py

I did not add the exercise to the config.json yet because I was not sure where it should be included in the order of problems. 
This is my first time doing a pull request so please let me know if there are any issues.

Add list-ops problem

---

exercises/rna-transcription/example.py
exercises/rna-transcription/rna_transcription_test.py

Now reflects the canonical test data defined in x-common (see [canonical-data.json](https://github.com/exercism/x-common/blob/master/exercises/rna-transcription/canonical-data.json)).
To work with the 3 new test cases I had to add a way to detect not valid input to the example implementation. While there are many ways to do this (*regex* being one of them) I thought the `if any(char not in valid_chars ...` construct is maybe the most self explanatory.
**Note:** *It would be great to get this merged before this weekend (November 26th) as there is a [code hangout](https://codebuddies.org/hangout/8An374DNxwZ38PJeF) planned.*

rna_transcription: Add invalid input support

---

exercises/hamming/example.py
exercises/hamming/hamming_test.py

Now reflects the canonical test data defined in x-common (see [canonical-data.json](https://github.com/exercism/x-common/blob/master/exercises/hamming/canonical-data.json)).
The existing implementation worked with all new test cases except the last two, so I had to add a simple input validation.
**Note:** *It would be great to get this merged before this weekend (November 26th) as there is a [code hangout](https://codebuddies.org/hangout/8An374DNxwZ38PJeF) planned.*

hamming: Add invalid input support

---

config.json
exercises/word-search/example.py
exercises/word-search/word_search.py
exercises/word-search/word_search_test.py

I don't really like the example solution, but it works. Also I'm not sure if it is the right way to provide the `class Point` this way.
https://github.com/exercism/x-common/blob/master/exercises/word-search/description.md

Add word-search exercise

---

test/check-exercises.py

So `./bin/configlet` only checks that for every exercises in the `config.json` there is also an example implementation and vice versa. It doesn't check if there is also a test file for every exercise.
The current test runner (`./test/check-exercises.py`) searches for all existing `*_test.py` files, so we won't get an error if we are missing a test file, put it in the wrong path or did name the file incorrectly (#294).
An attempt to fix this was started (#296) but not finished. So I adapted the new config format and changed the test runner in such a way, that it will detect missing test files.
With this new error case I also added more details to the failure message, so that it is clear `FAILURES:  hello-world (TestFailed), bob (FileNotFound)` what caused the problem.

Change to config.json based testing

---

exercises/poker/poker_test.py

* Added a missing corner test-case where the lower of the two pairs wins
if its higher than the others lower pair
* Added Highcard-fallback test for two-pair-equals-test
I thought you might want to add these, since quite a few implementations on exercism.io aren't correct in this case.

poker: add two more tests

---

exercises/atbash-cipher/atbash_cipher_test.py

Add `test_decode_number` as there is a test that encode number. Check this _iteration_[1] for a solution that pass the tests without checking for alphanumeric in decode.
Add `test_encode_decode`. Having done this in the first place, would had highlighted the need of checking for alphanumeric in decoding.
[1] http://exercism.io/submissions/c7c9448e6a674dd6a11ea35dc32e29a4

atbash_cipher_test: Add 2 tests

---

exercises/list-ops/example.py
exercises/list-ops/list_ops_test.py

* i'd expect a reversed empty tuple to be an empty tuple and not an empty list

list-ops: fix reversed tuple test

---

exercises/luhn/example.py
exercises/luhn/luhn_test.py

luhn: Update tests and example

---

exercises/hello-world/hello_world_test.py

As discussed in https://github.com/exercism/x-common/issues/520
closes #430

hello-world: Simplify to unconditional "Hello, World!"

---

exercises/atbash-cipher/atbash_cipher_test.py

Adds one missing test case from the canonical test data and
stores the test data version.

atbash-cipher: Update test cases

---

exercises/run-length-encoding/run_length_encoding_test.py

This removes the unicode test cases (https://github.com/exercism/x-common/issues/428, https://github.com/exercism/x-common/pull/434) and
adds the new white space and lowercase tests (https://github.com/exercism/x-common/pull/624).

run-length-encoding: Update test cases

---

config.json
exercises/isogram/example.py
exercises/isogram/isogram.py
exercises/isogram/isogram_test.py

This completes the work started in #367 by addressing the feedback to the previous PR. (Thanks @sbulage ❤️)

Add isogram

---

test/check-exercises.py

Even if the test runner itself is executed with a specific python version the subprocess used to execute the respective test script always uses the generic 'python' found in the PATH. On most systems that have python2 & 3 installed 'python' is a symlink to 'python2.X'. So this would mean that even if you would run 'python3 ./test/...py' the tests would still be run with python2.

Fix python version used to run tests

---

docs/TOOLS.md

This PR uses the suggested relative path for the images in: TOOLS.md
The following `/docs` don't have images:
- ABOUT.md
- HELLO.md
- INSTALLATION.md
- LEARNING.md
- RESOURCES.md
- TESTS.md
Closes #400

Update image paths

---

exercises/word-count/example.py
exercises/word-count/word_count_test.py

As discussed in https://github.com/exercism/x-common/issues/441
Fixes #416

word-count: Remove unicode test case

---

exercises/leap/leap_test.py

Adds the changes made to the the canonical test data in https://github.com/exercism/x-common/pull/463 and stores the test data version.

leap: Update test cases

---

exercises/bob/bob_test.py

Removes the unicode test and adds one missing test from the canonical test data and stores the test data version. Also switches the parameter order to follow #440.

bob: Update test cases

---

exercises/anagram/anagram_test.py

Updates the test cases according to the canonical test data and stores the test data version.
I switched from strings splitter into a list to use lists directly. This does not change anythings for the functions, but I think it makes it more clear for users that look at the tests, what their function can expect to receive.
```diff
detect_anagrams(
"good",
-            "dog goody".split()
)
detect_anagrams(
"good",
+          ["dog", "goody"]
)
```

anagram: Update test cases

---

exercises/largest-series-product/largest_series_product_test.py

Updates the test suite according to the canonical test data and stores the test data version.
The `big number with span of 13` test case was removed from the canonical test data (https://github.com/exercism/x-common/pull/471). I think it's a good *extra credit* case, so I changed it into a skipped test.

largest-series-product: Update test cases

---

config.json
exercises/rotationa-cipher
exercises/rotational-cipher/example.py
exercises/rotational-cipher/rotational_cipher.py
exercises/rotational-cipher/rotational_cipher_test.py
exercises/say/say_test.py

I will port the Rotational Cipher excerise

Rotational Cipher: Exercise Added

---

exercises/sublist/sublist_test.py

Two cases:
1.  One list has a double digit number and the second list has those numbers as single digits.  For example, 10 vs 1 and 0.
2.  Embedded spaces within a list entry vs individual letters.  For example, 'a c' vs 'a' 'c'.
One way to think about solving this in Python is to use string join, but that gives incorrect results for these edge cases.

sublist: Add test cases for edge cases

---

exercises/allergies/allergies_test.py

Updates the tests according to the canonical test data and stores the test data version.

allergies: Update test cases

---

config.json
exercises/transpose/example.py
exercises/transpose/transpose.py
exercises/transpose/transpose_test.py

Added example.py and exercise test files. Updated config.json. Please review

 transpose : Modified example.py to avoid exception

---

exercises/meetup/meetup_test.py

Adds ~80 missing test cases from the canonical test data and the version.
**?** The old test suite had two test cases for `5th` that are not part of the canonical test data.
I kind of like them and would let them remain in the test suite. The question is if they should be added as skipped tests for "extra credit" ([like here](https://github.com/exercism/xpython/blob/bbd3c623b8b1839fedac606b03f26e6c1130a9de/exercises/linked-list/linked_list_test.py#L46)) or as normal test cases. **?**
```python
def test_fifth_monday_of_march_2015(self):
self.assertEqual(meetup_day(2015, 3, 'Monday', '5th'), date(2015, 3, 30))
def test_nonexistent_fifth_monday_of_february_2015(self):
self.assertRaises(MeetupDayException, meetup_day, 2015, 2, 'Monday', '5th')
```

meetup: Update test cases

---

config.json
exercises/book-store/book_store.py
exercises/book-store/book_store_test.py
exercises/book-store/example.py

Definitely not an elegant solution, but it should be enough to validate the test cases.
I'm especially not sure about the range check in `_group_price(size)` because neither the description nor the canonical test data suggest how to handle bigger groups than 5. Maybe instead of raising a `ValueError` we could just keep the last discount or we just assume that there won't be more than five ... I don't know.

book-store: Add new exercise

---

exercises/grade-school/grade_school_test.py

From Python 3.6 on, dictionaries retain the order in which items are
added. If the test case puts the items into the tested class in sorted
order, even a naive implementation (one that does no sorting) can pass
by giving back all items in the original order.

grade-school: catch false positives due to test case being sorted already

---

config.json
test/check-exercises.py

We will be moving to a tree-shaped track rather than a linear one, as described in the [progression & learning in Exercism](https://github.com/exercism/docs/blob/master/about/conception/progression.md) design document.
In order to support this, we need to expand the metadata that exercises are configured with.
Note that 'core' exercises are never unlocked by any other exercises. Core exercises appear in the track in the order that they are listed in the array.
Non-core exercises depend on only one exercise (unlocked_by: ). At the moment we are assuming that this is a core exercise, but there is no reason that it needs to be.
Until now we have operated with a separate deprecated array. These are now being moved into the exercises array with a deprecated field.
With these defaults the track …

Add configuration defaults for nextercism

---

exercises/scale-generator/scale_generator_test.py

http://exercism.io/submissions/3c67c65da6e34871946a955fca7ff2ae
There seem to be a mistake in the enigmatic scale: enigmatic = Scale('G', 'enigmatic', 'mAMMMmM')
https://en.wikipedia.org/wiki/Enigmatic_scale Semitone, Tone and a half, Tone, Tone, Tone, Semitone, Semitone. Should be enigmatic = Scale('G', 'enigmatic', 'mAMMMmm')

Update the enigmatic scale case

---

config.json
exercises/complex-numbers/README.md
exercises/complex-numbers/complex_numbers.py
exercises/complex-numbers/complex_numbers_test.py
exercises/complex-numbers/example.py

Trying to implement complex-numbers according to guideline. This is initial commit for WIP pull-request. Tests and example.py still needs to be finished.

Implement exercise complex-numbers

---

exercises/acronym/acronym.py

Added a `words` parameter to the abbreviate method to ensure clarity to future users. This change was discussed in issue #509.
Fixes #597

Acronym: update function to have params as in #509

---

exercises/phone-number/example.py
exercises/phone-number/phone_number_test.py

* Update tests to use current version of canonical data (v1.2.0). These tests
require validation of the area and exchange codes, which is already mentioned
in README.md - the first digit of each must be between 2 and 9
* Update example code to pass new tests

phone-number: Add validation of area code and exchange code

---

exercises/hexadecimal/hexadecimal.py

Add an example parameter `hex_string` for the `hexa()` function. Issue: #564 
Fixes #564

hexadecimal: Add Example Parameter for hexa()

---

exercises/pig-latin/pig_latin.py

Added Parameters to the Pig Latin file in the function `translate`
This resolves the issue #592.
TODO: Pig Latin - Ticked on #509
Fixes #609

Pig Latin - Added Parameters to Placeholders

---

exercises/phone-number/phone_number.py

Added Parameters to the Phone Number file in the functions `__init__`
This resolves the issue #591.
TODO: Phone Number - Ticked on #509
Resolves #608

Phone Number - added parameters to placeholders

---

exercises/protein-translation/protein_translation.py

Added parameters to the `protein-translation.py` as described in issue #613 .
Fixes #613

protein-translation: add parameters to exercise placeholder as in #613

---

exercises/minesweeper/minesweeper.py

minesweeper: Add parameter to exercise placeholder. Closes #599

---

exercises/two-fer/two_fer.py

two-fer : added parameters to two-fer - Issue #650

---

exercises/hello-world/hello_world.py

Added Parameters to the Hello World file in the functions `hello`.
This resolves the issue #584.
TODO: Hello World - Ticked on #509 
Fixes #563

hello_word added parameter to exercise placeholder

---

exercises/queen-attack/queen_attack.py

As described in [#616](https://github.com/exercism/python/issues/616)
Fixes #616

queen-attack: Add parameters to exercise placeholder

---

exercises/matrix/matrix.py

adds a parameter to init method making it easier for users to understand the problem.
Fixes #572

matrix.py: adds parameter to init function

---

exercises/sublist/sublist.py

Added the `firstList` and `secondList` parameters to the abbreviate method to ensure clarity to future users. This change was discussed in issue #509.
Fixes #643

sublist: add parameters to exercise placeholder

---

exercises/triangle/triangle.py

triangle: Added parameters to exercise placeholder

---

exercises/two-bucket/example.py
exercises/two-bucket/two_bucket_test.py

two-bucket: fix incorrect test case

---

.travis.yml

By reading logs from https://travis-ci.org/exercism/python/jobs/286835621 I've noticed that our test script run tests before verifiying high level things with `configlet` which can be improved
This PR is meant to fix that

Change execution order of verification scripts for Travis CI

---

config.json

Add topics for 'Wordy'

---

config.json
exercises/markdown/README.md
exercises/markdown/example.py
exercises/markdown/markdown.py
exercises/markdown/markdown_test.py

resolves #729 
Want to implement this

Implement exercise markdown

---

config.json

Poker: added topics

---

config.json
exercises/food-chain/README.md
exercises/food-chain/example.py
exercises/food-chain/food_chain.py
exercises/food-chain/food_chain_test.py

Implement exercise food-chain

---

README.md
exercises/binary-search/binary_search_test.py
exercises/binary/binary_test.py
exercises/meetup/meetup_test.py
exercises/minesweeper/minesweeper_test.py
exercises/ocr-numbers/ocr_numbers_test.py
exercises/pythagorean-triplet/pythagorean_triplet_test.py
exercises/saddle-points/saddle_points_test.py
exercises/simple-cipher/simple_cipher_test.py
exercises/triangle/triangle_test.py
exercises/wordy/wordy_test.py

Improve exception tests

---

exercises/list-ops/example.py
exercises/list-ops/list_ops.py
exercises/list-ops/list_ops_test.py

I've implemented the tests from the most recent version of the [canonical data (v2.0.0)](https://github.com/exercism/problem-specifications/blob/master/exercises/list-ops/canonical-data.json), and I kept a couple of the old tests that I thought were good additions. This PR also fixes #570.
There are a couple of points that I'm not too sure about though and would invite comment.
**Key questions:**
- Is the new implementation of `append` and `concat` sensible? Or should we revert their behaviour?
- Do we want the suggested optional tests for long lists?
The canonical data seems to suggest implementing `append` and `concat` in a different way to the previous tests, and I'm not sure that I like it. The new `append` function is essentially just the old `concat` function, and the new `concat` …

list-ops: Update test cases to v2.0.0

---

exercises/clock/clock.py
exercises/clock/clock_test.py
exercises/clock/example.py

clock: Replace Clock.add() with operator Clock.__add__()

---

config.json
exercises/zipper/README.md
exercises/zipper/example.py
exercises/zipper/zipper.py
exercises/zipper/zipper_test.py

implement zipper

---

exercises/variable-length-quantity/example.py
exercises/variable-length-quantity/variable_length_quantity.py

Add parameters to exercise placeholder for variable-length-quantity.
Also change variable naming from bytes to bytes_ to avoid shadowing
python's bytes
Fixes: #651

variable-length-quantity: add parameters to exercise placeholder

---

exercises/forth/forth.py
exercises/forth/forth_test.py

While solving exercises, I noticed that somehow myself, @m-a-ge, and @N-Parsons all managed to miss that the test file was importing from `example`, not `forth`. This is now fixed.

forth: fix import line

---

exercises/markdown/example.py
exercises/markdown/markdown_test.py

markdown: Do not add <p> to list items

---

config.json

add topics to grains

---

exercises/leap/leap_test.py

[This Leap solution](http://exercism.io/submissions/7ef5b0ab93b540f79cdee9f153e0a21c) should not pass the unit test, since it checks whether `year % 100` and `year % 400` are equal in order to tell whether the year it has been passed is a leap year. This works for 2016 because `2016 % 100` and `2016 % 400` both evaluate to 16.
1996, another leap year that is divisible by 4 but not 100, does not have this property and, under that solution, would be falsely *not* classed as a leap year.

Swap '2016' for '1996' to stop faulty logic from passing unit test in Leap

---

exercises/twelve-days/example.py
exercises/twelve-days/twelve_days.py

twelve-days: Add parameters to exercise placeholder

---

config.json
exercises/error-handling/README.md
exercises/error-handling/error_handling.py
exercises/error-handling/error_handling_test.py
exercises/error-handling/example.py

error-handling: implement exercise

---

exercises/diffie-hellman/.meta/hints.md
exercises/diffie-hellman/README.md
exercises/simple-cipher/.meta/hints.md
exercises/simple-cipher/README.md

Closes #774 by creating a HINTS.md file for every exercise involving cryptography or the use of random module.
The wording is as follows
> 
> # Hints
> 
> ## Should I use random or secrets?
> 
> Python, as of version 3.6, includes two different random modules.
> 
> The module called `random` is pseudo-random, meaning it does not generate
> true randomness, but follows an algorithm that simulates randomness. 
> Since random numbers are generated through a known algorithm, they are not truly random. 
> 
> The `random` module is not correctly suited for cryptography and should not be used, 
> precisely because it is pseudo-random. 
> 
> For this reason, in version 3.6, Python introduced the `secrets` module, which generates
> cryptographically strong random numbers that provide the greater …

Hints on cryptography about "random" modules

---

README.md

This PR updates the README to include a couple of new conventions, and turns the references to relevant issues/PRs where these conventions were discussed/originated into links to make it easier for people to find and understand the reasoning.

README: Add new conventions and add links to relevant issues/PRs

---

exercises/forth/forth_test.py

Updates the version string format for `forth`, since it was missed when it was recently merged.

forth: Update version string to reference problem-specifications

---

config.json

To finish with #808 we must ensure that there are no topics in our `config.json` which are not listed in https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt
This PR fixes this inconsistency

Fix topics naming to meet naming convention 

---

exercises/forth/example.py
exercises/forth/forth_test.py

I noticed that there was an error in one of the tests, and that the simple parsing/stack tests from the `canonical-data` were not implemented. This PR fixes these issues, as well as applying the convention of `assertEqual(actual, expected)`.

forth: Fix errors in tests

---

exercises/word-count/word_count_test.py

Fix #1011 
As I mentioned in issue #1045, there were two tests from the canonical data that failed with the example implementation, so I left them out.

word-count: added test version and updated tests to match canonical 

---

exercises/rna-transcription/README.md
exercises/rna-transcription/example.py
exercises/rna-transcription/rna_transcription_test.py

Based on discussion at exercism/problem-specifications#956, this PR changes the `rna-transcription` exercise to raise a `ValueError` instead of returning an empty string.

rna-transcription: Use an exception to handle input errors

---

exercises/saddle-points/saddle_points_test.py

Update the `saddle points` testes following the recomandations of closes #1005

saddle-points: Update the tests folling the canonical data

---

exercises/phone-number/README.md

Fixes a typo in the README (exercism/problem-specifications#980).

phone-number: Fix typo in README

---

exercises/alphametics/alphametics_test.py

Resolves #531 
Before:
```Bash
$ pytest -v
============================= test session starts =============================
platform win32 -- Python 3.6.2, pytest-3.2.1, py-1.4.34, pluggy-0.4.0 -- c:\python36\python.exe
cachedir: .cache
rootdir: C:\Git\python\exercises\alphametics, inifile:
collected 8 items
alphametics_test.py::TestAlphametics::test_invalid_leading_zero_solution PASSED
alphametics_test.py::TestAlphametics::test_invalid_solution_must_have_unique_value_for_each_letter PASSED
alphametics_test.py::TestAlphametics::test_puzzle_with_eight_letters PASSED
alphametics_test.py::TestAlphametics::test_puzzle_with_four_letters PASSED
alphametics_test.py::TestAlphametics::test_puzzle_with_seven_letters PASSED
alphametics_test.py::TestAlphametics::test_puzzle_with_six_letters PASSED …
```

alphametics: improve test ordering

---

exercises/queen-attack/queen_attack_test.py

Resolves #1003 
Updated tests to match canonical data.
I moved some extra existing tests cases not covered by the tests in canonical data to the bottom.
The extra exception tests seem useful.

queen-attack: Update tests to match canonical data v2.0.0

---

exercises/grains/grains_test.py

Resolves #996 
Removes multiple total_after tests in favor of one at the end as specified in canonical-data.

grains: Update tests to match canonical-data 

---

exercises/poker/poker_test.py

Resolves #1002.
Updated tests to match canonical data.
I renamed some tests to better match up with the json file, and some of the implementations had slightly different cards so those were matched.

poker - Update tests to match canonical-data.json @v1.0.0

---

exercises/ocr-numbers/example.py
exercises/ocr-numbers/ocr_numbers.py
exercises/ocr-numbers/ocr_numbers_test.py

ocr-numbers: Update ocr-numbers to reflect changes to canonical data

---

exercises/alphametics/example.py

Reworked the solution, eliminated few inefficiencies

alphametics: Revised, increased speed

---

exercises/minesweeper/example.py
exercises/minesweeper/minesweeper_test.py

Add missing test version comment.
Add ordered tests with names matching canonical data descriptions.
Disable empty board tests which are incompatible with board class.
Move selected old tests to additional tests section. Closes #998

minesweeper: update tests to version 1.1.0

---

.gitignore

If people use `pytest-cache` when working on exercises, it creates a `.cache` directory that is currently not ignored - I've experienced this myself, and I just saw a PR with this issue.
This PR updates `.gitignore` to ignore the cache directories of `py-test` and Python modules (`.cache` and `__pycache__`, respectively).

Ignore pytest cache directory

---

exercises/go-counting/go_counting_test.py

There is no `gocounting` module; it should be `go_counting`

go-counting: fix typo in import

---

exercises/perfect-numbers/example.py
exercises/perfect-numbers/perfect_numbers.py
exercises/perfect-numbers/perfect_numbers_test.py

Resolves #1001
A few things to note:
- I added errors + error catching to both the example solution and the test cases (as these were specified in the canonical data)
- I refer to the range of valid inputs as "positive whole numbers" as the definition of natural numbers can either include or exclude 0. If this is accepted, I'll open an appropriate PR to update the canonical data accordingly
- I've put two blank lines below the version string as my PEP8 linter was complaining about it (it's possible my linter is not configured properly)

perfect-numbers: Update perfect-numbers to reflect changes to canonical data

---

test/check-exercises.py

This PR simplifies the `check-exercises.py` script by enforcing strict module naming.
The previous version used a heuristic to determine the correct name for the example to be renamed to for the tests to run. This meant that:
* The test-suite could import an arbitrary module name as long as it didn't exist.
* If the script was run locally, it would fail to determine the module name if the name clashed with an installed module (eg. `markdown`).
* Incorrect module names were accepted by Travis-CI checks, and thus could be displayed to learners and prevent their tests from passing.
~~DO NOT MERGE THIS!!!~~
~~This PR is designed to test Travis-CI for a possible issue I noticed due to #1104.~~

check-exercises.py: Enforce strict module naming

---

config.json

Re #1096, valid uuid is X(8)-X(4)-X(4)-X(4)-X(12) where X is [\da-f]. This exercise must've been merged after #1096 or was simply missed.

binary-search-tree: replace invalid uuid

---

.github/stale.yml

Propose the following changes:
- `daysUntilStale: 60 -> 21`: With 5 track maintainers (3+ active), issues are being manually closed after ~20 days frequently. 60 days is too long.
- Add `epic` to `exemptLabels`: `epic` denotes issues that are usually super-issues, and closing every sub-issue takes a lot of effort and time.
- `staleLabel: on hiatus -> abandoned`: `abandoned` is typically used by the maintainers here, so change for consistency

Make probot/stale more useful

---

exercises/say/example.py
exercises/say/say_test.py

From the [Python documentation](https://docs.python.org/2/library/exceptions.html#exceptions.AttributeError), `AttributeError` is "raised when an attribute reference or assignment fails." This situation is more appropriate for [`ValueError`](https://docs.python.org/2/library/exceptions.html#exceptions.ValueError): "Raised when a built-in operation or function receives an argument that has the right type but an inappropriate value..."

say: change to more appropriate exception type

---

exercises/proverb/README.md
exercises/proverb/example.py
exercises/proverb/proverb.py
exercises/proverb/proverb_test.py

This PR updates the `proverb` exercise to use the recently implemented canonical data.
**Note:** there will be a merge conflict with #1113 due to changes in the README, but I will fix this when one of these PRs is merged.

proverb: Update exercise to canonical-data 1.0.0

---

exercises/beer-song/example.py
exercises/clock/example.py
exercises/nucleotide-count/example.py
exercises/phone-number/example.py
exercises/protein-translation/example.py
exercises/say/example.py
exercises/two-fer/example.py

I noticed that some of the exercises were still using the old style string formatting (eg.`"%s" % value`) rather than using the newer `str.format` method - this PR moves everything to the newer style.

Migrate string formatting operations to `str.format`

---

exercises/protein-translation/example.py
exercises/protein-translation/protein_translation.py
exercises/protein-translation/protein_translation_test.py

Update protein-translation tests

---

exercises/reverse-string/reverse_string_test.py

Hi,
I fixed the naming of the test cases in reverse_string_test.py by adding the prefix `test_` in front of their names.  I noticed that they were not running and I made the small adjustments.
Thanks and regards,
J F

Rename test cases in reverse_string_test.py so that they will run

---

config.json
exercises/parallel-letter-frequency/README.md
exercises/parallel-letter-frequency/example.py
exercises/parallel-letter-frequency/parallel_letter_frequency.py
exercises/parallel-letter-frequency/parallel_letter_frequency_test.py

When migrating the data from v1 to v2, we will lose all the solutions submitted to
deprecated exercises, unless they exist in the track configuration.
This adds the deprecated parallel-letter-frequency exercise back, leaving it deprecated so that it
doesn't actively show up as part of the track.
We can delete it from the track again after we launch v2, if we want to.

Add back deleted, deprecated parallel-letter-frequency exercise

---

exercises/luhn/luhn_test.py

Apparently it was missing: https://github.com/exercism/problem-specifications/blob/master/exercises/luhn/canonical-data.json

luhn: add missing whitespace

---

exercises/palindrome-products/example.py
exercises/palindrome-products/palindrome_products_test.py

palindrome-products: Update palindrome-products to reflect changes to canonical data

---

exercises/word-search/example.py
exercises/word-search/word_search_test.py

I felt the "\n" are superfluous and therefore removed them (I've made this suggestion before in another Issue/PR).
Also this proposed format (with a list of strings) matches the format from [canonical-data of problem-specifications  ](https://github.com/exercism/problem-specifications/blob/master/exercises/word-search/canonical-data.json)
@N-Parsons and @behrtam could you review this please?

word-search: adapt testdata-format from canonical-testdata-format

---

exercises/phone-number/phone_number_test.py

I added the reason for why the tests should fail to give users a better understanding and also to reflect the the naming from canonical

phone-number: rename 2 tests

---

exercises/bob/bob_test.py
exercises/bob/example.py

bob: Update to clarify ambiguity regarding shouted questions

---

test/check-exercises.py

This PR edits the `check-exercises.py` script to skip testing of deprecated ~~and foregone~~ exercises.
The logic used assumes that `"deprecated"` ~~and `"foregone"`~~ are not keys in active exercises, as is currently the case.

check-exercises: Skip deprecated exercises

---

exercises/bowling/README.md

In preparation for [v2](https://github.com/exercism/v2-feedback/blob/master/README.md) we're updating Configlet—our Exercism track linter—to require that we generate the exercise README. This is because in v2 we will not be generating READMEs on the fly, but deliver the README as defined in the directory for each implementation.
I'm going to go ahead and merge this as soon as the build passes, as this is janitorial work rather than a language-specific change.
See https://github.com/exercism/configlet/issues/116 for more details.

bowling: Generate missing exercise README

---

exercises/rail-fence-cipher/rail_fence_cipher.py

Modifications in two places:
- Adjust the order of function parameters to be consistent with [test file](https://github.com/exercism/python/blob/master/exercises/rail-fence-cipher/rail_fence_cipher_test.py).
- Remove `fence_pattern` function to give learners more freedom.

rail-fence-cipher: improve stub file

---

exercises/hello-world/hello_world_test.py

Solves #1183. 
Since canonical data was only updated for new input policy (see the [change](https://github.com/exercism/problem-specifications/commit/be3ae666959780698df31656e750f85a9ba2b758)), which has nothing to do with test file in Python, so update of version number suffices.

hello-world: update tests to v1.1.0

---

exercises/leap/leap_test.py

Closes #1184. 
Since canonical data was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

leap: update tests to v1.3.0

---

exercises/reverse-string/reverse_string_test.py

Closes #1185
Since canonical data was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

reverse-string: update tests to v1.1.0

---

exercises/pangram/pangram_test.py

Closes #1186 
Since canonical data was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

pangram: update tests to v1.4.0

---

exercises/hamming/hamming_test.py

Closes #1188 
Since canonical data was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

hamming: update tests to v2.1.0

---

exercises/rna-transcription/rna_transcription_test.py

Closes #1187 
* Correct test class name from 'DNA' to 'RNA'
* Fix typo in test case method name
* Remove bad input tests

rna-transcription: update tests to v1.2.0

---

exercises/meetup/meetup_test.py

Closes #1192.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/meetup/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

meetup: update tests to v1.1.0

---

exercises/gigasecond/gigasecond_test.py

Closes #1190.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/gigasecond/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

gigasecond: update tests to v1.1.0

---

exercises/rotational-cipher/rotational_cipher_test.py

Closes #1193.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/rotational-cipher/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

rotational-cipher: update tests to v1.2.0

---

exercises/difference-of-squares/difference_of_squares_test.py

Closes #1194.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/difference-of-squares/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

difference-of-squares: update tests to v1.2.0

---

exercises/anagram/anagram_test.py

Closes #1195. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/anagram/canonical-data.json).
* Remove outdated test cases
* Fix typo in method name

anagram: update tests to v1.2.0

---

exercises/allergies/allergies_test.py

Closes #1196.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/allergies/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

allergies: update tests to v1.1.0

---

exercises/robot-simulator/robot_simulator_test.py

Closes #1197.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/robot-simulator/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

robot-simulator: update tests to v2.2.0

---

exercises/sieve/sieve_test.py

Closes #1198.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/sieve/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

sieve: update tests to v1.1.0

---

exercises/atbash-cipher/atbash_cipher_test.py

Closes #1199.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/atbash-cipher/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

atbash-cipher: update tests to v1.1.0

---

exercises/sum-of-multiples/sum_of_multiples_test.py

Closes #1200.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/sum-of-multiples/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

sum-of-multiples: update tests to v1.2.0

---

exercises/say/say_test.py

Closes #1202.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/say/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

say: update tests to v1.1.0

---

exercises/largest-series-product/largest_series_product_test.py

Closes #1203.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/largest-series-product/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

largest-series-product: update tests to v1.1.0

---

exercises/kindergarten-garden/kindergarten_garden_test.py

Closes #1204.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/kindergarten-garden/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

kindergarten-garden: update tests to v1.1.0

---

exercises/flatten-array/flatten_array_test.py

Closes #1205.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/flatten-array/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

flatten-array: update tests to v1.2.0

---

exercises/space-age/space_age_test.py

Closes #1207.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/space-age/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

space-age: update tests to v1.1.0

---

exercises/prime-factors/prime_factors_test.py

Closes #1209.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/prime-factors/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

prime-factors: update tests to v1.1.0

---

exercises/pig-latin/pig_latin_test.py

Closes #1210.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/pig-latin/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

pig-latin: update tests to v1.2.0

---

exercises/scrabble-score/scrabble_score_test.py

Closes #1211.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/scrabble-score/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

scrabble-score: update tests to v1.1.0

---

exercises/crypto-square/crypto_square_test.py

Closes #1212.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

crypto-square: update tests to v3.2.0

---

exercises/sublist/sublist_test.py

Closes #1212.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/sublist/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

sublist: update tests to v1.1.0

---

exercises/matrix/example.py
exercises/matrix/matrix.py
exercises/matrix/matrix_test.py

Closes #1215.
Since this exercise had been implemented before [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/matrix/canonical-data.json) was proposed, I've made dramatic change to the whole exercise. Notice that I've turned to testing `Matrix.row` method instead of retrieving instance attributes directly, because canonical data has input parameter `index`.

matrix: re-implement to conform with canonical data

---

exercises/custom-set/custom_set_test.py

Closes #1259.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/custom-set/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

custom-set: update tests to v1.3.0

---

exercises/forth/forth_test.py

Closes #1252.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/forth/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

forth: update tests to v1.5.0

---

exercises/alphametics/alphametics_test.py

Closes #1242. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/alphametics/canonical-data.json).
* Add test case `test_puzzle_with_ten_letters_and_199_addends`
* Rename confusing test method name

alphametics: update tests to v1.2.0

---

exercises/two-fer/two_fer_test.py

Closes #1247. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/two-fer/canonical-data.json).

two-fer: update tests to v1.2.0

---

exercises/poker/example.py
exercises/poker/poker.py
exercises/poker/poker_test.py

Closes #1230. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/poker/canonical-data.json).
- Rename test function from `poker` to canonical `best_hands`
- Tidy up input/output formats
- Activate all tests (some are formerly disabled)
- Make some test method names more meaningful
BTW I am quite confused about former contributors deactivating test cases that will break `example.py` by removing `test_` prefix of test case methods.

poker: update tests to v1.1.0

---

exercises/wordy/wordy_test.py

Closes #1226.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/wordy/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

wordy: update tests to v1.1.0

---

exercises/minesweeper/minesweeper_test.py

Closes #1224.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/minesweeper/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

minesweeper: update tests to v1.1.0

---

exercises/secret-handshake/secret_handshake_test.py

Closes #1220.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/secret-handshake/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

secret-handshake: update tests to v1.2.0

---

exercises/rectangles/rectangles_test.py

Closes #1232.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/rectangles/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

rectangles: update tests to v1.1.0

---

exercises/circular-buffer/circular_buffer.py
exercises/circular-buffer/circular_buffer_test.py

Closes #1214.
Currently method names in [test file](https://github.com/exercism/python/blob/master/exercises/circular-buffer/circular_buffer_test.py) don't strictly correspond with `description`s in [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/circular-buffer/canonical-data.json), some of which are ambiguous and even syntactically invalid, such as `test_full_buffer_cant_written` on [Line 37](https://github.com/exercism/python/blob/master/exercises/circular-buffer/circular_buffer_test.py#L37). As far as I can see, less descriptive test method names can slow down the process of working through the exercise and confuse beginners.
@cmccandless Advice?

circular-buffer: update tests and improve stub file

---

exercises/bowling/bowling.py
exercises/bowling/bowling_test.py
exercises/bowling/example.py

Closes #1240 
* Add two new test cases, `test_cannot_roll_after_bonus_roll_for_spare` and `test_cannot_roll_after_bonus_rolls_for_strike`, according to [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/bowling/canonical-data.json)

bowling: update tests to v1.2.0

---

exercises/list-ops/list_ops_test.py

Closes #1234.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/gigasecond/canonical-data.json) was only updated for new input policy and [function formats](https://github.com/exercism/problem-specifications/commit/4efde46d6d2915ff1f2c693c5751e62422ba764b#diff-637e4f7a1434d17126301fcffc3bbcbe), which has nothing to do with test file in Python, so update of version number suffices.

list-ops: update tests to v2.2.0

---

exercises/run-length-encoding/run_length_encoding_test.py

Closes #1191.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/run-length-encoding/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

run-length-encoding: update tests to v1.1.0

---

exercises/rail-fence-cipher/rail_fence_cipher_test.py

Closes #1216.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/rail-fence-cipher/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

rail-fence-cipher: update tests to v1.1.0

---

exercises/nth-prime/nth_prime_test.py

Closes #1217.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/nth-prime/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

nth-prime: update tests to v2.1.0

---

exercises/dominoes/dominoes_test.py

Closes #1255.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/dominoes/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

dominoes: update tests to v2.1.0

---

exercises/zipper/zipper_test.py

Closes #1254. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/zipper/canonical-data.json).
* Move utility functions into test class body

zipper: update tests to v1.1.0

---

exercises/complex-numbers/complex_numbers_test.py

Closes #1249. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/complex-numbers/canonical-data.json).
* Move tests of real and imaginary parts to top
* Add one more test case of exponential

complex-numbers: update tests to v1.3.0

---

exercises/collatz-conjecture/collatz_conjecture_test.py
exercises/collatz-conjecture/example.py

Closes #1248. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/collatz-conjecture/canonical-data.json).

collatz-conjecture: update tests to v1.2.0

---

exercises/all-your-base/all_your_base.py
exercises/all-your-base/all_your_base_test.py

Closes #1238. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/all-your-base/canonical-data.json).

all-your-base: update tests to v2.3.0

---

exercises/saddle-points/saddle_points_test.py

Closes #1218. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/saddle-points/canonical-data.json)
* Conform test method name to canonical description
* Rename variable `inp` and `ans` to `matrix` and `expected`

saddle-points: update tests to v1.1.0

---

exercises/diamond/diamond_test.py

Closes #1236.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/diamond/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

diamond: update tests to v1.1.0

---

exercises/variable-length-quantity/variable_length_quantity_test.py

Closes #1237.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/variable-length-quantity/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

variable-length-quantity: update tests to v1.1.0

---

exercises/binary-search/binary_search_test.py

Closes #1233.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

binary-search: update tests to v1.1.0

---

exercises/two-bucket/example.py
exercises/two-bucket/two_bucket.py
exercises/two-bucket/two_bucket_test.py

Closes #1250. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/two-bucket/canonical-data.json).

two-bucket: update tests to v1.4.0

---

exercises/twelve-days/example.py
exercises/twelve-days/twelve_days.py
exercises/twelve-days/twelve_days_test.py

Closes #1221. Re-implement this exercise according to [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/twelve-days/canonical-data.json).

twelve-days: re-implement according to canonical data

---

exercises/word-search/word_search.py
exercises/word-search/word_search_test.py

Closes #1241.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/word-search/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.
Besides I have removed unnecessary code in the stub to ensure more freedom of implementing this exercise.

word-search: update tests to v1.2.0

---

exercises/bracket-push/bracket_push.py
exercises/bracket-push/bracket_push_test.py
exercises/bracket-push/example.py

Closes #1223. [Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/bracket-push/canonical-data.json).
Besides updating version number, I have renamed the function `check_bracket` and its parameter `input_string` to `is_paired` with parameter `value` to be consistent with canonical data.

bracket-push: update tests to v1.2.0

---

exercises/palindrome-products/palindrome_products_test.py

Closes #1222. [Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/palindrome-products/canonical-data.json).
- Update version number
- Use `assertRaisesWithMessage` instead of plain `assertRaises`

palindrome-products: update tests to v1.1.0

---

exercises/scale-generator/example.py
exercises/scale-generator/scale_generator.py
exercises/scale-generator/scale_generator_test.py

Closes #1244. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/scale-generator/canonical-data.json).
* Remove property `name` from class `Scale`
* Refactor property `pattern` to `intervals`
* Remove `name`-related tests
* More descriptive test method names
* More concise test assertions

scale-generator: update tests to v1.0.0

---

exercises/tournament/tournament_test.py

Closes #1243.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/tournament/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

tournament: update tests to v1.4.0

---

exercises/house/example.py
exercises/house/house.py
exercises/house/house_test.py

Closes #1229. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/house/canonical-data.json).
I'm uncertain about whether I should transform outputs to lists of strings. As is [commented](https://github.com/exercism/problem-specifications/blob/master/exercises/house/canonical-data.json#L4) in the canonical data:
> JSON doesn't allow for multi-line strings, so all verses are presented here as arrays of strings. It's up to the test generator to join the lines together with line breaks.

house: update to v2.1.0

---

exercises/ocr-numbers/ocr_numbers_test.py

Closes #1228.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/ocr-numbers/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

ocr-numbers: update tests to v1.1.0

---

exercises/perfect-numbers/perfect_numbers_test.py

Closes #1219.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/perfect-numbers/canonical-data.json)* was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.
@cmccandless I have noticed #1155, so if we have reached a consensus on skipping `test_sixth_perfect_number` and `test_seventh_perfect_number`, I'll push a commit to this PR immediately.
\* *Changed link to canonical data for correct exercise - cmccandless*

perfect-numbers: update tests to v1.1.0

---

exercises/protein-translation/protein_translation_test.py

Closes #1245.
Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/protein-translation/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so update of version number suffices.

protein-translation: update tests to v1.1.0

---

config.json
exercises/rational-numbers/README.md
exercises/rational-numbers/example.py
exercises/rational-numbers/rational_numbers.py
exercises/rational-numbers/rational_numbers_test.py

Closes #1300. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/rational-numbers/canonical-data.json).

rational-numbers: implement exercise

---

exercises/food-chain/example.py
exercises/food-chain/food_chain.py
exercises/food-chain/food_chain_test.py

Closes #1253. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/food-chain/canonical-data.json). 
Taken the same testing approach as [twelve-days](https://github.com/exercism/python/blob/master/exercises/twelve-days/twelve_days_test.py).

food-chain: update tests to v2.1.0

---

exercises/queen-attack/example.py
exercises/queen-attack/queen_attack.py
exercises/queen-attack/queen_attack_test.py

Closes #1225. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/queen-attack/canonical-data.json).

queen-attack: re-implement according to canonical data 2.1.0

---

exercises/grains/grains_test.py

Since [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/grains/canonical-data.json) was only updated for new input policy, which has nothing to do with test file in Python, so bumping version suffices.

grains: update tests to v1.1.0

---

exercises/go-counting/example.py
exercises/go-counting/go_counting.py
exercises/go-counting/go_counting_test.py

I noticed that, while the existing test file referenced canonical data v1.1.0, until exercism/problem-specifications#1195 was merged just recently, there was no such data (I suspect that another test file was copied as a template and this line was assumed to be correct, both by author and reviewer(s)). As there is now canonical data, this PR conforms the tests to that data.

go-counting: adapt tests to canonical data v1.0.0

---

config.json
exercises/sgf-parsing/README.md
exercises/sgf-parsing/example.py
exercises/sgf-parsing/sgf_parsing.py
exercises/sgf-parsing/sgf_parsing_test.py

sgf-parsing: implement exercise

---

config.json

`lens-person` is specific to languages with immutable data (i.e. Haskell). This concept does not exist in Python, so the exercise should be foregone.

lens-person: forego exercise

---

config.json
exercises/bank-account/README.md
exercises/bank-account/bank_account.py
exercises/bank-account/bank_account_test.py
exercises/bank-account/example.py

Solves #730. I have closed #1176 in favor of this pull request.
Closes #757 (mutual-exclusion)

Implement exercise bank-account

---

exercises/alphametics/alphametics_test.py
test/check-exercises.py

While this test is canonical, it does not technically add additional coverage. This test serves as a test for efficiency (https://github.com/exercism/problem-specifications/pull/1024#issuecomment-347316485) of a solution, not completeness.
Furthermore, here are the run-times for this exercise from the [latest Travis build](https://travis-ci.org/exercism/python/builds/349382228) (at the time of this writing):
| Python Version | Run-time (seconds) |
| --- | --- |
| 2.7 | 3.155 |
| 3.3 | 2.461 |
| 3.4 | 3.567 |
| 3.5 | 7.270 |
| 3.6 | 0.774 |
Notice that the optimized example solution is only "fast" in 3.6.
@nikamirrr I know you're put in a lot of discussion on this exercise, both in this track (as the author of the current solution) and in exercism/problem-specifications (to add this test …

alphametics: mark computationally intensive test as extra-credit

---

exercises/bank-account/README.md

Update README of this exercise to the latest template.

bank-account: update README using configlet

---

exercises/bowling/bowling_test.py

bowling: negative test uses positive value

---

config.json
exercises/yacht/README.md
exercises/yacht/example.py
exercises/yacht/yacht.py
exercises/yacht/yacht_test.py

Implement exercise **yacht**. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/yacht/canonical-data.json). Discussions are welcome!

yacht: implement exercise

---

exercises/crypto-square/README.md

Update README according to commit [1477f38](https://github.com/exercism/problem-specifications/commit/1477f38634ea94b6e35e1c2bcd09a7f63108b04a).

crypto-square: Clarify rectangular output requirement in README

---

exercises/scale-generator/README.md

Check out this [commit](https://github.com/exercism/problem-specifications/commit/ee70bf7ca8a26b790461a2933cf60ec14a2c4882) in problem-specifications.

scale-generator: update README to latest description

---

exercises/food-chain/example.py
exercises/food-chain/food_chain_test.py

Closes #1381. Use a list of individual lines as expected output instead of implicit string concatenation.

food-chain: Enforce the same output format as canonical data

---

exercises/crypto-square/README.md

Check out this [commit](https://github.com/exercism/problem-specifications/commit/e41e9a7a2be14edfa177df42017f6e2cbf1c5605).

crypto-square: add missing relevant white space in README

---

exercises/rna-transcription/.meta/hints.md
exercises/rna-transcription/rna_transcription_test.py

The README for the python "rna_transcription" exercise reads:
Your function will need to be able to handle invalid inputs by raising a `ValueError` with a meaningful message.
The test suite doesn't check for this currently, so I've added a test case where it checks for bad bases which are any capital letters that are not G,C,T,A. There is probably room for another 3 - 4 tests; testing lower case, testing numbers, testing punctuation.

rna-transcription: Removed HINTS.md ValueError reference

---

exercises/hello-world/example.py
exercises/hello-world/hello_world.py

The old version of those files still expected an argument, which was used in very early versions of the exercise to create dynamic output.
But as we are only testing for a single static return value, namely `"Hello, World!"`, it is safe to remove that argument from example and stub.

Make example and stub implementation line up with tests

---

exercises/linked-list/example.py
exercises/linked-list/linked_list.py

It hurts readability to redefine the meaning of well-known builtins such
as 'next', and pylint rightfully warns about this, saying
W:  2,30: Redefining built-in 'next' (redefined-builtin)
It's a little unfortunate that Python grabs this part of the namespace,
but let's fix the issue by using slightly different words for 'the item
before' and the 'the item next'.

linked-list: Don't redefine builting function 'next'

---

exercises/reverse-string/example.py
exercises/reverse-string/reverse_string.py

It hurts readability to redefine the meaning of well-known builtins such
as 'input', and pylint rightfully warns about this, saying
W:  1,12: Redefining built-in 'input' (redefined-builtin)
It's a little unfortunate that Python grabs this part of the namespace,
but let's fix the issue by using a different word for 'the input text'.

reverse-string: Don't redefine builting function 'input'

---

exercises/saddle-points/saddle_points_test.py

There is a test for multiple saddle points in a column, but there is no test for multiple points in a row. 
These changes rename the existing test to indicate it tests for saddle points in a column and adds a test for multiple points in a row.

Add test for saddle points in row

---

exercises/isbn-verifier/isbn_verifier_test.py

isbn-verifier: updates tests to v2.7.0

---

exercises/grep/grep_test.py

Resolves #1437. From v1.0.0 to v1.1.0 the syntax for input changed: https://github.com/exercism/problem-specifications/commit/e893e0b25af17fc71e43dd6b25adfbd17a003823#diff-593bb60c24b63589316b40f4cb8decd2

update-grep: updates tests to v1.1.0

---

config.json
exercises/affine-cipher/README.md
exercises/affine-cipher/affine_cipher.py
exercises/affine-cipher/affine_cipher_test.py
exercises/affine-cipher/example.py

Closes #1448. [Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/affine-cipher/canonical-data.json)

affine-cipher: implement exercise

---

exercises/grains/grains_test.py

Closes #1504
Note that no changes were made to the tests since Python is in-line with the [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/grains/canonical-data.json). The canonical-data was updated to have error objects instead of -1 when an error would occur, and the Python tests are already in-line with that policy.

grains: updated tests to v1.2.0

---

exercises/change/README.md
exercises/change/change_test.py

Two changes are in this PR.
1. Updated README so that description shows the correct expected outcome (see https://github.com/exercism/problem-specifications/pull/1339)
2. Updated version of change_test.py to v1.3.0. The tests themselves were not updated for the same reason seen in https://github.com/exercism/python/pull/1511.

change: updated README, tests are now v1.3.0

---

exercises/forth/forth_test.py

Define utility functions in a utility class that inherits
from 'unittest.TestCase'. The test classes inherit from the utility
class.
Reduces line count from 384 to 307. It should also make it easier
for a user to comment out tests without mistakenly breaking
previous tests by commenting out their utility functions.
Resolves #1514

forth: Refactor duplicate utility functions

---

exercises/wordy/wordy_test.py

Update wordy test to 1.2.0. Fix #1530

wordy: update tests to v1.2.0

---

exercises/phone-number/phone_number_test.py

These tests were updated in #1532 to v1.6.0, but the referenced version
was not updated.

phone-number: set correct canonical-data version

---

exercises/pythagorean-triplet/example.py
exercises/pythagorean-triplet/pythagorean_triplet.py
exercises/pythagorean-triplet/pythagorean_triplet_test.py

Modify tests to fit latest canonical data. Add additional function to
find triplets with sum. Remove primitive triplets function from
exercise. Replace example.py with @cmccandless solution (with
permission). New solution runs considerably faster.
Brute force solutions that do not use primitive triplets will now
take very long. Perhaps hint should be added. This could be discussed
in problem-specifications.
Resolves #1510

pythagorean-triplet: Update exercise to v1.0.0

---

exercises/rational-numbers/example.py

Remove deprecated fractions.gcd from example.py
Before, warning was thrown in Travis Python 3.6 tests.

rational-numbers: fix deprecated gcd warning

---

exercises/sgf-parsing/sgf_parsing_test.py

Added an escaped backslash due to `DeprecationWarning: invalid escape sequence \]`.

Escaped backslash due to `DeprecationWarning`

---

exercises/rest-api/rest_api_test.py

Simple version bump, since https://github.com/exercism/problem-specifications/commit/fd4cb7bd8f30dd10a024b0b8cfa92f8a1442e828 just changes an int to float. Fixes  #1553 .

rest-api: update tests to v1.0.2

---

exercises/rest-api/rest_api_test.py

In the [problem specification](https://github.com/exercism/problem-specifications/blob/master/exercises/rest-api/canonical-data.json) (as well as the [README](https://github.com/exercism/problem-specifications/blob/master/exercises/rest-api/description.md)), the GET `/users` endpoint is listed with a payload pattern:
```
{"users": ["Adam", "Bob"]}
```
The canonical tests reflect that pattern in the "one user" case:
```
{"users": ["Bob"]}
```
Note the presence of a list, even with only one user.  This seems correct to me because it makes a single user not a special case for the format of the payload, and no matter whether there's one or many users to GET, I can still do a `for user in users`.  The Python version of the test file was missing those square brackets.  So I added them.

Update rest_api_test.py `get_single_user` case

---

bin/check-test-version.py

`--token` may still be used to override this.

bin/check-test-version: look for API token in .github.api_token

---

config.json

This is to get you all started with the rearrangement of the track, as proposed in #1614
Please note that I don't know Python; this was done based on the changes I made to the Ruby track. 
Hope it helps!
1. Copy Ruby's core exercise progression as a first step to help decrease the mentoring workload.
2. For easy reference, I put all the core exercises at the top of the file. 
3. Removed Leap as a core exercises, and choose other cores to unlock the side exercises that used to depend on Leap
4. Raindrops was marked 'deprecated', but is part of the Ruby core; I reinstated it for now.
5. In Ruby Difference of Squares and Grain are still cores, but will be changed to sides. As Python didn't have them as core, I left it like that. 
6. In Ruby, Robot Name is a core, but it is not an exercise in …

Copy Ruby Track's core progression

---

exercises/acronym/acronym_test.py

Add underscore emphasis test.
Fixes #1643

acronym: update tests to 1.7.0

---

exercises/two-fer/two_fer.py

The Two-Fer exercise is quite a simple one which really requires only two pieces of knowledge in any language:
- How do you append strings?
- How do you create default parameters?
In Python, the first is trivial, while the second is slightly trickier.  As written, the example code already provides the answer to the second question which is a massive spoiler, making the exercise far too easy in my opinion.  With this PR, I propose that this be dropped from the exercise, leaving the student to work out how default parameters work for themselves.

two-fer: Remove default parameter from solution stub

---

config.json

This is a first pass of many, designed to improve the track exercise progression.
This pass:
- Removes 'mathy' exercises and those that require the student to re-implement functionality that is already part of the core modules.
- Fix obvious issues in ordering of `core` exercises

Track Restructure (First pass)

---

config.json
exercises/hangman/.meta/hints.md
exercises/hangman/README.md
exercises/hangman/example.py
exercises/hangman/hangman.py
exercises/hangman/hangman_test.py

Fixes #745 
Solution based on the work of https://github.com/exercism/python/pull/1160
Config file lint with tool `configlet`, shall I keep all the changes in the config?
Ready for review

Implement exercise hangman

---

exercises/list-ops/list_ops_test.py

closes #1677 
Updated list-ops to v2.4.0
See [list_ops_test.py](https://github.com/exercism/python/blob/master/exercises/list-ops/list_ops_test.py)
See [v2.4.0 commit](https://github.com/exercism/problem-specifications/commit/779fa9c6ffb915bd87305be13507f243e7db5cbb#diff-637e4f7a1434d17126301fcffc3bbcbe)

list-ops: update tests to v2.4.0

---

config.json

`high-scores` is the first core test suite to require the student to use a class. This jump should be noted in the topics.

high-scores: add `classes` topic

---

exercises/leap/leap_test.py

One of the tests in the Leap exercise was being ignored due to missing the `_test` prefix

Stop leap test being ignored

---

exercises/resistor-color-duo/README.md

Exercise was renamed in #1741, but I forgot to regenerate the README.

resistor-color-duo: regenerate README to apply rename

---

exercises/armstrong-numbers/armstrong_numbers.py
exercises/armstrong-numbers/armstrong_numbers_test.py
exercises/armstrong-numbers/example.py

Issue: https://github.com/exercism/python/issues/1762
Update `armstrong-numbers` exercise so it matches [canonical-data.json](https://github.com/exercism/problem-specifications/blob/51418ec78bcca075b586d4c38d66d2c322b488fe/exercises/alphametics/canonical-data.json)
*Also Resolves #1751*

armstrong-numbers: sync with problem-specifications

---

exercises/dominoes/dominoes.py
exercises/dominoes/dominoes_test.py
exercises/dominoes/example.py

- Changed function name in tests, exercise stub, and `example.py` to **can_chain** to conform to `canonical-data.json`.

Dominoes: sync expected test results and input data with problem-specifications

---

exercises/wordy/example.py
exercises/wordy/wordy.py
exercises/wordy/wordy_test.py

Part of #1762
Changed function name to answer in test cases, exercise stub, and example.py to conform with canonical-data.json.
Changed test function names to fit the ones in canonical data.

Wordy : sync with problem-specifications

---

exercises/knapsack/example.py
exercises/knapsack/knapsack.py
exercises/knapsack/knapsack_test.py

- Changed function name to **maximum_value** in tests, `example.py` and exercise stub to conform with `canonical-data.json`.
- Changed function argument names to **maximum_wight** and **items** in `example.py` and exercise stub to conform with `canonical-data.json`.
- Cleaned up indentation and formatting in tests and `example.py` to conform with flake 8
- Changed single letter variable names to words in `example.py`

Knapsack : sync expected test results and input data with problem-specifications.

---

exercises/markdown/example.py
exercises/markdown/markdown.py
exercises/markdown/markdown_test.py

**NOTE:**  `flake8` will report the following for the exercise stub (in this case it isn't really a *stub*, but more a file to refactor):  _**"C901 'parse' is too complex (19)**_".  Which is the point : the file needs to be refactored to reduce complexity.
- Changed  function name to **parse** in tests, `example.py`, and exercise input to conform with `canonical-data.json`.
- Changed abbreviated variable name **res** to **result** in `example.py`, for clarity.
- Changed other single-letter variable names to words in `example.py`, for clarity.

Markdown: sync expected test results and input data with problem-specifications.

---

exercises/leap/example.py
exercises/leap/leap.py
exercises/leap/leap_test.py

- Changed function name to **leap_year** in tests, `example.py`, and exercise stub to conform with `canonical-data.json`.

Leap : sync expected test results and input data with problem-specifications.

---

exercises/meetup/example.py
exercises/meetup/meetup.py
exercises/meetup/meetup_test.py

- Changed function name to **meetup** in tests, `example.py`, and exercise stub to conform with `canonical-data.json`.
- Changed argument names to **day_of_week** and **week** in `example.py` and exercise stub to conform with `canonical-data.json`.
- Re-ordered function arguments in tests, `example.py`, and exercise stub to _year, month, **week**, **day_of_week**_ to conform with the order of inputs in `canonical-data.json`.
- Changed two-letter variable name to **day** in `example.py`, for clarity

Meetup : sync expected test results and input data with problem-specifications.

---

exercises/list-ops/example.py
exercises/list-ops/list_ops.py
exercises/list-ops/list_ops_test.py

- Changed function names to  **map** and **filter** in tests, `example.py`, and exercise stub to conform with `canonical-data.json`.
- Changed changed function argument names to **list**, **inital**, and **function** in `example.py` and exercise stub to better conform to `canonical-data.json`.
- Changed references to single, two-letter, and abbreviated variable names in `example.py` to whole words for clarity.

List ops: sync expected test results and input data with problem-specifications.

---

exercises/minesweeper/example.py
exercises/minesweeper/minesweeper.py
exercises/minesweeper/minesweeper_test.py

- Changed name of function to **annotate** in tests, `example.py`, and  exercise stub to conform with `canonical-data.json`.
- Changed function argument name to **minefield** in tests, `example.py` and exercise stub to conform with `canonical-data.json`.
- Changed the following in `example.py` for clarity:
- single-letter **r** variables to **row**  
- single-letter **b** variables to **board**.
-  **i1 / i2** variable references to **index1 / index2**
- **rowlen / collen** variable references to **row_len / col_len** 
- **cset** to **character_set**
- Changed the layout of tests list input/output to contain less vertical space to conform with `flake8` tests.

Minesweeper: sync expected test results and input data with problem-specifications

---

exercises/two-fer/example.py
exercises/two-fer/two_fer_test.py

part of #1762 
- changed the argument of test function to None from empty string.
- rewritten the example to fit the new test

two_fer: sync with canonical data

---

exercises/difference-of-squares/difference_of_squares.py
exercises/difference-of-squares/difference_of_squares_test.py
exercises/difference-of-squares/example.py

- Changed function name to  **difference_of_squares** in test cases, exercise stub, and `example.py` to conform with `canonical-data.json`.
- Changed `example.py` to use the formulas from https://brilliant.org/wiki/sum-of-n-n2-or-n3/, rather than loops.
- Changed argument name in `example.py` and exercise stub to **number** from _count_.

Difference of squares:   sync expected test results and input data with problem-specifications

---

exercises/two-fer/example.py
exercises/two-fer/two_fer_test.py

The changes being reverted by this PR were made to blindly conform to a 1-to-1 interpretation of the canonical data. I have been convinced that these changes are not idiomatic, and should not have been included.
Ref: [community response](https://github.com/exercism/python/pull/1806#issuecomment-497971969)
Maintainer's Note: when test generators are deployed, custom handling may be required for this exercise.

two-fer: revert change to explicit None argument

---

README.md

Following the patterns from previous commits over branch _**drop-python2**_: 
- Removed the references for Python 2.7 from **README.md**
- Updated the Python _3_ version to _3.6_ following the **ABOUT.md** guidelines on #1760.

README.md: Remove references to Python 2.7 from README.md (#1704)

---

docs/TESTS.md

All Python 2 references in this file were about _pytest_ module alternative version to Python 3
Since there aren't other versions than the Python 3 _pytest_, removed **notes** to avoid confusion to the reader.
Kept the section about how to check _pytest_ version, for knowledge purpose to the reader.
Those simplified the file and its readability

TESTS.md: Remove Python 2.7 references from TESTS.md

---

docs/LEARNING.md

- Changed **CodeCademy** reference, due to this course uses Python 2, and the Python 3 one is subscriber only. 
- Applied **SoloLearn** over the **CodeCademy** reference, and kept the description since its an interactive and also good for concept and syntax learning, also includes a certificate, and of course, it's using Python 3 :smile: 
- Removed **Learn Python The Hard Way (Book)** due to its use only Python 2, replaced with **LearnPython.org** tutorial that uses Python 3.
- Also, I did some research before changing those references and tried them, but I'll appreciate if you guys know any better references.
- Other references are already using Python 3. :snake:

LEARNING.md: Remove Python 2.7 references from LEARNING.md

---

exercises/sieve/example.py
exercises/sieve/sieve.py
exercises/sieve/sieve_test.py

part of #1762 
- renamed the function in sieve, test and example to primes in accordance with [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/sieve/canonical-data.json)

sieve: sync with canonical data

---

exercises/nth-prime/example.py
exercises/nth-prime/nth_prime.py
exercises/nth-prime/nth_prime_test.py

- Changed function name to **prime** in tests, `example.py`, and exercise stub to conform with `canonical-data.json`.
- Changed single letter variable names to words in `example.py` for clarity.
- Changed function argument to **number** to conform with `canonical-data.json`.

Nth prime: sync expected test results and input data with problem-specifications

---

exercises/secret-handshake/example.py
exercises/secret-handshake/secret_handshake.py
exercises/secret-handshake/secret_handshake_test.py

part of #1762 
- changed the name of the main function to fit the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/secret-handshake/canonical-data.json) file.

secret handshake: sync with canonical data

---

exercises/prime-factors/example.py
exercises/prime-factors/prime_factors.py
exercises/prime-factors/prime_factors_test.py

- Changed function name to **factors** in tests, `example.py`, and exercise stub to conform with `canonical-data.json`.
- Changed function argument name to **value** in `example.py` and exercise stub to conform with `canonical-data.json`

Prime factors: sync expected test results and input data with problem-specifications

---

exercises/raindrops/example.py
exercises/raindrops/raindrops.py
exercises/raindrops/raindrops_test.py

- Changed function name to **convert** in tests, `example.py`, and exercise stub to conform with `canoncial-data.json`
- Changed function argument name to **number** in `example.py` and exercise stub to conform with `canonical-data.json`
- Changed `example.py` solution to a shorter one using a nested tuple.

Raindrops: sync expected test results and input data with problem-specifications.

---

exercises/rectangles/example.py
exercises/rectangles/rectangles.py
exercises/rectangles/rectangles_test.py

- Changed function name to **rectangles** in tests, `example.py`, and exercise stub to conform with `canonical-data.json`
- Changed function argument name to **strings** in `example.py` and exercise stub to conform with `canonical-data.json`
- Changed most single letter variable names to words in `example.py` for clarity.
-  Changed comparisons to 0 to `if not` checks in `example.py` for clartiy.
-  Replaced nested loop in `search_corners` function to a comprehension in `example.py`

Rectangles: sync expected test results and input data with problem-specifications.

---

exercises/roman-numerals/example.py
exercises/roman-numerals/roman_numerals.py
exercises/roman-numerals/roman_numerals_test.py

- Changed function name to **roman** in tests, `example.py`, and exercise stub to conform with `canonical-data.json`
- Changed function argument name to **number** in tests, `example.py`, and exercise stub to conform with `canonical-data.json`

roman-numerals: sync expected test results and input data with problem-specifications.

---

exercises/reverse-string/reverse_string_test.py

Based off [this](https://github.com/exercism/problem-specifications/commit/6c95c2e50fb4cda7dfcc83de220dd3467d788007):
- added an additional test to conform with the 1.2.0 version of [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/reverse-string/canonical-data.json)

reverse-string: update tests to v1.2.0

---

exercises/luhn/example.py
exercises/luhn/luhn.py
exercises/luhn/luhn_test.py

Based off changes in [this](https://github.com/exercism/problem-specifications/commit/f375a46c1e3d50ecd0347ab1dfc8bbdafc8817c7) and [this](https://github.com/exercism/problem-specifications/commit/d7fdadc4d8f6e2b7d9b2115376c8f59d9dff4840).
- changed the name of `is_valid()` to `valid()` to match [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/luhn/canonical-data.json) description.
- added the missing test case added in 1.6.0
- changed one of the cases to what was changed in 1.6.1

luhn: update tests to v1.6.1

---

exercises/palindrome-products/example.py
exercises/palindrome-products/palindrome_products.py
exercises/palindrome-products/palindrome_products_test.py

- Changed function names to **largest** /  **smallest** in tests, `example.py`, and exercise stub to conform with `canonical-data.json`.
- Changed main function function argument names to **min**, / **max** in tests, `example.py`, and exercise stub to conform with `canonical-data.json`.
- Changed expected data type in tests to **list of lists** to conform with `canoncial-data.json`.
- Changed some function and variable names in `example.py` to better clarify code and remove single letter variable names.
- ~Removed `from __future__ import division` from `example.py`~

Palindrome products:  sync expected test results and input data with problem-specifications.

---

exercises/anagram/anagram_test.py

See issue #1826.  
Note: this implementation uses `assertCountEqual()`, first available in Python 3.2.
"Update tests to v1.4.1" references: https://github.com/exercism/problem-specifications/pull/1534

Anagram: relax test requirement for ordered elements

---

exercises/yacht/example.py
exercises/yacht/yacht.py
exercises/yacht/yacht_test.py

Part of #1762 
Based upon #1809 
- Updated test suite to v1.2.0 of [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/yacht/canonical-data.json).
- Fixed an error in one of the test cases, and renamed functions to match canon.
- Added the same comment concerning enumerated constants as in the sublists exercise.
- Minor variable and message changes to `example.py`

yacht: sync with canonical data

---

exercises/tournament/tournament.py
exercises/tournament/tournament_test.py

part of #1762 
see also #1776 
This was already mostly addressed in #1776, I only did a minor cleanup of the files:
- fixed typos in test function names
- changed the name of the argument to `rows`  to fit what's in [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/tournament/canonical-data.json)

tournament: sync with canon

---

exercises/complex-numbers/complex_numbers.py
exercises/complex-numbers/complex_numbers_test.py

All of the needed method skeletons (`__add__`, `__mul__`, etc.) are provided in the initial solution file except for `__eq__`.
Proposing to add it as well for the sake of consistency.

complex-numbers: add __eq__ skeleton

---

exercises/say/say_test.py

This is absolutely the same as #1835, just messed the commit history the first time.

say: pass 'int' instead of 'float' in test suite

---

exercises/dot-dsl/dot_dsl.py
exercises/dot-dsl/dot_dsl_test.py
exercises/dot-dsl/example.py

Unintentional mutable default arguments lead to surprising results and are confusing to newcomers to say the least ( https://docs.python-guide.org/writing/gotchas ).
A mutable default argument
```python
def __init__(self, attrs={}):
self.attrs = attrs
```
can be replaced with 
```python
def __init__(self, attrs=None):
self.attrs = {} if attrs is None else attrs
```
or possibly even more compact
```python
def __init__(self, attrs=None):
self.attrs = attrs or {}
```
However, this particular exercise forces all of the arguments to be passed through the test suite (specifically, `test_malformed_EDGE`). In that case, I think it makes sense not to provide any defaults for the constructors of `Node` and `Edge` at all, and an immutable default (or, again, no default at all) for the constructor of …

dot-dsl: remove mutable default arguments

---

exercises/kindergarten-garden/example.py

The example.py has a mutable default, improperly named constants, and incorrectly invokes name mangling on a "non-public" class attribute. It's also inefficient.

kindergarten-garden: improve example.py

---

exercises/luhn/example.py

The existing example is convoluted: the multiple methods are unnecessary (and inefficient considering the checksum for a given string need only be calculated once), and the use of a closure in **Luhn.addends** adds complexity without enhancing readability.
Instead here's a straightforward method that should be easier to understand. The only "trick" is the **cadence**, which just reflects the fact that you want to double every even-indexed digit on an even-length card number and every odd-indexed digit on an odd-length card number.

luhn: improve example.py

---

exercises/robot-simulator/robot_simulator_test.py

Fixes #1839 
- changed the test names to fit the new [canonical](https://github.com/exercism/problem-specifications/blob/master/exercises/robot-simulator/canonical-data.json) changes.
- changed the argument of one of the functions to fit canon.
- reordered tests so they make more logical sense.
- reordered arguments in .rotate() tests, to better fit the order in canon.

robot-simulator: update tests to canonical data 3.2.0

---

exercises/pangram/pangram_test.py

Fixes #1841 
- This was just a cosmetic change, renamed the test functions to the [canon](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json)equivalents.

pangram: update tests to canonical data 2.0.0.

---

exercises/forth/forth_test.py

Changes made in 1.7.1 were superficial, so just updating the reference for consistency's sake.

forth: update canonical reference version

---

exercises/rna-transcription/example.py

Remove valid character test, as that's not required by spec any longer.
Also removed some unwieldy Python 2 compatibility code. When we drop support for Python 2 we can just change this to a **str.maketrans** call.

rna-transcription: fix example.py

---

bin/generate_tests.py
config/generator_macros.j2
exercises/twelve-days/.meta/template.j2
exercises/twelve-days/twelve_days_test.py

#1881 must be merged before this PR.

twelve-days: add test template

---

bin/generate_tests.py
config/generator_macros.j2
exercises/acronym/.meta/template.j2
exercises/acronym/acronym_test.py
exercises/clock/.meta/template.j2
exercises/grade-school/.meta/template.j2
exercises/hamming/.meta/template.j2
exercises/hamming/hamming_test.py
exercises/hello-world/.meta/template.j2
exercises/hello-world/hello_world_test.py
exercises/high-scores/.meta/template.j2
exercises/isogram/.meta/template.j2
exercises/kindergarten-garden/.meta/template.j2
exercises/luhn/.meta/template.j2
exercises/matrix/.meta/template.j2
exercises/raindrops/.meta/template.j2
exercises/scrabble-score/.meta/template.j2
exercises/scrabble-score/scrabble_score_test.py
exercises/twelve-days/.meta/template.j2
exercises/twelve-days/twelve_days_test.py
exercises/two-fer/.meta/template.j2
exercises/word-count/.meta/template.j2
exercises/word-count/word_count_test.py

Import macros with context allows standard header/footer macros to access variables from the exercise spec so they do not need to be provided as arguments, simplifying test templates significantly.

Use import with context for generators

---

.travis.yml
bin/template_status.py

`template_status.py` will check each exercise and report the following states:
- Template not found
- Template contains syntax error
- Template creates tests that are either invalid Python code or do not pass with the current example solution
Running this script in the CANONICAL_SYNC job will provide a reference for which exercises are still missing templates.

Add template status script

---

exercises/leap/leap_test.py
exercises/matrix/matrix_test.py

Against policy, this PR modifies two exercises. Exception to policy is being made to clear up a failing CI job.
#1920 created to track the issue that is temporarily mitigated by this PR.
Closes #1917 by mutual exclusion
Closes #1919 by mutual exclusion

leap, matrix: update tests

---

exercises/etl/.meta/template.j2
exercises/etl/etl_test.py

Currently, there are two minor issues with the generated test file which appear to be with the black auto formatter:
1- Dictionary entries are ALWAYS on separate lines, which makes them less easy to read when dealing with small entries. Like [here](https://github.com/exercism/python/compare/master...alirezaghey:issue-%231915?expand=1#diff-6162c6d7d91d9dc13cbdf39e188b596fR35)
2- These very same entries have a redundant comma after their last entry. Like [here](https://github.com/exercism/python/compare/master...alirezaghey:issue-%231915?expand=1#diff-6162c6d7d91d9dc13cbdf39e188b596fR60)
**edit**:
Resolved #1915

Resolved Issue #1915

---

config.json

As per [this link](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt), `control_flow_if_else_statements` is not a valid topic, but `conditionals` is.

high-scores: Fix invalid topic name

---

bin/generate_tests.py

Allows for template creation in a Windows environment.
The Jijna environment/loader expects forward slashes for the path used to find a template. In a Windows environment `os.path.join` produces a string with backslashes. We can use `posixpath.join` instead to make sure that the template path is always created with forward slashes.

Update template path formatting

---

exercises/armstrong-numbers/.meta/template.j2
exercises/armstrong-numbers/armstrong_numbers_test.py

This PR adds a template for armstrong numbers #1927 
However I'm having an issue generating the tests. The generator script doesn't find the template. 
Running `bin/generate_tests.py -v armstrong-numbers` gives me the following console output
`DEBUG:generator:armstrong-numbers\.meta\template.j2`
`INFO:generator:armstrong-numbers: no template found; skipping`

Armstrong numbers add test template

---

exercises/rotational-cipher/.meta/template.j2
exercises/rotational-cipher/rotational_cipher_test.py

Resolves #1982.
Sorry about the seemingly large number of changes. I've changed the `'` to `"` everywhere for consistency since otherwise there was a single case which used an apostrophe in the text, so only that had double quotes.

rotational-cipher: Add test template.

---

bin/generate_tests.py

Fix incorrect error message when black is not installed. Decided to handle it in two locations, just in case someone uses this as a library and not via the CLI.
Resolves #2060

generator: handle no local black install

---

exercises/nth-prime/.meta/additional_tests.json
exercises/nth-prime/.meta/template.j2
exercises/nth-prime/nth_prime_test.py

Add meta template and additional_tests.json to generate nth-prime test file including all tests currently contained in the nth_prime_test.py file. test_case macro is split conditionally to handle error cases, single number cases and ranges of primes. Closes: #1962

nth-prime: add template

---

config/generator_macros.j2
docs/GENERATOR.md
exercises/binary-search/.meta/template.j2
exercises/bowling/.meta/template.j2
exercises/hamming/hamming_test.py
exercises/perfect-numbers/.meta/template.j2
exercises/satellite/.meta/template.j2
exercises/scale-generator/.meta/template.j2
exercises/scale-generator/scale_generator_test.py
exercises/series/.meta/template.j2
exercises/sgf-parsing/.meta/template.j2
exercises/variable-length-quantity/.meta/template.j2
exercises/wordy/.meta/template.j2

- Document built-in generator filters
- For `macros.footer()`, do not require explicit _has_error_case param for footer macro, but still allow it

Docs and macros improvements

---

exercises/hamming/.meta/template.j2
exercises/hamming/hamming_test.py

Small fix.
After #2084 change, hamming's test suite has utility methods section rendered twice.

hamming: remove doubled utility methods

---

exercises/grains/.meta/template.j2
exercises/grains/example.py
exercises/grains/grains.py
exercises/grains/grains_test.py

Add test template for grains which adds all square() tests and the method to generate the only existing total() test. Closes #1952.

grains: add test template

---

exercises/rational-numbers/.meta/template.j2
exercises/rational-numbers/rational_numbers_test.py

Resovles #1975 
I've a problem with template and `if/elif` conditions. Maybe you can help me why `if` conditions only works for 'Arithmetic' description? When you look at `rational_numbers_test.py`: 74 the tests are only rendered for for that group of cases. Other like 'Absolute value' are omitted.

rational-numbers add template

---

bin/generate_tests.py

Proposal to allow template authors to specify additional Python code to support their templates.
*Reason:* some things are very, very verbose in Jinja. The example that prompted this was the `react` exercise. The [spec](https://github.com/exercism/problem-specifications/blob/master/exercises/react/canonical-data.json) for this exercise is quite complex. There was a need to find all unique callback names in each test case. In Python, this is quite easy:
```
callbacks = sorted({
op["name"]
for op in case["input"]["operations"]
if op["type"] == "add_callback"
})
```
In Jinja (which does not support comprehensions), this is quite difficult. However, if template authors were able to have a `.meta/plugins.py`, they could include the above snippet (which is totally not re-usable for other …

generator: Add support for exercise plugins

---

exercises/forth/.meta/template.j2
exercises/forth/example.py
exercises/forth/forth_test.py

This adds the test template for forth track.
I updated example.py as the template generates ValueError exceptions instead of StackUnderflowError or ZeroDivisionError.
There might be a test version to be updated somewhere to tell the test is not exactly the same as before but I didn't find where.
Resolves: #1949

forth: add test template

---

exercises/resistor-color/.meta/template.j2
exercises/resistor-color/resistor_color_test.py

I add the test template for Resistor Color exercise, resolve #1978

resistor-color: Add test template

---

exercises/alphametics/.meta/template.j2
exercises/alphametics/alphametics_test.py

Resolve #1925.
There's no skipped test in this commit. I don't find any field in the canonical file indicating that a test should be skipped.

Add test template for alphametics

---

bin/generate_tests.py
exercises/alphametics/.meta/template.j2
exercises/alphametics/alphametics_test.py

Adds a function to the render environment to allow line wrapping of VERY long strings. Updates the alphametics test file as an example, as it had a string that ran to over 1400 columns width.

generate_tests: option to wrap long lines

---

bin/generate_tests.py

Current version forces 3.7, but one of the few pains of being on Arch Linux is that _suddenly_ you're on 3.8, and you can't run the script anymore.
Sigh.

generate_tests: allow newer Python versions

---

bin/generate_tests.py
exercises/phone-number/.meta/additional_tests.json
exercises/phone-number/.meta/template.j2
exercises/phone-number/example.py
exercises/phone-number/phone_number_test.py

Resolve #1966. I change the class name to `PhoneNumber` to make it consistent with the canonical file, and also auto-format the example file.

phone-number: add test template

---

README.md

Looks like PyUp.io switched to a [paid model for organization repos](https://pyup.io/pricing/). No one here is paying for this, so drop the badge.
Resolves #2138

remove PyUp.io badge from README

---

.travis.yml
exercises/pov/.meta/template.j2
exercises/pov/pov_test.py

I added Python 3.8 ([released Oct 14, 2019](https://docs.python.org/3/whatsnew/3.8.html)) to Travis CI config and change `assertEquals` to `assertEqual` in POV exercise to fix the deprecation warning.
```
/tmp/tmppvu6epthpov/pov_test.py:131: DeprecationWarning: Please use assertEqual instead.
self.assertEquals(tree.path_to("a", "c"), expected)
```
As far as I understand, they are just alias now: https://stackoverflow.com/questions/930995/assertequals-vs-assertequal-in-python/931011

Add Python 3.8 to Travis CI config

---

exercises/forth/.meta/template.j2
exercises/forth/forth_test.py

The template removed seperate classes per major case, resulting in
several tests with duplicate names and therefore an incomplete test
suite.
This reinstates the distinct classes.
Fixes #2148

forth: reinstate seperate classes

---

exercises/say/.meta/template.j2
exercises/say/example.py
exercises/say/say_test.py

I have a problem when I execute generate_test.py  
`error: cannot format /tmp/tmp3247y8ob: Cannot parse: 43:6: , one hundred)
Traceback (most recent call last):
File "bin/generate_tests.py", line 331, in <module>
generate(**opts.__dict__)
File "bin/generate_tests.py", line 297, in generate
if not generate_exercise(env, spec_path, exercise, check):
File "bin/generate_tests.py", line 214, in generate_exercise
format_file(tmp.name)
File "bin/generate_tests.py", line 176, in format_file
check_call(["black", "-q", path])
File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['black', '-q', '/tmp/tmp3247y8ob']' returned non-zero exit status 123.
`

say: add test template 

---

config/maintainers.json

Add Pedro Romano to maintainers.

---

docs/GENERATOR.md
exercises/bob/bob_test.py

Also added a small clarification in the docs on where to run the test generator.
Relevant language changes:
https://github.com/exercism/problem-specifications/pull/1631/files
https://github.com/exercism/problem-specifications/pull/1632/files
resolves: https://github.com/exercism/problem-specifications/issues/1630
unblocks: https://github.com/exercism/python/pull/2165

Update tests for Bob.

---

exercises/word-count/.meta/additional_tests.json
exercises/word-count/word_count_test.py

This is a localized version of a change I discussed with the main problem-specs repo. They told me that, due to their lockdown, I should bring this to the language-specific repositories.
Effectively, the problem states that contractions ("can't", "won't", etc.) should treat apostrophes as part of the word, but rule 3 states:
Other than the apostrophe in a contraction all forms of punctuation are ignored
As such, I've added a very simple case testing that normal apostrophes are removed. The following code (while bad) should do a good job of showcasing a solution that passes all the live tests but fails the new one:
```
from string import punctuation
def count_words(sentence): 
dict = {}
punc = punctuation.replace("'",'')
for val in punc:
if val in sentence:
sentence = sentence.replace(val, …
```

word-count: Add multiple apostrophes test case

---

exercises/book-store/example.py

The existing example.py is quite complex and not particulary efficient,
even for quite small lists of books. This example.py is much simpler,
but could be made considerably more efficient through a bit of a caching
and some sensible short-circuit returns. These are left to the student
to figure out, however.
This one will also pass the new tests in #2174.

[book-store] Simplify example.py

---

exercises/zipper/.meta/template.j2
exercises/zipper/example.py
exercises/zipper/zipper_test.py

Adds a test template for `zipper`, removes the need for #2160, which was
going down a much more complicated path. Updates example.py for a minor
change in the canonical data for `Zipper.up()`.
Closes #2005.

[zipper] add template

---

exercises/book-store/.meta/additional_tests.json
exercises/book-store/.meta/template.j2
exercises/book-store/book_store_test.py
exercises/book-store/example.py

Adds tests that requires use of booth groups of 4 and 5 volumes.
Closes #2141, which had gone stale.

[book-store] Add additional tests

---

bin/generate_tests.py
exercises/sgf-parsing/.meta/template.j2
exercises/sgf-parsing/sgf_parsing_test.py

Fixes issue with pytest throwing a warning on invalid escapes.
Closes #2176

[sgf-parsing] fix escaped characters

---

exercises/grep/.meta/template.j2
exercises/grep/grep_test.py

Updates `grep` to use mock, per the work of @AnAccountForReportingBugs, with minor modifications (fallback after KeyError wouldn't work as is, and we want it to error loudly anyway).
Closes #2147.

[grep] Use mock for unit testing

---

config/maintainers.json

This maintainer seems to have removed himself from @exercism/python, but not from maintainers.json. Furthermore, I believe his GitHub username has changed, so this is now an invalid entry.

remove m-a-ge from maintainers list

---

bin/generate_tests.py
exercises/diffie-hellman/.meta/template.j2
exercises/diffie-hellman/diffie_hellman_test.py

-Add jinja2 test template for Diffie Hellman exercise #1944 
- Split `to_snake` into two functions (`to_snake_base` and `to_snake`)
- Register `to_snake_base` jinja2 macro
- Generate new test template

diffie-hellman: add test template 

---

config.json

Per discussions on [issue 1780](https://github.com/exercism/python/issues/1780), the `error-handling` exercise probably needs a full re-write.  Until that can be completed, we're deprecating the exercise for the Python track.

Marking `error-handling` Side Exercise Deprecated

---

exercises/pythagorean-triplet/pythagorean_triplet.py

Removed the two extra functions in the pythagorean-triplet exercise that weren't covered by tests, and weren't included in the canonical test data.

pythagorean-triplet: Removed unnecessary functions from student file

---

config.json

**Supersedes**  #2313   Updated our current concept exercises with `status`. While all of these are still pending implementation tests, I felt as though some of them were close enough to done to be flagged `beta`. This will be updated again as we complete more exercises:
"name": "Processing Logs", ("strings")
"status": "wip"
"name": "Tisbury Treasure Hunt" ("tuples")
"status": "beta"
"name": "Guido's Gorgeous Lasagna" ("basics")
"status": "beta"
"name": "Ghost Gobble Arcade Game" ("bools")
"status": "beta"
"name": "Pretty Leaflet"("string-formatting")
"status": "wip"
"name": "Inventory Management"("dicts")
"status": "wip"
"name": "Log Levels"("enums")
"status": "wip"
"name": "Elyse's Enchantments"("lists")
"status": "wip"
"name": "Chaitana's Colossal Coaster"("list-methods")
"status": …

Updated concept exercise status for current concept exercises.

---

exercises/practice/roman-numerals/roman_numerals_test.py

See https://github.com/exercism/problem-specifications/pull/1777

roman-numerals: rename tests for clarity

---

.github/workflows/ci-workflow.yml
bin/test_exercises.py
exercises/concept/currency-exchange/.meta/config.json
exercises/concept/currency-exchange/.meta/exemplar.py
exercises/concept/currency-exchange/exchange.py
exercises/concept/currency-exchange/exchange_test.py
exercises/concept/making-the-grade/.meta/exemplar.py

Certain exercises were missing the `unittest.main` footer, preventing their tests from running in CI. As much of our tooling depends on pytest anyway, this PR changes the script to invoke pytest from the current Python executable. Will fail if pytest not installed for that Python version.

use pytest in CI script

---

bin/data.py
config.json

**⚠ This PR requires you to make a simple change before merging. ⚠**
---
To save maintainers from having to manually specify the `files` key in their exercises' `.meta/config.json` files, we are providing support for track-level patterns. See [this PR](https://github.com/exercism/docs/pull/58) for details.
This PR adds (**purposefully wrong**) file patterns to the `config.json` file. It is up to you, the track maintainers, to change these patterns to their correct value.
You can use the following placeholders:
- `%{kebab_slug}`: the `kebab-case` exercise slug (e.g. `bit-manipulation`)
- `%{snake_slug}`: the `snake_case` exercise slug (e.g. `bit_manipulation`)
- `%{camel_slug}`: the `camelCase` exercise slug (e.g. `bitManipulation`)
- `%{pascal_slug}`: the `PascalCase` exercise slug (e.g. …

🤖 Add file patterns to config.json

---

concepts/dict-methods/about.md
concepts/dict-methods/introduction.md
concepts/dict-methods/links.json

Added/wrote the following files for the `dict-methods` concept:
* `about.md`
*  `introduction.md`
*  `links.json`

[V3] Add Dict methods concept files

---

docs/TOOLS.md

We can't have relative links on the website to images. So this guards against this breaking.

Update to absolute image paths in prep for website

---

concepts/numbers/links.json

`URL` --> `url`. 
Python had a configlet linting error :  `Invalid capitalization of the url key:`, as referenced in https://github.com/exercism/configlet/pull/171.  
This fixes that error.

Corrected JSON formatting error.

---

exercises/practice/secret-handshake/.docs/instructions.append.md
exercises/practice/secret-handshake/.meta/example.py
exercises/practice/secret-handshake/.meta/plugins.py
exercises/practice/secret-handshake/.meta/template.j2
exercises/practice/secret-handshake/secret_handshake.py
exercises/practice/secret-handshake/secret_handshake_test.py

secret-handshake: make input a binary string instead of integer

---

concepts/basics/.meta/config.json
concepts/bools/.meta/config.json
concepts/dicts/.meta/config.json
concepts/enums/.meta/config.json
concepts/list-methods/.meta/config.json
concepts/lists/.meta/config.json
concepts/none/.meta/config.json
concepts/numbers/.meta/config.json
concepts/string-formatting/.meta/config.json
concepts/string-methods/.meta/config.json
concepts/strings/.meta/config.json
concepts/tuples/.meta/config.json

Added concept blurbs, authors and contributors for the following concepts:
- `basics`
- `bools`
- `dicts`
- `enums`
- `list-methods`
- `lists`
- `none`
- `numbers`
- `string-formatting`
- `string-methods`
- `strings`
- `tuples`

Added concept blurbs and authors for existing concept exercises.

---

bin/data.py
config.json

-  Added `UUID4`, `slug`, and `name` of currently defined python concepts to `config.json`
-  Added `prerequisites` and `practices` for practice exercises that have been flagged `deprecated`
- (_trinary, strain, proverb, point-mutations, pascals-triangle, parallel-letter-frequency, octal, nucleotide-count, hexadecimal, error-handling, binary, and accumulate._)
-  Added `list-methods` as a prerequisite for `loops`
-  Ran Prettier to format
-  Changed `bin/data.py` to remove `blurb` as a property from `class Concept`.  Concept blurbs have been moved to a `.meta/config.json` file under `python/concepts/<concept name>`.

Added concept `UUIDs`, deprecated exercise prerequisites, and adjusted  prereqs for `loops`

---

config.json

There was a duplicate prerequisite for the atbash-cipher exercise, which causes the track to not sync properly.
Closes https://github.com/exercism/website/issues/846

Fix duplicate prerequisite

---

bin/data.py
config.json

This PR adds adds two new keys to the `online_editor` property in the `config.json` files:
1. `ace_editor_language`: the language identifier for the Ace editor that is used to edit code on the website
2. `highlightjs_language`: the language identifier for Highlight.js which is used to highlight code on the website
For more information, see https://github.com/exercism/docs/pull/124/files
We've pre-populated the values for the two new keys with the track's slug, which is probably the correct value for most tracks. Please check these values are correct for your track:
https://github.com/exercism/v3-launch/issues/32

🤖 Add Ace editor and highlightjs languages to config.json

---

config.json
exercises/concept/black-jack/.docs/hints.md
exercises/concept/black-jack/.docs/instructions.md
exercises/concept/black-jack/.docs/introduction.md
exercises/concept/black-jack/.meta/config.json
exercises/concept/black-jack/.meta/design.md
exercises/concept/black-jack/.meta/exemplar.py
exercises/concept/black-jack/black-jack.py
exercises/concept/black-jack/black-jack_test.py

This is a reconstruction of PR [2949](https://github.com/exercism/v3/pull/2949) that was closed.  We were unable to contact the authors, but did not want the work to go unused or unacknowledged.  This is reproduced as-is, and will probably need to be reviewed and edited, but I wanted to get the PR done before it slipped through the cracks.  The exercise is currently flagged as WIP in `config.json`

Reconstituted V3 Repo PR2949 (https://github.com/exercism/v3/pull/2949)

---

concepts/conditionals/.meta/config.json
concepts/conditionals/about.md
concepts/conditionals/introduction.md
concepts/conditionals/links.json

Filled in docs for the `conditionals` concept.
- Added `introduction.md`
- Added `about.md`
- Added `links.json`
- Added blurb in `.meta/config.json`
- Added authors in `.meta/config.json`

Concept Conditionals Add Files

---

exercises/concept/black-jack/.meta/config.json
exercises/concept/card-games/.meta/config.json
exercises/concept/chaitanas-colossal-coaster/.meta/config.json
exercises/concept/currency-exchange/.meta/config.json
exercises/concept/ghost-gobble-arcade-game/.meta/config.json
exercises/concept/guidos-gorgeous-lasagna/.meta/config.json
exercises/concept/inventory-management/.meta/config.json
exercises/concept/little-sisters-essay/.meta/config.json
exercises/concept/log-levels/.meta/config.json
exercises/concept/making-the-grade/.meta/config.json
exercises/concept/pretty-leaflet/.meta/config.json
exercises/concept/restaurant-rozalynn/.meta/config.json
exercises/concept/sets/.meta/config.json
exercises/concept/tisbury-treasure-hunt/.meta/config.json

This is a re-implementation of [PR2431](https://github.com/exercism/python/pull/2431), minus the picked-up history.
Includes
- `black-jack` (_comparisons_)
- `card-games` (_lists_)
- `chaitanas-colossal-coaster` (_list-methods_)
- `currency-exchange` (_numbers_)
- `ghost-gobble-arcade-game` (_bools_)
- `guidos-gorgeous-lasagna` (_basics_)
- `inventory-management` (_dicts_)
- `little-sisters-essay` (_string methods_)
- `log-levels` (_enums_)
- `making-the-grade` (_loops_)
- `pretty-leaflet` (_string-formatting_)
- `restaurant-rozalynn`(_none_)
-  `sets`
- `tisbury-treasure-hunt` (_tuples_)

[PR2431 Re-Do]: Added Website icons to .meta/config.json exercise files.

---

config.json

Had too many (still) in:
- numbers
- strings
- conditionals
The `practices` arrays for `deprecated` exercises  were also being picked up on the page (_see [Issue #55](https://github.com/exercism/v3-beta/issues/55) in the V3-Beta Repo_), so zeroed those out for the 12 deprecated exercises on the track.

Cleaned up Deprecated Exercise Entries & Edited Excess Refrences

---

.appends/.github/labels.yml

Added Missing EndQuote on Line 163, to fix YAML linting errors on combined labels file.

Fix Missing EndQuote on Line 163

---

.appends/.github/labels.yml
.github/workflows/stale.yml

We keep getting issues flagged stale that we don't intend to.  Changed our `stale` action to only check (any of) the following labels, and otherwise leave things alone:
- `x:status/claimed`
- `claimed 🐾`
- `in-progress 🌿`
- `status/draft`
- `experimental 🔬`
- `dependencies`
- `do not merge 🚧`
- `status/wontfix  🙅🏽`
- `duplicate`
- `first-timers only 🐣`
- `github_actions`
- `good first issue`
- `good first patch`
- `hacktoberfest 🍁`
- `hacktoberfest-accepted ☑`
- `invalid`
- `python`
- `security 🚨`
- `wip/content-checking  ☑`
- `wip/proof-reading 👀`
- `wip/story-writing  ✍`
- `wip/style-guideline-checking 📐`
- `spam 🚫`
I also updated `.appends/labels.yml` to omit the excess `abandoned` labels.  We just don't need three of em.  😆

Add New Labels to Stale Action Exempt List

---

config.json

To help unblock [Beta Issue 165](https://github.com/exercism/v3-beta/issues/165), removed `comparisons` as a prerequisite from "making the grade" and "meltdown mitigation".

Removed 'comparisons' as a dependency in Concept Tree.

---

concepts/sets/.meta/config.json
concepts/sets/about.md
concepts/sets/introduction.md
concepts/sets/links.json
exercises/concept/sets/.meta/design.md

Created the following docs for the `set` concept:
- `concepts/sets/.meta/config.json`
- `concepts/sets/about.md`
- `concepts/sets/introduction.md`
- `concepts/sets/links.json`
- `exercises/concept/sets/.meta/design.md`

Add `Sets` Concept Documents

---

exercises/concept/currency-exchange/.docs/hints.md
exercises/concept/meltdown-mitigation/.docs/hints.md
exercises/concept/meltdown-mitigation/.docs/instructions.md
exercises/concept/meltdown-mitigation/.docs/introduction.md
exercises/concept/meltdown-mitigation/.meta/exemplar.py
exercises/concept/meltdown-mitigation/conditionals.py
exercises/concept/meltdown-mitigation/conditionals_test.py

Closes [#2490](https://github.com/exercism/python/issues/2490)
Found a few things to fix in Currency Exchange and Meltdown Mitigation

Typos on "numbers" concept.

---

concepts/tuples/about.md
exercises/concept/tisbury-treasure-hunt/.docs/instructions.md

Fixes #2502 (minus the table formatting)
Corrected `instructions.md` task 4 to have the function return the string **`"not a match"`** (minus the period) for both the instructions and the code example.
Also fixed some formatting issues in the `about.md` file.

Fixed formatting in about and fixed instruction typos per bug 2502.

---

concepts/tuples/about.md
exercises/concept/tisbury-treasure-hunt/.docs/instructions.md

Removed the excess leading spaces as per the unaccepted feedback from [PR #2503](https://github.com/exercism/python/pull/2503).  @kotp  -- you were right (of course 😄 ).

Removed excess leading spaces from Tuples about and Tisbury Instructions

---

docs/LEARNING.md

Updated LEARNING.md docs

---

docs/TESTS.md
exercises/shared/.docs/help.md
exercises/shared/.docs/tests.md

TEST.md Refresh

---

exercises/concept/making-the-grade/.docs/instructions.md
exercises/concept/making-the-grade/loops_test.py

Related to issue #2526, `test_round_scores()` at Making the Grade should accept any order of rounded data, not just a reversed one.

test_round_scores at Making the Grade accepts any order of rounded data

---

exercises/concept/little-sisters-essay/string_methods_test.py

Some tests were not executing since every test method has to be prefixed with `test`

Follow unittest method naming conventions

---

exercises/concept/currency-exchange/exchange.py

Added missing function to [Currency Exchange](https://exercism.org/tracks/python/exercises/currency-exchange) exercise's `exchange.py` file.
Function `unexchangeable_value()` exists in tests and instructions but not in `exchange.py` file. I don't think it's intentional since this is a learning exercise.
Also changed single to double triple quotes

Added missing 'unexchangeable_value' function to exchange.py

---

docs/TESTS.md

Just a stray parenthesis in there. nbd.

Fix typo in markdown for a link

---

exercises/concept/currency-exchange/.meta/exemplar.py
exercises/concept/currency-exchange/exchange.py

Issue #2545 
Added return type and value in docstrings for `exchange.py` and `exemplar.py` files
Additional: fixed minor typo in `tuples.py`

Fixed docstrings for Currency Exchange

---

exercises/concept/card-games/.docs/instructions.md

Task 6 requires comparison of the averages of odd- and the even- positioned cards, but the instructions stated odd- and even- valued cards, which could have led to a confusion. Fun fact: the tests worked OK for both interpretations, due to the parities of values corresponding to the parities of indexes.

Card Games: rephrase the instructions for Task 6

---

reference/concepts/IDEAL_config.json

Removed blocking and TBD Prerequisite Concept exercises from `config.json`.  Moved the existing `config.json` to `reference/IDEA_config.json` for a ref. as we add future exercises.

Remove Blocking (and Nonexistent) Prerequisites from Config.json

---

concepts/lists/about.md

numbers_to_cube example in "Working with Lists" used "*3" instead of "**3" while the example
description says that numbers are going to be cubed. Due to this typo the example output was
also wrong and had numbers in the list multiplied by three instead of cubes.
This change fixes the operation to be cube as per the description and also fixes the output.

Fixed numbers_to_cube example.

---

pytest.ini

Partially addresses #2539, although documentation should also be updated.
Added basic `pytest.ini` with registration for task mark so Pytest will no longer throw warnings when run locally outside of the test runner.

[Python (PyTest)] Added PyTest ini File to Register Task Custom Mark

---

exercises/concept/meltdown-mitigation/.meta/exemplar.py
exercises/concept/meltdown-mitigation/conditionals.py
exercises/concept/meltdown-mitigation/conditionals_test.py

Related to #2537  & #2535
#2535.

[Meltdow Mitigation] Changes to docstrings and exemplar file for PyLinting

---

concepts/dicts/about.md
concepts/dicts/introduction.md
exercises/concept/inventory-management/.docs/hints.md
exercises/concept/inventory-management/.docs/instructions.md
exercises/concept/inventory-management/.docs/introduction.md
exercises/concept/inventory-management/.meta/config.json
exercises/concept/inventory-management/.meta/design.md
exercises/concept/inventory-management/.meta/exemplar.py
exercises/concept/inventory-management/dicts.py
exercises/concept/inventory-management/dicts_test.py

This is in support of https://github.com/exercism/python/issues/2342.

[Inventory Management] Typo &  Language Edits for dicts Concept and Exercise.

---

exercises/concept/little-sisters-essay/.docs/hints.md

The `endswith` link in the hints.md file had a typo.

Fixed hints.md "endswith" link

---

exercises/concept/card-games/lists_test.py

in `class TestMaybeDoubleLast`
Was:
def test_instructions_example_1(self):
hand = [5, 9, 11]
want = [5, 9, 22]
maybe_double_last(hand)
self.assertEqual(
hand,
want,
msg=f'Expected {want} but got an incorrect result: {hand!r}'
)
Corrected as below in several places.
def test_instructions_example_1(self):
hand = [5, 9, 11]
want = [5, 9, 22]
got = maybe_double_last(hand)
self.assertEqual(
want,
got,
msg=f'Expected {want} but got an incorrect result: {got!r}'
)

[Card Games] Fix Results Oversight in Tests for Maybe Double Last

---

exercises/concept/guidos-gorgeous-lasagna/lasagna_test.py

"Received" instead of "Recieved".
While at it, modified the test to iterate over functions instead of repeating an identical procedure three times.
IMO it is more concise while still easily understandable.

Fix typo in `guidos-gorgeous-lasagna` tests

---

exercises/practice/linked-list/linked_list_test.py

This is a PR for https://github.com/exercism/python/issues/2572.
This PR adds a test to the linked-list exercise, which checks that different calls to `iter()` on the same `LinkedList` instance return independent iterators, (i.e. which change state independently of each other).

Add iterator independence test to linked-list exercise.

---

.github/workflows/ci-workflow.yml

Per notice and instructions listed in [3287](https://github.com/actions/virtual-environments/issues/3287), `ubuntu-16.04` is being deprecated.  Updated this workflow to use `ubuntu-latest`

Update ci-workflow.yml to use ubuntu-latest

---

exercises/concept/meltdown-mitigation/.docs/instructions.md
exercises/concept/meltdown-mitigation/.meta/config.json
exercises/concept/meltdown-mitigation/.meta/exemplar.py
exercises/concept/meltdown-mitigation/conditionals.py
exercises/concept/meltdown-mitigation/conditionals_test.py

Changes:
- Change Task 2 intervals to cover non-integer comparison.
- Rewrite tests to test more points, especially the border cases.
- Reduce number of tests of only one per function, but test many points
(asserts in loop) in each test.
- Remove hints of integer input parameters (they can be any numeric type).

Meltdown exercise change according to issue #2565

---

exercises/concept/card-games/.meta/exemplar.py
exercises/concept/card-games/lists_test.py

- Fix unmatched visual indentation in `TestConcatenateRounds`
- Add a test case for `TestApproxAverageIsAverage` to also check if median equals average
The latter was also not implemented in the example solution, so added it there as well.

Improve tests of `card-games` exercise

---

exercises/concept/currency-exchange/.docs/instructions.md
exercises/concept/currency-exchange/.meta/config.json
exercises/concept/currency-exchange/.meta/exemplar.py
exercises/concept/currency-exchange/exchange.py
exercises/concept/currency-exchange/exchange_test.py

Heya, here are the improvements to the [currency exchange](https://exercism.org/tracks/python/exercises/currency-exchange) concept exercise. This was discussed over at issues #2591 and #2594. I already reviewed the readability of the instructions, but I'd like to get a second opinion on that as that was the main point of the first issue.
The exercise passes the tests as normal. Most of the improvements are grammar and language-related, for example `unexchangable_value()` was technically correct, but it has been changed to `non_exchangeable_value()` for extra clarity. The points of interest were clarified in issue #2594.
Thank you!

Currency Exchange]: Improvements

---

exercises/concept/meltdown-mitigation/conditionals.py

I noticed this while implementing a solution for meltdown-mitigation. The README and tests agreed that it should be 90%, but the docstring showed 40%.

Correct fail_safe docstring

---

exercises/concept/card-games/.meta/config.json
exercises/concept/card-games/lists_test.py

Tests of `card-games` are refactored to cover more cases, utilize `subTest` and (hopefully) are now more readable and maintainable.
The promised follow-up to #2590.
Partially addresses #2605.

Refactor tests of `card-games`

---

exercises/concept/guidos-gorgeous-lasagna/.docs/instructions.md

The example code for instruction 3 has a tuple as input but per the test cases and pre-fab docstring it should take a "str, list" (as opposed to "tuple(str, list)"). In short there are extra parenthesis.
In instruction 4 the second code example returns `{'blue cheese', 'pinenuts', 'pork tenderloin'}` but with the current data in sets_categories_data.py should return `{'pork tenderloin', 'blue cheese', 'pine nuts', 'onions'}` after correcting the missing space in pine nuts in the input. I'm guessing onions were maybe added later and pine nuts was spaced after the instruction was written.

cater-waiter: Minor code example fixes

---

exercises/concept/black-jack/.docs/hints.md
exercises/concept/black-jack/.docs/instructions.md
exercises/concept/black-jack/.meta/config.json
exercises/concept/black-jack/.meta/exemplar.py
exercises/concept/black-jack/black_jack.py
exercises/concept/black-jack/black_jack_test.py

Partially addresses #2428
Implemented 
- instructions
- code skeleton
- tests
- example solution
- hints
as seemed appropriate.
Relied on https://bicyclecards.com/how-to-play/blackjack for some typical house rules.
Overall, seems in-line with teaching python operators.

Implement `black-jack` concept exercise

---

exercises/concept/guidos-gorgeous-lasagna/lasagna_test.py

`Guido's Gorgeous Lasagna` (basics concept) 
`lasagna_test.py` -- Added a try around the names imported from `lasagna.py` and re-worded the raised error messaging.

[Guido's Gorgeous Lasagna] Added Try-except Around Imports in Test File

---

.github/pr-commenter.yml

The new PR-Commenter for the repo, codename: `Porcupine Revenger`. Made together with @J08K  ❤️
Splitting this into two parts, for sharing of REP purposes.
MERGE FIRST PLEASE

[New Workflow]: Added snippets to the auto-pr-commenter. 2/2

---

exercises/practice/hangman/.docs/instructions.append.md
exercises/practice/hangman/.meta/example.py
exercises/practice/hangman/hangman_test.py
exercises/practice/largest-series-product/.docs/instructions.append.md
exercises/practice/largest-series-product/.meta/example.py
exercises/practice/largest-series-product/.meta/template.j2
exercises/practice/largest-series-product/largest_series_product_test.py
exercises/practice/meetup/.docs/instructions.append.md
exercises/practice/meetup/.meta/additional_tests.json
exercises/practice/meetup/.meta/example.py
exercises/practice/meetup/.meta/template.j2
exercises/practice/meetup/meetup.py
exercises/practice/meetup/meetup_test.py
exercises/practice/minesweeper/.docs/instructions.append.md
exercises/practice/minesweeper/.meta/additional_tests.json
exercises/practice/minesweeper/.meta/example.py
exercises/practice/minesweeper/.meta/template.j2
exercises/practice/minesweeper/minesweeper_test.py

Forth set from [Issue #2563](https://github.com/exercism/python/issues/2563)

[Practice Exercises]: Add Better Error Handling Instructions & Tests for Error Raising Messages (# 4 of 8)

---

exercises/practice/nth-prime/.docs/instructions.append.md
exercises/practice/nth-prime/.meta/example.py
exercises/practice/nth-prime/.meta/template.j2
exercises/practice/nth-prime/nth_prime_test.py
exercises/practice/ocr-numbers/.docs/instructions.append.md
exercises/practice/ocr-numbers/.meta/example.py
exercises/practice/ocr-numbers/.meta/template.j2
exercises/practice/ocr-numbers/ocr_numbers.py
exercises/practice/ocr-numbers/ocr_numbers_test.py
exercises/practice/palindrome-products/.docs/instructions.append.md
exercises/practice/palindrome-products/.meta/example.py
exercises/practice/palindrome-products/.meta/template.j2
exercises/practice/palindrome-products/palindrome_products.py
exercises/practice/palindrome-products/palindrome_products_test.py

Fifth set from [Issue #2563](https://github.com/exercism/python/issues/2563)

[Practice Exercises]: Add Better Error Handling Instructions & Tests for Error Raising Messages (# 5 of 8)

---

exercises/concept/card-games/.docs/introduction.md

a > was missing in the code example

Fix-Python-Card-Game-Introduction-Typo

---

exercises/practice/perfect-numbers/.docs/instructions.append.md
exercises/practice/perfect-numbers/.meta/example.py
exercises/practice/perfect-numbers/.meta/template.j2
exercises/practice/perfect-numbers/perfect_numbers.py
exercises/practice/perfect-numbers/perfect_numbers_test.py
exercises/practice/phone-number/.docs/instructions.append.md
exercises/practice/phone-number/.meta/example.py
exercises/practice/phone-number/.meta/template.j2
exercises/practice/phone-number/phone_number_test.py
exercises/practice/pov/.docs/instructions.append.md
exercises/practice/pov/.meta/example.py
exercises/practice/pov/.meta/template.j2
exercises/practice/pov/pov_test.py
exercises/practice/queen-attack/.docs/instructions.append.md
exercises/practice/queen-attack/.meta/example.py
exercises/practice/queen-attack/.meta/template.j2
exercises/practice/queen-attack/queen_attack_test.py

Sixth set from [Issue #2563](https://github.com/exercism/python/issues/2563)
Labeling this one `large`, due to the editing work required for both `phone-number` and `POV`

[Practice Exercises]: Add Better Error Handling Instructions & Tests for Error Raising Messages (# 6 of 8)

---

exercises/practice/rational-numbers/.meta/template.j2
exercises/practice/rational-numbers/rational_numbers_test.py
exercises/practice/robot-simulator/.meta/template.j2
exercises/practice/robot-simulator/robot_simulator_test.py
exercises/practice/roman-numerals/.meta/template.j2
exercises/practice/roman-numerals/roman_numerals_test.py
exercises/practice/run-length-encoding/.meta/template.j2
exercises/practice/run-length-encoding/run_length_encoding_test.py
exercises/practice/saddle-points/.docs/instructions.append.md
exercises/practice/saddle-points/.meta/template.j2
exercises/practice/saddle-points/saddle_points_test.py
exercises/practice/satellite/.docs/instructions.append.md
exercises/practice/satellite/.meta/template.j2
exercises/practice/satellite/satellite_test.py

Seventh set from [Issue #2563](https://github.com/exercism/python/issues/2563)
**`Note:`** For the exercises that did not have error cases, the generic "error handling" macro was removed from the JinJa2 templates, and the test files were re-generated.

[Practice Exercises]: Add Better Error Handling Instructions & Tests for Error Raising Messages (# 7 of 8)

---

exercises/concept/log-levels/.meta/exemplar.py
exercises/concept/log-levels/enums.py

For log-levels `(Enums concept)`, proper docstrings  are added to stub file `(enums.py)` and `exemplar.py`.
Example docstrings were referenced and denoted with triple """.

Add doc-strings to stub file and exemplar.py

---

exercises/concept/card-games/.docs/instructions.md

There is both a first level and a second-level header with the text "Instructions". This is not a big problem in the exercise description, but in the editor, the first task is shown as "Instructions", which is not right. I've removed the duplicate header so that Task 1 will be shown correctly as "Tracking Poker Rounds".

Remove duplicate instructions header

---

exercises/concept/currency-exchange/.docs/hints.md

Changed in-line links to reference links.  Hope that this also fixes hint problem.  But either way, it needed to be done to conform to the markdown spec.

[Currency-Exchange]: In-line links to  reference links

---

exercises/concept/tisbury-treasure-hunt/.docs/hints.md

Changed in-line links to reference links.  With some luck , this will fix the hints problem.  But even if it doesn't, the was needed to bring the doc up to the markdown spec.

[Tisbury Treasure Hunt]:  In-line links to Reference Links

---

exercises/concept/little-sisters-vocab/.docs/instructions.md

Remove the secocnd "to" from the sentence `If the root word originally ended in a consonant followed by a 'y', then the 'y' was changed to to 'i'.`

Remove duplicate "to"

---

exercises/practice/queen-attack/.docs/instructions.append.md

The tests check that the two queens are not in the same place - but the instructions don't specify that. So I'm adding that.

[Queen-Attack]: Add instructions for error checking that the two queens are not the same

---

concepts/comparisons/.meta/config.json
concepts/comparisons/about.md
concepts/comparisons/introduction.md
concepts/comparisons/links.json

This PR adds documentation for the Comparisons concept on the python track.
The following files are updated
- ./meta/config.json
- introduction.md
- about.md
- links.json

[New Concept Documents] : comparisons concept #2456

---

bin/data.py
exercises/practice/anagram/.meta/template.j2
exercises/practice/anagram/anagram_test.py
exercises/practice/grade-school/.meta/example.py
exercises/practice/grade-school/.meta/tests.toml
exercises/practice/grade-school/grade_school_test.py
exercises/practice/hamming/.meta/tests.toml
exercises/practice/hamming/hamming_test.py
exercises/practice/markdown/.meta/template.j2

Due to a bug in `bin/data.py`, automated test generation was including test cases flagged `include=false` in the exercise `tests.toml` files.  
This PR:
1. Corrects `TestsTOML` `load()` classmethod in `bin/data.py` to only include test cases where `include != false`
2. Updates the `tests.toml` files for affected exercises
2. Corrects the JinJa templates for affected exercises
3. Includes regenerated test files for the 4 exercises in question.

[Anagram, Grade-School, Hamming and Markdown ]:  Corrected Bad Test files and Templates

---

exercises/practice/accumulate/.meta/example.py
exercises/practice/affine-cipher/.meta/example.py
exercises/practice/all-your-base/.meta/example.py
exercises/practice/allergies/.meta/example.py
exercises/practice/alphametics/.meta/example.py
exercises/practice/armstrong-numbers/.meta/example.py
exercises/practice/atbash-cipher/.meta/example.py
exercises/practice/beer-song/.meta/example.py
exercises/practice/binary-search-tree/.meta/example.py
exercises/practice/binary-search-tree/binary_search_tree.py
exercises/practice/binary-search/.meta/example.py
exercises/practice/binary/.meta/example.py
exercises/practice/bob/.meta/example.py

[Linting]: Lint practice stub files (1 / ?) 

---

exercises/practice/go-counting/.meta/example.py
exercises/practice/grade-school/.meta/example.py
exercises/practice/grains/.meta/example.py
exercises/practice/grep/.meta/example.py
exercises/practice/hamming/.meta/example.py
exercises/practice/hangman/.meta/example.py
exercises/practice/hangman/hangman.py
exercises/practice/hello-world/.meta/example.py
exercises/practice/hexadecimal/.meta/example.py
exercises/practice/house/.meta/example.py
exercises/practice/isogram/.meta/example.py
exercises/practice/kindergarten-garden/.meta/example.py
exercises/practice/knapsack/.meta/example.py

[Linting]: Lint practice stub files (4 / ?)

---

exercises/practice/largest-series-product/.meta/example.py
exercises/practice/ledger/.meta/example.py
exercises/practice/linked-list/.meta/example.py
exercises/practice/luhn/.meta/example.py
exercises/practice/markdown/.meta/example.py
exercises/practice/matrix/.meta/example.py
exercises/practice/minesweeper/.meta/example.py
exercises/practice/nucleotide-count/.meta/example.py
exercises/practice/ocr-numbers/.meta/example.py
exercises/practice/octal/.meta/example.py
exercises/practice/palindrome-products/.meta/example.py
exercises/practice/parallel-letter-frequency/.meta/example.py
exercises/practice/pascals-triangle/.meta/example.py
exercises/practice/perfect-numbers/.meta/example.py
exercises/practice/phone-number/.meta/example.py
exercises/practice/point-mutations/.meta/example.py
exercises/practice/poker/.meta/example.py
exercises/practice/pov/.meta/example.py
exercises/practice/pov/pov.py
exercises/practice/prime-factors/.meta/example.py
exercises/practice/protein-translation/.meta/example.py
exercises/practice/proverb/.meta/example.py
exercises/practice/pythagorean-triplet/.meta/example.py

[Linting]: Lint practice stub files (5 / ?)

---

exercises/practice/wordy/.meta/additional_tests.json
exercises/practice/wordy/.meta/example.py
exercises/practice/wordy/wordy_test.py

See [Issue #2799](https://github.com/exercism/python/issues/2799) for discussion.  Changed the following:
1.  Changed error message in `additional_tests.json` to `syntax error`
2.  Regenerated `wordy_test.py` from JinJa2 template
3.  Updated `example.py` to pass re-generated tests.

[Wordy]: Changed Expected Error Messages for Python-Specific Test Cases

---

exercises/practice/high-scores/.meta/example.py
exercises/practice/high-scores/.meta/tests.toml
exercises/practice/high-scores/high_scores.py
exercises/practice/high-scores/high_scores_test.py

Per discussion in issue #2786, the newly added test cases to get at mutability issues  make no sense for the current Python implementation of this exercise.  
This PR reverts/skips those added test cases in prep for (perhaps) added Python-specific cases for mutability, or re-writing the exercise to be class-based or in a format that better sets up mutability discussions.
1.  Set `Top 3 scores -> Latest score after personal top scores` & `Top 3 scores -> Scores after personal top scores` to `include= false` in `tests.toml.
2. Regenerated test file from JinJa template
3. Edited `example.py` to match and pass tests.

[High Scores]: Skipped "scores after personal top" Test Cases

---

exercises/practice/tournament/.meta/example.py
exercises/practice/tree-building/.meta/example.py
exercises/practice/triangle/.meta/example.py
exercises/practice/trinary/.meta/example.py
exercises/practice/twelve-days/.meta/example.py
exercises/practice/two-bucket/.meta/example.py
exercises/practice/two-fer/.meta/example.py
exercises/practice/variable-length-quantity/.meta/example.py
exercises/practice/word-count/.meta/example.py
exercises/practice/word-search/.meta/example.py
exercises/practice/wordy/.meta/example.py
exercises/practice/yacht/.meta/example.py
exercises/practice/zebra-puzzle/.meta/example.py

[Linting]: Lint practice stub files (8 / 8)

---

exercises/concept/currency-exchange/.docs/instructions.md

I added some additional explanation to steps 1-6, just a few hints to point the user in the right direction of what operation to use. I managed to figure out steps 5 and 6 and I think the new instructions make it more clear on what to do. I also believe this wording is less overwhelming, breaking things into smaller parts.

[Currency Exchange]: Reworded task explanations

---

concepts/basics/links.json

Well after clarifications I did fix it my self and here is the PR :rocket:
This PR resolves the following problem(s):
- There was a link to `https://docs.python.org/3/reference/expressions.html#calls` on this page which held the description `called` that is miss typed, It must follow the link and be typed **_calls_**.

Fixed dictation error in basic concepts links, Closes #2818

---

concepts/basics/introduction.md

An extra space in the function name where it was calling prevented simple copy-paste usage.

Typo in introduction.md

---

exercises/concept/little-sisters-vocab/.docs/instructions.md
exercises/concept/little-sisters-vocab/.meta/exemplar.py
exercises/concept/little-sisters-vocab/strings.py
exercises/concept/little-sisters-vocab/strings_test.py

I noticed that the function actually extracts an adjective, not a noun (The description itself states _The function should return the extracted **adjective** as a verb._).
Also proposed a new sentence (with an adjective) in the test as it was using a noun.

Update noun_to_verb to adjective_to_verb

---

exercises/practice/clock/.docs/instructions.append.md
exercises/practice/clock/.meta/additional_tests.json
exercises/practice/clock/.meta/config.json
exercises/practice/clock/.meta/example.py
exercises/practice/clock/.meta/template.j2
exercises/practice/clock/clock.py
exercises/practice/clock/clock_test.py

This pull request aims to add helpful instructions about the difference between the `__repr__` and `__str__` methods to the Clock exercise, to address #2813.

Clock: adding support for `repr` and `str` functionality

---

concepts/basics/about.md
concepts/basics/introduction.md
exercises/concept/guidos-gorgeous-lasagna/.docs/introduction.md

Hi @BethanyG, I read your comments to the previous PR and checked for all instances of the docstring to `number_to_the_power_of` function. 
I found one more instance, altogether 3 files were changed.
This PR relates to issue: https://github.com/exercism/python/issues/2833
Note 1: Prettier suggests to add one more line after `>>> print(number_to_the_power_of.__doc__)` but I kept the same distance as in the original, because it's supposed to show how the REPL prints output, so I guess not having that blank line is fine?
Note 2: I wanted to update the already created PR (#2834), but some of my changes (updated branch to be in sync with main) must have automatically closed it.

Fix all entries with wrong output for number_to_the_power_of.__doc__

---

exercises/practice/bowling/.meta/template.j2
exercises/practice/bowling/bowling_test.py

error_case tests were being generated with code that always raised exceptions regardless of the user's code; this was disguised as 'passing' tests since they were expecting an exception anyway.
This change means the generator now checks the 'property' field from the canonical-data.json file and correctly calls the `score` method instead of `roll` for error tests where that is specified.
**Edit to add: [issue link here](https://github.com/exercism/python/issues/2839)**

Fix error_case test gen to check for 'score' prpty

---

concepts/comparisons/about.md
concepts/comparisons/introduction.md
config.json
exercises/concept/black-jack/.docs/hints.md
exercises/concept/black-jack/.docs/instructions.md
exercises/concept/black-jack/.docs/introduction.md
exercises/concept/black-jack/.meta/config.json
exercises/concept/black-jack/.meta/exemplar.py
exercises/concept/black-jack/black_jack.py
exercises/concept/black-jack/black_jack_test.py

Added/Changed/Edited files:
----
____
____

[Black Jack]: Comparisons Concept and Concept Exercise Finalization

---

exercises/concept/black-jack/black_jack_test.py

Solution/Modification: Added two extra test cases to the data array in the test_is_blackjack function.
Problem: One can conceivably pass the test_is_blackjack test by calling the value_of_card function for each card, add the results together, and then test if the value was 11 (as an Ace in the value_of_card function is fixed as 1).  However, this alone does not necessarily indicate that blackjack has been achieved, as any two cards that sum to 11 (such as 4 and 7, or 9 and 2) would also pass the test, even though they shouldn't.  For blackjack to occur, one must also check that one of the cards is an Ace (or, alternatively, that one of the cards has a value of 10)

Update to the test_is_blackjack function

---

exercises/concept/cater-waiter/.docs/instructions.md

The instructions referred to a supporting module called 'categories.py'
which doesn't exist. The correct reference is to
'sets_categories_data.py'.
Resolves #2845

Fix module reference in Caiter Waiter concept exercise instructions.md

---

config.json

Closes #2795 
- Added `conditionals` (Meltdown Mitigation) as prerequisite for `strings` (Little Sisters Vocab).
- Added `comparisons` (Black Jack) as prerequisite for `loops` (Making the Grade).
- Removed `conditionals` as prerequisite for `loops` (_`comparisons` has `conditionals` as a prerequisite_.)

[Strings and Loops] Changed Prerequisites for Concept Exercises

---

exercises/concept/ghost-gobble-arcade-game/.docs/hints.md

I was just looking over this and found that only the first sentence had 'operators' (plural) while the other 3 had 'operator' (singular).  Judging by the text in the indirect link, I figured that the latter 3 were incorrect.

ghost-gobble-arcade_game: Fixed typos in hints.md

---

exercises/concept/black-jack/.meta/exemplar.py
exercises/concept/black-jack/black_jack_test.py

I added one more column ('2', 'A', 1) for the test of the "value_of_ace" function to check if the value of the ace we already have in hand is 11.
"Hint: if we already have an ace in hand then it's value would be 11."

I added one more column ('2', 'A', 1) for the test of the "value_of_ace"

---

exercises/concept/chaitanas-colossal-coaster/.docs/introduction.md

#2883
As mentioned in the text of the introduction 'pop' has the parameter 'index'. The syntax is described `<list>.pop(<item>)`. It should be `<list>.pop(<index>)`.

[Chaitana's Colossal Coaster] Corrected spelling mistake in the introduction

---

concepts/basics/about.md

Parenthetical phrase "(Its turtles all the way down)" should be "(it's turtles" etc. - the parenthetical phrase is part of the sentence, so "Its"should not be capitalized, and here, the word should be "it's" because the meaning is "it is," represented by the contraction "it's", not the possessive "Its."

Correct typo in about.md

---

exercises/practice/grade-school/grade_school.py

A bunch of tests call an "added()" method, but the method is not stubbed out. At a minimum, it should be stubbed out.

[Grade School]: Stub out `added` and `add_student` methods that are called in the tests

---

exercises/concept/black-jack/black_jack_test.py

Single quotation mark seems to be used for strings in black_jack_test.py.
I found one string surrounded by double quotation mark.
And I fixed.

fix(concept/black-jack): quotation marks

---

.github/workflows/ci-workflow.yml
exercises/concept/card-games/lists_test.py
requirements.txt

- trim whitespaces in the end of line
- trim blanklines between pytest tasks (PEP 8)

refactor: reformat lists_test.py by pylint

---

exercises/concept/inventory-management/.docs/introduction.md

Changed `(key`, `value`) to (`key`, `value`)
#2897

[Inventory Management] Correct typo in the introduction

---

concepts/comparisons/.meta/config.json

changed "True or False" to "'True' or 'False'" as in the other texts #2906

[Comparisons] Corrected typo

---

exercises/concept/black-jack/black_jack_test.py

I saw this in a submission that passed the test. The incorrect implementation was:
```python
def is_blackjack(card_one, card_two):
if card_one != card_two:
if card_one and card_two in ['J','Q',"K",'A']:
return True 
return False
```
Not sure if I should have opened an issue for this first and if patches like these are accepted but just thought I would open a PR with a possible fix. Let me know!

Add additional test case to black-jack

---

exercises/concept/cater-waiter/.docs/introduction.md

Change `dcts` to `dicts` in the introduction of "Cater Waiter". See #2924

[Cater Waiter] Correct Typo in Introduction

---

exercises/concept/cater-waiter/.docs/introduction.md

Replace **dictionary** `animals` by **set** `birds`. This should be done because the example is about sets. See #2920

[Cater Waiter] Change Dict to Set in Example of Introduction

---

exercises/practice/two-bucket/.docs/instructions.append.md
exercises/practice/two-bucket/.meta/config.json
exercises/practice/two-bucket/.meta/template.j2
exercises/practice/two-bucket/.meta/tests.toml
exercises/practice/two-bucket/two_bucket_test.py

Fixing issue #2916 
Test generator was failing because the new tests contain `error` field which wasn't handled by the old JinJa2 template.
No changes to `example.py` were required.

two-bucket: Update test generation template (#2916)

---

exercises/concept/cater-waiter/.docs/instructions.md

Change "EXAMPLE_INTERSECTIONS" to "EXAMPLE_INTERSECTION" in the example data import statement for problem 7.
"EXAMPLE_INTERSECTIONS" does not exist in sets_categories_data.py; "EXAMPLE_INTERSECTION" does.

Correct typo in instructions.md

---

requirements-generator.txt

JinJa2 is complaining that it can't import `soft_unicode` from markupsafe.  Pinning version to see if that helps fix the CI issue.

Add Markupsafe to generator-requirements.txt

---

exercises/concept/making-the-grade/.docs/instructions.md

In the very first test case, there is a test case of 40.5, and the expected value is 40. This contradicts the instructions which says values of for example 40.50 should round up to 41. This also contradicts the instructions to use round() which rounds values of .5 down.
Here is the test case which contradicts the instructions:
```
@pytest.mark.task(taskno=1)
def test_round_scores(self):
data = [
([], []),
([.5], [0]),
([1.5], [2]),
(
[90.33, 40.5, 55.44, 70.05, 30.55, 25.45, 80.45, 95.3, 38.7, 40.3],
[90, 40, 55, 70, 31, 25, 80, 95, 39, 40]),
```

Updating instructions to match test case

---

concepts/classes/about.md
exercises/concept/ellens-alien-game/.docs/hints.md
exercises/concept/ellens-alien-game/.docs/instructions.md
exercises/concept/ellens-alien-game/.docs/introduction.md

Originally related to #2954, but also included things I found when re-reviewing the docs.
- Cleaned up a few "leftover" typos and wording issues in both exercise and concept docs.
- Added line for **task two** (`hit()`) instructions hinting at choosing Alien health to remain at zero or go below zero.
- Edited `hints` to add note about being able to take alien health below zero.
- Edited `hints` to add more detail on how to go about changing a class attribute and *where* to do it.

[Ellens Alien Game] Cleanup Pass for Docs.

---

exercises/concept/black-jack/.docs/instructions.md

Fix Python syntax in example code

---

exercises/concept/card-games/.docs/hints.md

The in-line style was breaking link display on the website.

Corrected Mis-Formatted Reference Links

---

exercises/concept/guidos-gorgeous-lasagna/.meta/exemplar.py
exercises/concept/guidos-gorgeous-lasagna/lasagna.py

Fixed and under-indentation from lines 9-15 in exemplar. Added a module level docstring in both stub and exemplar files.

[Lasagna]: Added docstring and fixed format

---

exercises/concept/little-sisters-vocab/.docs/introduction.md

Originally showing:
```python
>>> cat_words.split(',')
...
['feline', 'four-footed', 'ferocious', 'furry']
```
which is missing spaces. Fixed to:
```python
['feline', ' four-footed', ' ferocious', ' furry']
```
Tested on Python 3.8.5 and Python 3.10.4 (not that this project supports 3.10, but I don't have 3.9 handy).

[little-sisters-vocab] Minor typo fix in introduction.md

---

CODE_OF_CONDUCT.md
exercises/concept/black-jack/.meta/exemplar.py
exercises/concept/black-jack/black_jack.py
exercises/concept/card-games/.meta/exemplar.py
exercises/concept/card-games/lists.py
exercises/concept/cater-waiter/.meta/exemplar.py
exercises/concept/cater-waiter/sets.py
exercises/concept/chaitanas-colossal-coaster/.meta/exemplar.py
exercises/concept/chaitanas-colossal-coaster/list_methods.py
exercises/concept/ghost-gobble-arcade-game/.meta/exemplar.py
exercises/concept/ghost-gobble-arcade-game/arcade_game.py
exercises/concept/guidos-gorgeous-lasagna/.meta/exemplar.py
exercises/concept/guidos-gorgeous-lasagna/lasagna.py
exercises/concept/inventory-management/.meta/exemplar.py
exercises/concept/inventory-management/dicts.py
exercises/concept/little-sisters-essay/.meta/exemplar.py
exercises/concept/little-sisters-essay/string_methods.py
exercises/concept/little-sisters-vocab/.meta/exemplar.py
exercises/concept/little-sisters-vocab/strings.py
exercises/concept/making-the-grade/.meta/exemplar.py
exercises/concept/making-the-grade/loops.py
exercises/concept/meltdown-mitigation/.meta/exemplar.py
exercises/concept/meltdown-mitigation/conditionals.py
exercises/concept/tisbury-treasure-hunt/.meta/exemplar.py
exercises/concept/tisbury-treasure-hunt/tuples.py

Adresses #2974.
- Making sure a module level (top of file) docstring exists in concepts that need them, such as early exercises.
- Making sure a summary first line (function scope) docstring exists in concepts that need them.
- Making sure that summary first line docstrings begin with an imperative mood as per pycdocstyle [D401](https://manpages.ubuntu.com/manpages/xenial/man1/pydocstyle.1.html#:~:text=D401%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%94%82%20First%20%20%20line%20%20%20should%20%20%20be%20%20%20%20in%20%E2%94%82%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%94%82%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%E2%94%82%20imperative%20mood).
- The summary level and module level docstring should end in a …

Docstring Cleanup 

---

exercises/concept/guidos-gorgeous-lasagna/.docs/instructions.md

The first part of the exercise consist on defining a constant. In the instructions there is an example where the the constant is called as follows:
```python
>>> lasagna.EXPECTED_BAKE_TIME
```
I believe that the constant was probably an atribute from the lasagna class in an earlier version of the problem, and now it just makes it difficult to understand what "lasagna" means in the exercise. 
#3003

Remove lasagna from the constant name (EXPECTED_BAKE_TIME)

---

exercises/practice/high-scores/.meta/config.json
exercises/practice/high-scores/.meta/template.j2
exercises/practice/high-scores/high_scores_test.py

Support the scores property tests. Add myself as a contributor.

high-scores: handle HighScores.scores tests

---

exercises/practice/darts/.docs/hints.md

Per issue #2998 (_which has been resolved in the linked website issue_), nested bullets were not working in `hints` files.
They are now, so this PR restores `hints` for the `Darts` exercise to the nested-bullet state.
Closes #2998.

[Darts]: Restore Nested Bullets

---

exercises/concept/card-games/lists_test.py

Adding in a test for `[1, 3, 5, 7, 9]` to prevent an invalid alternate solution for Task 6.
Alternate solution that passes all current tests: `return card_average(hand) % 2 == 0`.
Fixes #3025 .

[Card Games] Additional test for Task 6.

---

docs/PROBLEM-SOLVING.md
docs/config.json

Per conversation in slack, making a rough-draft doc for general problem solving links and strategies.  Not sure where this will ultimately live, but PR-ing it to the Python track docs for the time being.

[PROBLEM-SOVLING]: Added (very) rough draft of problem solving links

---

docs/TOOLS.md

There are two (at least) reasons for this:
1. The paragraph itself indicates that it is a community effort to
provide this list
2. We indicate a claim of lack of bias (organization wise) based on
- "this is a collection of tools that are popular in the community"
- "it is not intended to be prescriptive"
- welcoming others to add to this list
3. I am not aware of affiliations or lack thereof of any in this list at
this time, in the past, or at any point in the future.
4. It is better to not claim the negative, and instead claim the
affirmative when it happens.  (Less maintenance work.)

Removed mention of non-affiliation

---

concepts/conditionals/introduction.md

When explaining elif (changes in lines 48, 52 and 54):
x > y doesn't necessarily guarantee x > z directly, therefore first check-in (if) should be x > y and y > z, while second check-in (elif) could be y > z, therefore else would return z > x and z > y
Counterexample: x = 15, y = 10, z = 20. The current program (since x > y) would return "x is greater than y and z", when x >z is not true. The revised code would also evaluate x > z, therefore returning "z is greater than x and y"

[Conditionals]: Update introduction.md & about.md

---

exercises/concept/chaitanas-colossal-coaster/.docs/hints.md

I was going through this exercise and noticed that one of the hints was not being displayed due to a missing `#`.

[List Methods]: Fix Markdown Heading in Hints File

---

config.json

_Marked as massive, due to the amount of re-reviewing, visualization, and re-ordering._
These are changes to address issue #2714  & #3023, and include:
<br>
```mermaid
flowchart TD
%%{init: {"theme": "base", "themeVariables": { "fontFamily": "Victor Mono, San Francisco, Roboto", "fontSize" : "18px", "primaryColor": "#D9D7FF", "nodeBorder": "#9F80DF", "lineColor": "#AFAC6A", "clusterBorder" : "#585B5D"}}}%%
classDef TBD fill:#D9D7FF,stroke:#9F80DF,stroke-width:4px,stroke-dasharray: 5 5, color: #734CC4;
classDef Beta fill:#F5DE90,stroke:#F6B303,stroke-width:2px, color:#525952;
classDef WIP fill:#DEE8BB,stroke:#AFAC6A,stroke-width:4px,stroke-dasharray: 5 5, #908D49;
classDef TBD-f fill:#C4D7FF,stroke:#97AFFF,stroke-width:4px,stroke-dasharray: 5 5, #7388CB;
classDef Practice …
```

[Python Track Syllabus]:  Track Re-Ordering

---

exercises/practice/diffie-hellman/.meta/template.j2
exercises/practice/diffie-hellman/diffie_hellman_test.py

[Diffie- Hellman]: Corrected Malformed JinJa2 Template

---

concepts/function-arguments/about.md
concepts/function-arguments/introduction.md
concepts/functions/about.md
concepts/functions/introduction.md

Updating the functions concept to prepare for the functions concept exercise. This includes completing the function arguments concept, which is currently TODO. Function arguments will be lightly covered in functions, but a link to the function arguments concept will be provided, so something should be in there, I think.

[Update Concept] functions, and complete function arguments

---

concepts/decorators/about.md

Adds concept / concept exercise for #2356. This is in a WIP state and is up for any feedback to come in earlier!
Notes:
- error messages have been designed in line with python 3.9. I believe the error messages in question have not been changed between 3.6 and 3.9. I am aware that 3.10 changed many error messages, but I do not know whether the ones used in this concept have been changed. If you would like me to check/update these to be inline with 3.10 then please say! (I chose 3.9 as it is the version currently used by the test runner and I believe that 3.8, which the track itself uses, doesn't make a difference anyway.
In line with the above, should I be basing code samples off 3.8 or 3.9? (I assume when the track updates code samples would have to be updated to)
I will edit this as I …

[New Concept]: Decorators

---

config.json

Noticed that the dashboard :
Was not showing the concept exercises in the same order that the syllabus tree had them.  This should fix that issue, and put the concept exercises in the same order as they appear in the tree.

[Track Config]: Reorganized Concept Exercises

---

README.md

Changed link to config.json to point at the python track config instead of the JavaScript track  config.

Correct config.json link to python

---

exercises/practice/twelve-days/.docs/hints.md

Tagging @exercism/reviewers  since bobahop is traveling for the next week+.
The `hints.md` file for this exercise was getting cut off in the UI due to having multiple top-level headers (see the `hints.md` file as intended [here](https://github.com/exercism/python/blob/main/exercises/practice/twelve-days/.docs/hints.md)):
This PR should fix that.

[Twelve Days]: Corrected Markdown Header Tags in `hints.md` File

---

docs/TDD.md

Added code block endings whose omission caused the links to not parse. Slipped by my critique fatigue.

[TDD.md] Restored omitted code block endings that broke link parsing

---

concepts/bools/about.md
exercises/concept/ghost-gobble-arcade-game/.meta/exemplar.py
exercises/concept/ghost-gobble-arcade-game/arcade_game.py

Changed the touching_power_pellet param docstring on the score() function to accurately reflect the instructions and the param name itself. Changed from "does the player have an active power pellet" to "is the player touching a power pellet".
I've also fixed a small typo on the concepts/bools/about.md file.

[Ghost Gobble Arcade Game] Docstring fix

---

exercises/concept/card-games/.docs/introduction.md

This is a simple fix: one period added to the end of a sentence. I took the time to review [list concept docs](https://github.com/exercism/python/tree/main/concepts/lists) and the [exercise folders](https://github.com/exercism/python/tree/main/exercises/concept/card-games) and failed to find more errors.
This is my first real PR, so I am happy to take feedback.
Also, I am available for more simple, first-time-contributions if they come up. I am using Exercism to learn Python, so any chance to contribute would be welcome.
@BethanyG let me know if I should ping anyone else!
***Thank you!***

Added a period to the introduction.md

---

exercises/concept/black-jack/black_jack_test.py

When solving this exercise, initially I was not considering that an Ace in hand would have the value of 21, so the last test was rightfully failing: `('2', 'A', 1)`:
```python
def value_of_ace(card_one: str, card_two: str) -> int:
c1 = value_of_card(card_one)
c2 = value_of_card(card_two)
diff = 21 - (c1 + c2)
if diff >= 11:
return 11
return 1
```
A quick-fix would have been to just check if `card_two` is an ace, something like:
```python
def value_of_ace(card_one: str, card_two: str) -> int:
c1 = value_of_card(card_one)
c2 = 11 if card_two == 'A' else value_of_card(card_two)
diff = 21 - (c1 + c2)
if diff >= 11:
return 11
return 1
```
This last solution passes the current tests, but it shouldn't, because it is not checking if the first card is an ace.
This PR adds a test where the first …

blackjack: Add test with ace as first card for 'value_of_ace' function

---

exercises/practice/clock/.docs/instructions.append.md

Needed to close the Python code fence for the first block under `Representing Your Class`.

Added Missing Close to Code Fence

---

.github/workflows/ci-workflow.yml
pylintrc
requirements-generator.txt
requirements.txt

**Please Note:** This PR **should not be merged** before reviewing and merging these related PRs:
- [`python-test-runner` #105](https://github.com/exercism/python-test-runner/pull/105)
- [`python-analyzer` #55](https://github.com/exercism/python-analyzer/pull/55)
- [`python-representer` #35](https://github.com/exercism/python-representer/pull/35)
The changes made here depend on the updated tooling images in the linked PRs, so those should be in place first before doing upgrades here.  Otherwise, we risk issues on the site due to missing docker images.
Potentially closes #2656

[Python Version Upgrade]: First Pass at Upgrading Track to  use `python:3.10.6-slim`

---

concepts/numbers/.meta/config.json
concepts/numbers/introduction.md

Corrected underscore rules in concept introduction.
Of the four files checked (concept introduction and about, exercise introduction and instructions) only one file needed to be fixed. Since only the concept was changed, contribution was only added to the concept.
I searched through the repo to determine if it came up anywhere else - later exercises, for instance - but that appears not to be the case.

Correct PEP 515 underscore rules (Ref. issue #3159)

---

pylintrc

As of Pylint `2.6++`, there have been rule deprecations and a few Python feature deprecations.   
When upgrading our tooling to use Python `3.10.6`, we forgot some of these deprecations in this `.pylintrc` file and they will toss errors with the version of Pylint we are using.
This edit should fix that problem.

[Linting]:  Update .pylintrc to Reflect Pylint 2.6++ Deprecations

---

exercises/concept/currency-exchange/.docs/hints.md
exercises/concept/currency-exchange/.docs/instructions.md
exercises/concept/currency-exchange/.meta/config.json
exercises/concept/currency-exchange/.meta/exemplar.py
exercises/concept/currency-exchange/exchange.py
exercises/concept/currency-exchange/exchange_test.py

Fixes #3157 and is somewhat discussed there.
Basically, what I ended up doing is:
- Added a new task asking to implement `get_leftover_of_bills`, which encourages using modulo operator `%`.
- Removed task 6, which was a weird semi-duplicate of task 5 (and also potentially hinted at using `%`).
Also, along the way:
- Tried to make `int` and `float` usage more intuitive.
- Used `assertAlmostEqual` method to compare floating point values in tests.
- Modified some test values to improve the variety of cases being tested.

[Currency Exchange] Improve the `int`/`float` usage consistency

---

exercises/practice/perfect-numbers/.meta/template.j2
exercises/practice/perfect-numbers/perfect_numbers_test.py

Fixes wrong assertion method in "perfect numbers" tests.
Refs.: 
- https://github.com/python/cpython/issues/79031
- https://flake8.pycqa.org/en/latest/user/error-codes.html (F632)

Replace `assertIs` assertion with `assertEqual` for string literals in tests

---

config.json

Added "classes" as a prerequisite for `Gigasecond` so that it will not unlock until a student has completed all the existing learning exercises for the track (currently, the last concept in the syllabus is "classes").   
Hopefully, this avoids confusion and frustration as expressed by user @GKotfis in gitter:

Add Prerequisite to Gigasecond

---

exercises/practice/diffie-hellman/.meta/template.j2
exercises/practice/diffie-hellman/diffie_hellman_test.py

The original code passed a generator expression into the assertion, which was converted into a list prior to being evaluated for truthiness.
Even if all the values in the generator are False, the assertion will check whether `[False, False, False, ...]` is truthy, which it is.
I can't see how this test can ever have failed.
The most obvious solution is to have one assertion for each case that we want to test.
We could fix this by using `all()` around the generator expression, but I don't feel that's good style in tests. We want feedback about what failed, so I've used `subTest()` which is is used in other exercises.

Fix bad assertion in DiffieHellmanTest

---

exercises/practice/tree-building/.meta/example.py
exercises/practice/tree-building/tree_building_test.py

From exercise's [instruction](https://github.com/exercism/problem-specifications/blob/main/exercises/tree-building/description.md) we know that 
> All records have a **parent ID lower than their own ID**, except for the root record, which has a **parent ID that's equal to its own ID**.
But the current exception message in the tests and the example code says the opposite
> Node record_id should be smaller than it's parent_id.
This could lead to misunderstanding while solving the exercise. PR fixes this by replacing parent_id with record_id and vice versa in the exception message
> Node parent_id should be smaller than it's record_id.

[Tree Building] swap parent_id and record_id in the exception message according to the task instruction

---

README.md
exercises/shared/.docs/help.md

The Exerism Forum (https://forum.exercism.org/) has now made Gitter redundant.
We're directing everyone there.

Remove reference to Gitter

---

exercises/concept/tisbury-treasure-hunt/.docs/instructions.md

Resolves issue #3196 
- Fixed the type in the Task 4 example to reflect what is actually passed to the function.

Fixed typo in Task 4 example

---

exercises/concept/cater-waiter/sets.py

I noticed the parameter type for `dish_ingredients` in the docstring is `set`  while the actual type is `list`.  The readme is correct and states the parameter as `list`.

Corrected parameter type stated in docstring

---

.github/workflows/pause-community-contributions.yml

In the original workflow, I had `catch(err) => false`.
But during code review the question was raised:
What happens if we get rate limited and all the requests from the API fail?
(E.g. if we do a script and automatically create PRs across all of Exercism, which is totally a thing).
We were like: ooh, that would suck, wouldn’t it? It would be better if we occasionally had to deal with manually closing a PR.
But here’s the kicker. The API response has no body. It’s either 204 or 404, where 404 is perceived as… an error.
So I changed it, and (importantly) forgot to test the script one final time.
So here is a version that will actually work. (I tested.)

Fail closed on pause contributions workflow

---

exercises/concept/currency-exchange/.docs/instructions.md

Simply remove "new" and "old" specifiers, i.e. clarify through abstraction.

Clarify Currency Exchange instructions

---

exercises/concept/guidos-gorgeous-lasagna/lasagna_test.py

Possibly closes #3181 and #3161.
**To address #3181:**
Modified test file to add `raise from None` for the fenced `ImportErrors` at the top of the test file.  In combination with a test runner fix, this will trim the stack trace for the raised errors, limiting the stack to the last error thrown.
Instead of
```python
ImportError while importing test module '.mnt.exercism-iteration.lasagna_test.py'.
Hint: make sure your test modules.packages have valid Python names.
Traceback:
.mnt.exercism-iteration.lasagna_test.py:6: in <module>
from lasagna import (EXPECTED_BAKE_TIME,
E   ImportError: cannot import name 'bake_time_remaining' from 'lasagna' (.mnt.exercism-iteration.lasagna.py)
During handling of the above exception, another exception occurred: …
```

[Guido's Gorgeous Lasagna] Addressed issues 3181 and 3161 for lasagna test file.

---

exercises/practice/hello-world/.meta/template.j2
exercises/practice/hello-world/hello_world.py
exercises/practice/hello-world/hello_world_test.py

In conjunction with [Python Test Runner #111](https://github.com/exercism/python-test-runner/pull/111), modified the template and regenerated the test file to include explicit error messages about needing a function with a `return`, and not using `print()` for "Hello, World!".
Error message will now read:
```python
ImportError:
MISSING FUNCTION --> In your 'hello_world.py' file, we can not find or import the function named hello(). 
The tests for this first exercise expect a function that returns the string "Hello, World!"
Did you use print("Hello, World!") instead?
```
If the student instead uses the function but replaces `return` with `print()`, they should see the following:
```python
def test_say_hi(self):
msg = "\n\nThis test expects a return of the string 'Hello, World!' \nDid you …
```

[Hello World]: Modified ImportError Message to be More Direct.

---

exercises/practice/rotational-cipher/.approaches/alphabet/content.md
exercises/practice/rotational-cipher/.approaches/ascii-values/content.md
exercises/practice/rotational-cipher/.approaches/introduction.md
exercises/practice/rotational-cipher/.approaches/recursion/content.md
exercises/practice/rotational-cipher/.approaches/str-translate/content.md

See [this forum post](https://forum.exercism.org/t/link-references-in-special-blocks-admonitions-are-not-rendered/3803/5) for the proposed fix for reflinks inside an admonition block. 
Fixed some other msc.  errors while reviewing the docs.

[Rotational Cipher Approaches] Msc link, punctuation, & formatting fixes.

---

config.json

Per discussion with @ErikSchierboom - since the naive solution to `Palindrome Products` often times out tests & the numbers concept appears very early in the track, we thought it best to remove this associated practice exercise from the progression.
**Replacement TBD**, but we do have 6 other practice exercises associated, so it's ok to remove and not replace for now.

[Palindrome Products] Removed Numbers Concept Exercise from Practices Array

---

CONTRIBUTING.md
README.md
docs/ABOUT.md
docs/GENERATOR.md
docs/INSTALLATION.md
docs/LEARNING.md
docs/TESTS.md
exercises/shared/.docs/help.md

**`Do Not Merge Until the Python` [Test Runner](https://github.com/exercism/python-test-runner), [Analyzer](https://github.com/exercism/python-analyzer/pull/63), & [Representer](https://github.com/exercism/python-representer/pull/41) `are Updated to use Python 3.11.2`**
Hope I caught all references.

[Track Documents] Updated for Python 3.10 --> 3.11.

---

exercises/concept/little-sisters-vocab/.docs/introduction.md

The provided translation was from English to Russian. In Ukrainian "nine" is written with an apostrophe - дев'ять.

Fix English-Ukrainian translation typo

---

exercises/practice/accumulate/.meta/tests.toml
exercises/practice/parallel-letter-frequency/.meta/tests.toml
exercises/practice/strain/.meta/tests.toml

These exercises are deprecated for the track, so the `tests.toml` files have been updated to exclude all "new" tests.  The thought being that if we un-deprecated these exercises, they'd be in the old state, and we could see where they'd need changes.
- new file:   exercises/practice/accumulate/.meta/tests.toml
- new file:   exercises/practice/parallel-letter-frequency/.meta/tests.toml
- new file:   exercises/practice/strain/.meta/tests.toml

[Tests.toml] Synced Deprecated Exercises.

---

exercises/practice/largest-series-product/.docs/instructions.md
exercises/practice/largest-series-product/.docs/introduction.md
exercises/practice/largest-series-product/.meta/tests.toml
exercises/practice/largest-series-product/largest_series_product_test.py

The largest-series-product exercise has been overhauled as part of a project to make practice exercises more consistent and friendly.
For more context, please see the discussion in the forum, as well as the pull request that updated the exercise in the problem-specifications repository:
- https://forum.exercism.org/t/new-project-making-practice-exercises-more-consistent-and-human-across-exercism/3943
- https://github.com/exercism/problem-specifications/pull/2246 
Note that we have deprecated and removed two test cases that deal with the multiplicative identity (also referred to as an empty product). By doing this we were able to avoid talking about this at all, which makes this exercise much more approachable.
----
If you approve this pull request, I will eventually merge it. However, if …

Sync largest-series-product docs with problem-specifications

---

exercises/practice/largest-series-product/.docs/instructions.append.md

This patch assumes that the intent of this `instructions.append.md` was to match the actual requirements.

[Largest Series Product] Synchronize Addendum Example Code with Tests

---

exercises/practice/yacht/.approaches/config.json
exercises/practice/yacht/.approaches/functions/content.md
exercises/practice/yacht/.approaches/functions/snippet.txt
exercises/practice/yacht/.approaches/if-structure/content.md
exercises/practice/yacht/.approaches/if-structure/snippet.txt
exercises/practice/yacht/.approaches/introduction.md
exercises/practice/yacht/.approaches/structural-pattern-matching/content.md
exercises/practice/yacht/.approaches/structural-pattern-matching/snippet.txt

As per the blog post on Freeing our Maintainers, the community contributions pause has an exception for writing approaches. This is for Yacht.
Let me know your suggestions. This is my first time, so my apologies if there are any errors in the format.

Write approaches for Yacht

---

exercises/practice/sublist/.approaches/config.json
exercises/practice/sublist/.approaches/introduction.md
exercises/practice/sublist/.approaches/list-manipulation/content.md
exercises/practice/sublist/.approaches/list-manipulation/snippet.txt
exercises/practice/sublist/.approaches/using-strings/content.md
exercises/practice/sublist/.approaches/using-strings/snippet.txt

Few points on my this:
1. I've said that it's better practice not to use magic values, but this isn't exactly magic values. Is it fine, or shall we remove the line? If it _is_ fine, are we allowed to link to SO posts? I normally wouldn't, but for this topic, I liked the explanation there.
2. I've claimed the string approach is less performant than the list one - but I'm not too sure about this, it was just a hunch. Am I correct?
3. I don't really like my titles, feel free to rename them.
4. I myself used the list manipulation approach to solve this problem. I chose the top voted answer for the string approach instead of, say, Bethany's because it seemed simpler. However, upon analysing this solution, I'm not too sure if it's correct. It does pass the tests, but while I've said there's a …

[Sublist] Write approaches

---

exercises/practice/accumulate/.docs/instructions.md
exercises/practice/binary-search/.docs/instructions.md
exercises/practice/binary/.docs/instructions.md
exercises/practice/book-store/.docs/instructions.md
exercises/practice/bowling/.docs/instructions.md
exercises/practice/darts/.docs/instructions.md
exercises/practice/error-handling/.docs/instructions.md
exercises/practice/gigasecond/.docs/introduction.md
exercises/practice/hexadecimal/.docs/instructions.md
exercises/practice/killer-sudoku-helper/.docs/instructions.md
exercises/practice/linked-list/.docs/instructions.md
exercises/practice/nucleotide-count/.docs/instructions.md
exercises/practice/octal/.docs/instructions.md
exercises/practice/pangram/.docs/instructions.md
exercises/practice/pangram/.docs/introduction.md
exercises/practice/parallel-letter-frequency/.docs/instructions.md
exercises/practice/queen-attack/.docs/instructions.md
exercises/practice/roman-numerals/.docs/instructions.md
exercises/practice/saddle-points/.docs/instructions.md
exercises/practice/saddle-points/.docs/introduction.md
exercises/practice/secret-handshake/.docs/instructions.md
exercises/practice/sieve/.docs/instructions.md
exercises/practice/strain/.docs/instructions.md
exercises/practice/sum-of-multiples/.docs/instructions.md
exercises/practice/trinary/.docs/instructions.md
exercises/practice/two-fer/.docs/instructions.md

Synced the `introduction.md` and `instruction.md` files for the following exercises:

Synced `instructions.md` & `introduction.md` Files from Problem Specifications

---

exercises/practice/ledger/.meta/config.json
exercises/practice/ledger/.meta/template.j2
exercises/practice/ledger/.meta/tests.toml
exercises/practice/ledger/ledger.py
exercises/practice/ledger/ledger_test.py

Here is a test of the manual flag.
`Ledger` was recently added to `problem-specifications`, and a new JinJa2 template was made for it.
A new `tests.toml` file was also added, and all test cases were set to active.
However, great pains were taken to not have the canonical data invalidate the existing student solutions.
So the JinJa2 template and resulting new test file (_even though they've "changed"_) should not require re-queueing of student solutions.

[Ledger]: Added JinJa2 Template, Re-Synced Tests & Regenerated Test Files 

---

exercises/practice/accumulate/.docs/instructions.md
exercises/practice/error-handling/.docs/instructions.md

These two exercises are deprecated for the track.  
Nevertheless, we've synced instructions for them. 
This **should not** re-queue any of the solutions for testing -- both because they are instructions, and because they are not active on the track.

[Accumulate & Error-Handling]: Synced Instructions (Deprecated Exercises)

---

exercises/practice/say/.docs/instructions.append.md

Missing a 9 in the unit's digit. Does not match the desciption given at instructions.md of "It's fine to stop at "trillion".

[Say]:  Instruction Append Typo in writing 999 billion .... 999 thousand 999

---

exercises/concept/little-sisters-vocab/strings.py

Tiny tweak based on https://forum.exercism.org/t/little-sisters-vocabulatry-discrepency-between-test-and-docstring-for-adjective-to-verb/6949/3

little-sisters-vocab: Update stub to match instructions

---

exercises/concept/meltdown-mitigation/.docs/instructions.md

It seems a few people get stuck on this (maybe because the sentence is quite long and for non-native speakers it's tough to parse - e.g. "plus or minus 10%" could feel confusing maybe?) so I thought maybe we become SUPER explicit.
(To be clear, I find the instructions very clear already, but it seems others don't)
Some context here: https://forum.exercism.org/t/exercise-meltdown-mitigation/6545/2

[meltdown-mitigation] Be super explicit

---

concepts/generators/about.md
exercises/concept/plane-tickets/.docs/introduction.md
exercises/practice/binary-search/.docs/instructions.md
exercises/practice/bob/.approaches/answer-list/content.md
exercises/practice/bob/.approaches/if-statements-nested/content.md
exercises/practice/bob/.approaches/if-statements/content.md
exercises/practice/etl/.docs/instructions.md
exercises/practice/gigasecond/.docs/introduction.md
exercises/practice/grains/grains_test.py
exercises/practice/isogram/.approaches/scrub-regex/content.md
exercises/practice/leap/.approaches/datetime-addition/content.md
exercises/practice/linked-list/.docs/instructions.md
exercises/practice/luhn/.approaches/recursion/content.md
exercises/practice/pangram/.approaches/all/content.md
exercises/practice/pangram/.approaches/bitfield/content.md
exercises/practice/pangram/.docs/introduction.md
exercises/practice/pig-latin/.approaches/sets-and-slices/content.md
exercises/practice/rational-numbers/.docs/instructions.md
exercises/practice/rna-transcription/.approaches/translate-maketrans/content.md
exercises/practice/rna-transcription/.docs/instructions.md
exercises/practice/rna-transcription/.docs/introduction.md
exercises/practice/secret-handshake/.docs/instructions.md
exercises/practice/sieve/.docs/instructions.md
exercises/practice/simple-linked-list/.docs/instructions.md
exercises/practice/wordy/.approaches/dunder-getattribute/content.md
exercises/practice/wordy/.approaches/introduction.md

In line with Exercism's spec, we're ensuring that all admonition fences are demarcated with four tildes (`~~~~`) across all repositories. We will be following up with an org-wide script that can be used to keep this consistent. [Problem Specifications](https://github.com/exercism/problem-specifications) has already been updated.
We'll automatically merge this a week from now, but feel free to merge beforehand!
- Spec: https://exercism.org/docs/building/markdown/markdown#h-special-blocks-sometimes-called-admonitions
- Meta issue: https://github.com/exercism/exercism/issues/6705

Convert backtick (`) admonition fences to tildes (~)

---

exercises/concept/currency-exchange/.docs/instructions.md
exercises/concept/currency-exchange/.docs/introduction.md
exercises/concept/currency-exchange/.meta/exemplar.py
exercises/concept/currency-exchange/exchange.py

The word _amount_ is generally used for things that come in piles (like money) or
that can otherwise be measured but not counted (like water).
The word _number_ is typically used if you can count the things.
Technically money can be counted, but it's an exception (see 'piles' above).
Here we count bills and digits, so 'number' is the more common choice of word.

Fix grammar in currency-exchange exercise

---

concepts/string-methods/about.md
exercises/concept/little-sisters-essay/.docs/introduction.md

The Little Sister's Essay concept and associated concept gives some example sentences using the phrase 'the man in the hat'. In English this is an idiomatic phrase that means the man who is wearing the hat, but could technically also translate to the man who is inside the hat.
The Thai phrase ผู้ชายในหมวก translates the second meaning. I've replaced this with a phrase that better matches the intended meaning.
This change was discussed in the following forum thread: https://forum.exercism.org/t/the-man-inside-the-hat-little-sisters-essay/7828/2

Change Thai in string methods concept and exercise

---

exercises/concept/currency-exchange/.docs/hints.md
exercises/concept/currency-exchange/.docs/instructions.md
exercises/concept/currency-exchange/.docs/introduction.md
exercises/concept/currency-exchange/.meta/exemplar.py
exercises/concept/currency-exchange/exchange.py

The exchange booth in this exercise only deals in
cash of specific increments. That is to say, you can bring any combination of bills and coins to exchange, but you get a collection of bills of a single denomination in the target currency in return.
The explanation was quite clear on this, but the parameter names and docstrings in the methods dealing with this part of the task used the term 'budget', which could lead readers to assume that the bills had to do with the original currency.
This reworks the methods related to bills to be more generic, not referring to the exchange process at all, hopefully avoiding this misinterpretation.
See forum thread here for details of the discussion leading to this change:
https://forum.exercism.org/t/currency-exchange-exercise-suggested-naming-tweaks/7 …

Clarify bills in currency exchange exercise

---

concepts/function-arguments/about.md
concepts/numbers/about.md
concepts/recursion/about.md
concepts/recursion/introduction.md
exercises/concept/electric-bill/.docs/introduction.md
exercises/concept/electric-bill/.meta/exemplar.py
exercises/concept/electric-bill/electric_bill.py
exercises/concept/ellens-alien-game/.meta/exemplar.py
exercises/concept/ellens-alien-game/classes.py
exercises/concept/locomotive-engineer/.docs/hints.md
exercises/concept/locomotive-engineer/.docs/instructions.md
exercises/practice/grains/.approaches/bit-shifting/content.md
exercises/practice/grains/.approaches/introduction.md
exercises/practice/robot-name/.approaches/mass-name-generation/content.md

This is a follow-up to https://github.com/exercism/python/pull/3517
I've been meaning to do this for a while, and finally found the time to sit down and meticulously check all the occurrences of "[Aa]mount of" in the repository.
I've fixed the following occurrences:
- number of values
- number of digits
- number of function calls
- number of hours
- number of health points
- number of (intermediate) delivery points
- number of keyword arguments
- number of grains
- number of names
I have also verified that the following are correct:
- amount of reputation
- amount of work
- amount of functionality
- amount of memory
- amount of money
- amount of domestic currency
- amount of tree climbing
- amount of energy
There are also two things that we need to figure out:
**Currency Exchange concept …

Change 'amount' to 'number' for countables

---

exercises/concept/currency-exchange/.docs/hints.md

This is a tiny thing, and it probably wouldn't confuse people who are
actually doing the exercise.
I came across it because I was doing a full audit of instances where
we say 'amount of ...' since there were several instances where it
should have been 'number of ...'.
At first I thought this was supposed to be 'number of changes', but
then in the context of the exercise it turns out that it was a
different problem entirely :)

Fix grammar in currency-exchange hint

---

exercises/concept/plane-tickets/generators_test.py

Bad typo.  [forum post](https://forum.exercism.org/t/wrong-error-message-in-plane-tickets-python-track-exercise/7984)

[Plane Tickets]: Update `generators_test.py` to Correct L47 Test Error Message

---

exercises/concept/mecha-munch-management/dict_methods_test.py

Also discovered errors in the test data and methodology for two tests:
`test_send_to_store()` and `test_sort_entries()`
Because `dicts` are hashmaps, two will compare equal if they have the same keys and values **_even if those appear in a different order_**.  While insertion order is guaranteed for dictionaries in Python, that ordering is not used for equality tests. 😱 so these tests were always passing....
To fix this …

[Mecha Munch Management]: Modified Test Error Messages & Fixed Ordering Tests

---

exercises/concept/locomotive-engineer/locomotive_engineer_test.py

[Locomotive Engineer]: Modified Test Error Messages

---

concepts/bools/about.md
concepts/bools/introduction.md
exercises/concept/ghost-gobble-arcade-game/.docs/hints.md
exercises/concept/ghost-gobble-arcade-game/.docs/introduction.md
exercises/concept/ghost-gobble-arcade-game/.meta/config.json
exercises/concept/ghost-gobble-arcade-game/arcade_game_test.py

[Ghost Gobble Arcade Game]: Modified Test Error Messages & Touched Up Docs

---

concepts/tuples/introduction.md
exercises/concept/ghost-gobble-arcade-game/.meta/config.json
exercises/concept/tisbury-treasure-hunt/.docs/hints.md
exercises/concept/tisbury-treasure-hunt/.docs/introduction.md
exercises/concept/tisbury-treasure-hunt/.meta/config.json
exercises/concept/tisbury-treasure-hunt/tuples_test.py

[Tisbury Treasure Hunt]: Modified Test Error Messages & Touched Up Docs

---

concepts/loops/about.md
exercises/concept/making-the-grade/.docs/hints.md
exercises/concept/making-the-grade/.docs/instructions.md
exercises/concept/making-the-grade/.docs/introduction.md
exercises/concept/making-the-grade/loops_test.py

[Making the Grade]: Modified Test Error Messages & Touched Up Docs

---

exercises/concept/little-sisters-vocab/.docs/hints.md
exercises/concept/little-sisters-vocab/.docs/instructions.md
exercises/concept/little-sisters-vocab/.docs/introduction.md
exercises/concept/little-sisters-vocab/.meta/config.json
exercises/concept/little-sisters-vocab/strings_test.py

[Little Sisters Vocab]: Modified Test Error Messages & Touched Up Docs

---

concepts/string-methods/.meta/config.json
concepts/string-methods/about.md
concepts/string-methods/links.json
exercises/concept/little-sisters-essay/.docs/hints.md
exercises/concept/little-sisters-essay/.meta/config.json
exercises/concept/little-sisters-essay/string_methods_test.py

[Little Sister's Essay]: Modified Test Error Messages & Touched Up Docs

---

exercises/concept/inventory-management/.docs/hints.md
exercises/concept/inventory-management/dicts.py
exercises/concept/inventory-management/dicts_test.py

[Inventory Management]: Modified Test Error Messages & Touched Up Docs

---

exercises/concept/ellens-alien-game/classes_test.py

[Ellens Alien Game]: Updated Test Error Messages.

---

exercises/concept/currency-exchange/.meta/config.json
exercises/concept/currency-exchange/exchange_test.py

[Currency Exchange]: Updated Test Error Messages.

---

exercises/concept/chaitanas-colossal-coaster/.docs/hints.md
exercises/concept/chaitanas-colossal-coaster/.meta/config.json
exercises/concept/chaitanas-colossal-coaster/list_methods_test.py

[Chaitanas Colossal Coaster]: Modified Test Error Messages & Touched Up Docs

---

concepts/lists/about.md
exercises/concept/card-games/.docs/hints.md
exercises/concept/card-games/.docs/introduction.md
exercises/concept/card-games/lists_test.py

[Card Games]: Modified Test Error Messages & Touched Up Docs

---

concepts/basics/about.md
concepts/basics/links.json
exercises/concept/guidos-gorgeous-lasagna/.docs/hints.md
exercises/concept/guidos-gorgeous-lasagna/.docs/introduction.md
exercises/concept/guidos-gorgeous-lasagna/lasagna_test.py

[Guido's Gorgeous Lasagna]: Modified Test Error Messages & Touched Up Docs

---

concepts/comparisons/about.md
concepts/comparisons/links.json
exercises/concept/black-jack/.docs/introduction.md
exercises/concept/black-jack/black_jack_test.py

[Black Jack]: Modified Test Error Messages & Touched Up Docs

---

.github/workflows/ci-workflow.yml
.github/workflows/issue-commenter.yml
.github/workflows/pr-commenter.yml
.github/workflows/stale.yml
.github/workflows/test-runner.yml

This PR updates GitHub Actions runners to a specific version.
This ensures that the workflow will always run on the same runner, which makes your build _stable_.
The PR updates the *-latest version with the current version, as specified in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-test-runners-to-version for more information.

CI: pin GitHub Actions runners

---

.github/workflows/ci-workflow.yml
.github/workflows/issue-commenter.yml
.github/workflows/pr-commenter.yml
.github/workflows/stale.yml
.github/workflows/test-runner.yml

This PR updates GitHub Actions workflows to a specific version.
This ensures that the workflow will always run the same code, which makes your build _stable_.
It will also prevent a potential security issue where a tag could be replaced by a malicious commit without consumers being aware of it.
The PR updates each non-SHA based workflow reference with the SHA of the referenced version/tag, so the current behavior should not change.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-actions-to-shas for more information.

CI: pin GitHub Actions workflows

---

concepts/complex-numbers/.meta/config.json
concepts/complex-numbers/about.md
concepts/complex-numbers/introduction.md
concepts/complex-numbers/links.json

New concept documents, for discussion.
You may want to cut the last bit of `about.md`. It got a bit preachy.

complex-numbers concept docs

---

concepts/fractions/.meta/config.json
concepts/fractions/about.md
concepts/fractions/introduction.md
concepts/fractions/links.json
config.json

Documentation for the fractions module. Probably low-priority (marked TBD-F), but I'm working on the numbers sub-tree for now (smaller, easier concepts than e.g. functions).
Cheat: `introduction.md` is currently the same as `about.md`, which may be something to change at some point.

fractions concept

---

concepts/bitwise-operators/.meta/config.json
concepts/bitwise-operators/about.md
concepts/bitwise-operators/introduction.md
concepts/bitwise-operators/links.json

Another concept, to review non-urgently at your leisure.
There was some minor confusion about calling it `bitwise-operators` (better) or `bitwise-operations` (occurs in a few places in the plans). That's why the concept uses one, the branch uses the other name.

The `bitwise-operators` concept

---

exercises/practice/leap/.articles/performance/content.md

Switched from `src="https://github.com/exercism/images/blob/main/images/tracks/python/leap/leap_timeit_bar_plot-light.svg"` to `https://assets.exercism.org/images/tracks/python/leap/leap_timeit_bar_plot-light.svg`  🤦🏽‍♀️

Update content.md with the correct link this time!

---

exercises/practice/leap/.articles/performance/content.md

The site requires this to be in markdown syntax for proper processing.

[Leap Performance Article]: Swapped HTML Syntax for Markdown Syntax for svg Image.

---

exercises/practice/leap/.articles/performance/content.md

Old Table:
New Table:
|                 |    1900 |    2000 |    2019 |    2020 |
|:----------------|--------:|--------:|--------:|--------:|
| if-statements   | 1.7e-07 | 1.6e-07 | 9.0e-08 | 1.3e-07 |
| ternary         | 1.2e-07 | 1.1e-07 | 1.1e-07 | 1.0e-07 |
| datetime-add    | 7.2e-07 | 7.3e-07 | 7.5e-07 | 7.1e-07 |
| calendar-isleap | 2.2e-07 | 2.1e-07 | 1.4e-07 | 1.7e-07 |

[Leap]: Updated Table in Performance Article with Newer Timings to Match Graph.

---

exercises/practice/raindrops/.approaches/dict-and-join/content.md
exercises/practice/raindrops/.approaches/dict-and-join/snippet.txt
exercises/practice/raindrops/.approaches/introduction.md
exercises/practice/raindrops/.articles/performance/code/Benchmark.py
exercises/practice/raindrops/.articles/performance/content.md

Probably this was done on purpose but as a way to discuss this I wanted to propose a little simplification to the approach.
I think this is more sound and readable to just use the item from the dict.
Let me know what you think.
Thanks in advance.

dict-and-join simplify for raindrops approaches

---

exercises/practice/raindrops/.articles/performance/content.md

Updated `Benchmark.py` link to point at GitHub Repo rather than the website (_which returns a 404_)

[Raindrops]: Update content.md Benchmark URL

---

concepts/tuples/about.md
exercises/concept/tisbury-treasure-hunt/.docs/introduction.md

Fixed small typo in line 65 replaced : with =

Fixed small typo in introduction.md

---

concepts/tuples/about.md

Multiple links were pointed at the deprecated V3 repo instead of the Python docs.  Annoying.

[Tuples]: Fix Bad Links in About.md

---

exercises/practice/meetup/.docs/instructions.append.md

Add a clarification to the docs that in Python there is a week descriptor called `fifth` that should be the fifth weekday of the month, if one exists.

Clarify that in Python there is a week descriptor called 'fifth'

---

exercises/concept/mecha-munch-management/.docs/introduction.md

Corrected Real Python link and line 21 reference to `palette` instead of `palette_I`.

[Mecha Munch Management]: Fix typos in introduction.md

---

concepts/sets/about.md
exercises/concept/cater-waiter/.docs/introduction.md

Per (closed) [PR 3639](https://github.com/exercism/python/pull/3639) & (closed) [PR 3638](https://github.com/exercism/python/pull/3638/files), changed `introduction.md` for the `Cater Waiter` exercise and `about.md` for the `Sets` concept.

[Cater-Waiter/Sets]: Fixed Superset/subset Operator & Operator Descriptions

---

exercises/practice/circular-buffer/.approaches/built-in-types/content.md
exercises/practice/circular-buffer/.approaches/built-in-types/snippet.txt
exercises/practice/circular-buffer/.approaches/config.json
exercises/practice/circular-buffer/.approaches/introduction.md
exercises/practice/circular-buffer/.approaches/standard-library/content.md
exercises/practice/circular-buffer/.approaches/standard-library/snippet.txt

For this one I experimented with brevity to see how it looks.
What do you think - too short? Or about what this exercise deserves (in Python)?

[Circular Buffer] draft approaches

---

exercises/shared/.docs/representations.md

First draft of `representations.md` doc, describing the normalizations that the Python representer performs for student solutions.
To be reviewed/merged after the [representer changes](https://github.com/exercism/python-representer/pull/45) are merged.

[Representer Documentation]: First draft of representations.md doc

---

exercises/concept/black-jack/.docs/instructions.md

Previously discussed in the [forum](https://forum.exercism.org/t/suggested-changes-to-python-learning-exercise-black-jack-instructions/10436).
The instructions on the exercise [black_jack](https://exercism.org/tracks/python/exercises/black-jack) might be improved.
It could be better to refer to the value of the upcoming ace instead of the value of those in hand since this doesn't apply if we have more than one ace in hand.
Current instructions:
`Hint: if we already have an ace in hand then its value would be 11.`
Proposed instructions:
`Hint: if we already have an ace in hand, then the value for the upcoming ace would be 1.`
Sources: "[...] and aces count as either 1 or 11 according to the player's choice." from [Wikipedia](https://en.wikipedia.org/wiki/Blackjack?lang=en#Rules_of_play_at_c …

[Black Jack]: ✏️ Updates to instructions.

---

exercises/practice/resistor-color-expert/resistor_color_expert_test.py

Per [issue on forum](https://forum.exercism.org/t/python-resistor-color-expert/10587).

[Resistor Color Expert]: Change `test_blue_grey_white_red_and_brown` to `test_blue_grey_white_brown_and_brown`

---

concepts/string-methods/about.md
exercises/concept/little-sisters-essay/.docs/introduction.md

Just a fix for a small typo in examples.
---
Before: _**m**ужчина_ (`m` was latin/roman letter).
After: _**м**ужчина_ (`м` is now cyrillic, as expected).

[Essays] Fix a typo in the exercise introduction

---

exercises/concept/card-games/.meta/exemplar.py
exercises/concept/card-games/lists.py

Improve docstring summary of `approx_average_is_average` function to be more clear. This is a fix for https://github.com/exercism/python/issues/3674.
1. Initially I've started an implementation of `approx_average_is_average` function based on docstring.
2. Wrote the function, run tests and found the implementation doesn't work.
3. Then read instructions and found inconsistencies between docstring and instructions (see the screenshot below).

[Card Games] Update 'approx_average_is_average' docstring summary

---

exercises/concept/inventory-management/.meta/exemplar.py
exercises/concept/inventory-management/dicts.py

Docstring summary of `list_inventory` function is inconsistent. This is a fix for issue #3683.
1. Initially I've started an implementation of `list_inventory` function based on docstring.
2. Wrote the function, run tests and found the implementation doesn't work.
3. Then read instructions and found inconsistencies between docstring and instructions.
| Currently | Suggested |
| --- | --- |
| `"""Create a list containing all (item_name, item_count) pairs in inventory.` | `"""Create a list containing only available (item_name, item_count > 0) pairs in inventory.`

[Inventory Management] Update 'list_inventory' docstring summary

---

exercises/concept/mecha-munch-management/.docs/hints.md

Fixes the following typos in hints for task no. 5 (`Send User Shopping Cart to Store for Fulfillment`):
1. Keyword argument should be `reverse`, not `reversed` (reference: [official documentation](https://docs.python.org/3/library/functions.html#sorted));
2. Boolean value should be `True`, not `true`.
**Related issue**: #3685.
| Currently | Suggested |
| --- | --- |
| `reversed=true` | `reverse=True` |
----

[Mecha Munch Management]: Fix hint for task #5 (send_to_store)

---

exercises/concept/ghost-gobble-arcade-game/.docs/instructions.md
exercises/concept/ghost-gobble-arcade-game/.meta/exemplar.py
exercises/concept/ghost-gobble-arcade-game/arcade_game.py

Small semantic fix within the first task of the exercise.
---
The requested functionality isn't to to return if you can eat **the** ghost but given the input if you can eat **a** ghost

[Ghost Gobble arcade game]fix semantics.

---

exercises/practice/pov/.docs/instructions.append.md

Per [this discussion](https://forum.exercism.org/t/wrong-error-message-for-pov-to-path-test-case-when-source-not-found/11601/4) on the forum.  Given the difficulty of the exercise, the examples were removed and a reminder to check the expected results in the tests was added.

[POV] Update instructions.append.md & Remove Error Message Examples

---

docs/TESTS.md

Updates URL for pytest tutorial - and also link text (since the tutorial is on the pylint documentation rather than pycqa). 
(Just noting that when I ran Prettier, it also caught a couple unrelated whitespace changes.)
Recap in forum [discussion thread](https://forum.exercism.org/t/testing-on-the-python-track-broken-link/12227), but the existing link 404'd

(Fix): Update pylint (v. 2.17.7) tutorial link

---

exercises/concept/inventory-management/.docs/introduction.md

an extra space made the markdown fail displaying _keys_ in italics:

remove extra space

---

exercises/practice/collatz-conjecture/.approaches/introduction.md

The General guidance text was saying: "The key to this exercise is to check if the number and then do the correct operation." I have changed it to say that we check if the number is even.

[Collatz Conjecture] Approaches - missing words fix

---

exercises/concept/mecha-munch-management/.docs/instructions.md
exercises/concept/mecha-munch-management/dict_methods_test.py

Per discussion on the [forum](https://forum.exercism.org/t/testing-data-in-mecha-munch-management-dict-methods-py-task3/12638.), removed the duplicate "Eggs" `dict` key from **Task 3** example code in `instructions.md`, and from the input data in **Task 3** tests.

[Mecha Munch Management]: Corrected Duplicate "Eggs" `dict` Key in Instructions & Tests 

---

bin/generate_tests.py
exercises/practice/transpose/.meta/template.j2
exercises/practice/transpose/transpose.py
exercises/practice/transpose/transpose_test.py

As a result of the discussion [here in the forum](https://forum.exercism.org/t/in-transpose-excercise-there-is-a-mistake-in-tests/12307/9) and the previously logged issue [here in GitHub](https://github.com/exercism/python/issues/3136), decided to alter the `JinJa2` template for this exercise, so that the test case input was "pre joined" prior to verifying it in the test case.  
This is to avoid any ambiguity around whether the function input is intended to be a `list` or a `str` (_the intent from [problem specs](https://github.com/exercism/problem-specifications/blob/main/exercises/transpose/canonical-data.json#L4-L6) is that the inputs are `str`s_).
[x] Changed `generate_tests.py` to add the `join_test_inputs()` function & make it available in the template environment.
[x] Changed the …

[Transpose & generate_tests.py]: Added `join` env Function & Changed Template

---

concepts/conditionals/about.md
concepts/conditionals/introduction.md
exercises/concept/meltdown-mitigation/.docs/hints.md
exercises/concept/meltdown-mitigation/.docs/introduction.md
exercises/concept/meltdown-mitigation/.meta/exemplar.py

Per discussion on the [forum](https://forum.exercism.org/t/pylint-returning-r1705-no-else-return-in-meltdown-mitigation-spoiler/12463), and the linked [SO Post](https://stackoverflow.com/questions/22782785/when-to-use-if-vs-elif-in-python/22783232#22783232), adjusted the `introduction.md` and `about.md` files as well as the `hints.md` and  `exemplar.py` file connected to the `Meltdown Mitigation` exercise.

[Meltdown Mitigation & Conditionals Concept]: Adjusted `if-elif-else` Examples & Hints.

---

concepts/list-methods/about.md
exercises/concept/chaitanas-colossal-coaster/.docs/introduction.md

Per [forum post](http://forum.exercism.org/t/chaitana-s-colossal-coaster-exercise-instructions-fact-checking/13178) discussion.
Python changed from Tmsort to Powersort in Python 3.11.  Added links to new Algo & core team change discussion.

[Chaitanas-Colossal-Coaster]: Corrected Reference to Python Internal Sort() Method 

---

concepts/list-methods/about.md
exercises/concept/chaitanas-colossal-coaster/.docs/introduction.md

Per [forum discussion](http://forum.exercism.org/t/chaitana-s-colossal-coaster-exercise-instructions-fact-checking/13178/3)
The Python docs offer [additional tips and techniques for sorting](https://docs.python.org/3/howto/sorting.html) _lists effectively._ `--[changed to]-->` 
**The Python docs offer [additional tips and techniques for sorting](https://docs.python.org/3/howto/sorting.html).**

[Chaitanas Colossal Coaster]: Removed "effectively" from HOWTO sentence.

---

concepts/sets/about.md
concepts/sets/introduction.md
exercises/concept/cater-waiter/.docs/instructions.md
exercises/concept/cater-waiter/.docs/introduction.md
exercises/concept/cater-waiter/sets.py

Per [forum discussion](http://forum.exercism.org/t/cater-waiter-exercise-variable-definition-missing/13293):
1.  Corrected `just_berries` variable typo in `cater-waiter/introduction.md`, `sets/introduction.md`, and, `sets/about.md`
2.  Changed `emdash`  representation from a double Hyphen to the `U+2014`/`ALT + 0151` character in `cater-waiter/introduction.md`, `sets/introduction.md`, and, `sets/about.md`.
3.  Changed the function signature in `sets.py` to be a `set` and not a `list` of ingredients.

[Cater-Waiter & Sets Concept]: Typos and `emdash` changes.

---

exercises/concept/cater-waiter/.docs/introduction.md

Per [forum post follow-up](http://forum.exercism.org/t/cater-waiter-exercise-variable-definition-missing/13293/4).

[Cater-Waiter]: Added Missing Markdown Otalics Underscore Back Into File

---

exercises/practice/wordy/.approaches/config.json
exercises/practice/wordy/.approaches/dunder-getattribute/content.md
exercises/practice/wordy/.approaches/functools-reduce/content.md
exercises/practice/wordy/.approaches/functools-reduce/snippet.txt
exercises/practice/wordy/.approaches/import-callables-from-operator/content.md
exercises/practice/wordy/.approaches/import-callables-from-operator/snippet.txt
exercises/practice/wordy/.approaches/introduction.md
exercises/practice/wordy/.approaches/lambdas-in-a-dictionary/content.md
exercises/practice/wordy/.approaches/lambdas-in-a-dictionary/snippet.txt
exercises/practice/wordy/.approaches/recursion/content.md
exercises/practice/wordy/.approaches/recursion/snippet.txt
exercises/practice/wordy/.approaches/regex-with-operator-module/content.md
exercises/practice/wordy/.approaches/regex-with-operator-module/snippet.txt
exercises/practice/wordy/.approaches/string-list-and-dict-methods/content.md
exercises/practice/wordy/.approaches/string-list-and-dict-methods/snippet.txt
exercises/practice/wordy/.docs/instructions.append.md

Added the following new approaches for `Wordy`:
1.  String, List, and Dictionary Methods
2.  Import Callables from the Operator Module
3. Regex and the Operator Module
4. Lambdas in a Dictionary to Return Functions
5. Recursion for iteration
6. Functools.reduce for Calculation
- Edited and added to the introduction for approaches to include the above items.
- Amended the `instruction.append` to include an example and reference to `try-except`.

[Wordy & Wordy Approaches]: Added 6 Additional Approaches & Modified the Instruction Append for Wordy.

---

exercises/practice/wordy/.approaches/introduction.md
exercises/practice/wordy/.docs/hints.md

Hopefully, this is the last round.

[Wordy]: Moar Typos & Missing Links. 

---

exercises/concept/cater-waiter/.docs/introduction.md

Fixed minor typo hasable -> hashable

Fixed typo.md

---

exercises/concept/chaitanas-colossal-coaster/list_methods_test.py

In Chaitana's Colossal Coaster, the test for taskno=6 only checked that the correct name was returned, it did not verify that the queue was updated to remove the last person from the queue.  This change adds a second test to taskno=6 to validate the queue.

[Chiatana's Colossal Coaster]: Update Tests to Verify Queue has been Updated

---

concepts/bitwise-operators/about.md
exercises/practice/bob/.approaches/introduction.md
exercises/practice/nth-prime/.approaches/generator-fun/content.md
exercises/practice/roman-numerals/.approaches/introduction.md

Yes, I did combine exercises (_which is naughty_).  But since these were small, I thought it best to do an all-in-one this time.
Changed files:

[Approaches Typo Fixes]:  Fixing Spelling in Approaches Docs

---

concepts/unpacking-and-multiple-assignment/about.md
exercises/concept/locomotive-engineer/.docs/introduction.md

[Forum Discussion](https://forum.exercism.org/t/potential-for-expansion-of-packing-to-list-syntax-explanation/13824/4).
Didn't add a whole lot here, but I hope it helps without confusing things.

[Unpacking & Multiple Assignment/Locomotive Engineer]: Added Some Notes on Using `*` On the Left-Hand Side

---

exercises/practice/roman-numerals/.approaches/introduction.md

https://exercism.org/tracks/python/exercises/roman-numerals/approaches/loop-over-roman **-->** https://exercism.org/tracks/python/exercises/roman-numerals/approaches/loop-over-romans
In `introduction.md`

[Roman Numeral Approaches]: Fix Broken Link in Approaches Introduction

---

exercises/practice/simple-linked-list/.docs/hints.md
exercises/practice/simple-linked-list/.docs/instructions.append.md

Removed three extraneous periods that were included mid-sentence, once within a parenthetical.

[Simple Linked List]: Remove Extraneous Periods from Links in `hints.md` & `instructions.append.md`

---

exercises/concept/mecha-munch-management/.meta/config.json
exercises/concept/mecha-munch-management/dict_methods.py
exercises/concept/mecha-munch-management/dict_methods_test.py
exercises/concept/mecha-munch-management/dict_methods_test_data.py

Modified **`dict_methods_test.py`** and added **`dict_methods_test_data.py`** for test data.

[Mecha Munch Management]: Reformatted Test File & Pulled Data out into Its Own File

---

exercises/practice/bank-account/.docs/instructions.append.md

Per [this discussion on the forum](https://forum.exercism.org/t/bank-account-instructions-mention-race-conditions-tests-do-not-check-for-race-condition/15722/5), added an instruction append while we sort out general instruction wording and whether or not we deprecate this exercise.

[Bank Account]: Added Explicit Instruction Append for not Doing Concurrency Tests.

---

exercises/practice/sieve/.approaches/comprehensions/content.md

Added language about the disallowed `%` operator to the Comprehensions approach.
See [this forum discussion ](https://forum.exercism.org/t/sieve-instructions-disagree-with-dig-deeper/15470) for details.  I was unable to rewrite this without the modulus, but felt it was important to include as a counter example.  Using `%` makes the code _look cleaner_, but doesn't actually confer any advantage over the first example in the file.

[Sieve]: Update content.md for Comprehension Approach

---

exercises/practice/wordy/.approaches/introduction.md
exercises/practice/wordy/.meta/tests.toml
exercises/practice/wordy/wordy_test.py

Also corrected formatting in approaches introduction.
See [forum discussion](https://forum.exercism.org/t/wordy-tests-require-non-meaningful-error-messages/15473/6) for additional details.

[Wordy]: Removed "President" Test Case & Regenerated Test file  

---

exercises/practice/bank-account/.docs/instructions.append.md

Misspelling of Exercism as well as backticks broke formatting on site.

[Bank Account]:  Fix instructions.append.md Admonition

---

exercises/practice/resistor-color-expert/.docs/instructions.md
exercises/practice/resistor-color-expert/.docs/introduction.md

Forum discussion [here](https://forum.exercism.org/t/minor-formatting-issues-for-resistor-color-expert/15775).
-  links to Resistor Color Duo and Resistor color Trio.
- Lower-cased band names in instructions
- Clarified later examples to be `lists` for the function inputs,

[Resistor Color Expert]: Fixed up Instructions & Introduction

---

exercises/concept/mecha-munch-management/.docs/instructions.md

`'Apple': 1` was missing from results dict on Task 3 examples.

[Mecha Munch Management]: Fix Typo in instructions.md

---

exercises/practice/grains/.meta/config.json
exercises/practice/leap/.meta/config.json
exercises/practice/rna-transcription/.meta/config.json
exercises/practice/say/.meta/config.json

Synced the following 4 exercises:

[March Metadata Sync]: Metadata for practice exercises 

---

exercises/practice/flatten-array/.meta/tests.toml
exercises/practice/flatten-array/flatten_array_test.py

Re-synced tests from Problem Specifications.

[Flatten Array]: Updated Tests & Regenerated Test Cases

---

exercises/practice/crypto-square/.meta/tests.toml
exercises/practice/crypto-square/crypto_square_test.py

No changes to example.py needed.

[June Problem Specs Sync]: Synced tests.toml & Regenerated Test File for `crypto-square`

---

exercises/practice/swift-scheduling/.docs/instructions.md
exercises/practice/swift-scheduling/.meta/config.json
exercises/practice/swift-scheduling/swift_scheduling_test.py

Synced metadata & instructions to problem-specifications and regenerated tests.

[Swift Scheduling]: Synced Exercise to Problem Specifications.

---

exercises/concept/mecha-munch-management/.docs/instructions.md
exercises/concept/mecha-munch-management/.docs/introduction.md
exercises/concept/mecha-munch-management/dict_methods.py

<br>
[Forum discussion 1](https://forum.exercism.org/t/about-task3-in-mecha-munch-management-the-1st-dict-methods-exercise-in-python/18191)
[Forum discussion 2](https://forum.exercism.org/t/inquiry-about-default-ordering-for-a-dictionary-in-python/18178)

[Mecha Munch Management] Fixed typos in Instructions, Introduction, & Stub File

---

concepts/unpacking-and-multiple-assignment/about.md
exercises/concept/locomotive-engineer/.docs/introduction.md

Per forum [discussion](https://forum.exercism.org/t/locomotive-engineer-grammatical-error/19287).

[Locomotive Engineer & Unpacking Concept]: Fixed Grammatical Error in paragraph Describing * Used with `zip()`

---

concepts/strings/about.md
exercises/concept/little-sisters-vocab/.docs/hints.md
exercises/concept/little-sisters-vocab/.docs/instructions.md
exercises/concept/little-sisters-vocab/.docs/introduction.md

Per [forum discussion](https://forum.exercism.org/t/loops-usage-on-little-sister-vocab-before-its-teached/19389/3).

[Little Sister's Vocab]: Fixed up Code Examples for `str.join()` & Added an Additional Hint.
