sieve/example.py
I think I've resolved the Python 3 compatibility issues from my previous pull request.
I think this is a cleaner solution and doesn't need the boolean array to flag non prime numbers.
=> Sieve: Cleaned Example

gigasecond/gigasecond_test.py
Changed date to a datetime to resolve #163
=> Gigasecond: Tests now consider time of day in addition to date

gigasecond/gigasecond_test.py
=> Gigasecond: Implemented new rollover tests for gigasecond from x-common

sum-of-multiples/sum_of_multiples_test.py
Adding test cases to Sum of Multiples as per exercism/exercism.io#2341.
=> Add test cases to Sum of Multiples

README.md
Closes https://github.com/exercism/xpython/issues/150
=> README: Some advice for contributors

config.json, hello-world/example.py, hello-world/hello_world.py, hello-world/hello_world_test.py
This adds the introduction hello-world example for python as well.
=> added a hello-world example

hello-world/example.py, hello-world/hello_world.py, hello-world/hello_world_test.py
I made it so that the exercise complies with Pep8.
I changed a double quote to a single quote in example.py to be consistent.
I changed the if statement in the example to be more pythonic.
=> hello-world: Made Pep8 compliant, made strings consistent

scrabble-score/scrabble_score_test.py
Not the only one, but replaces the word that wouldn't fit.
re: exercism/x-common#86
=> Longest word possible on the board.

docs/WORKFLOW.md
* Recommended that users install pytest and pytest-cache
* Gave examples of how to use pytest
* Documented how to run tests without pytest
=> WORKFLOW: Improved Documentation On Tests

docs/WORKFLOW.md
* Added more advanced testing commands
- The exercises on exercism are good for practicing pdb, and I thought it would be beneficial to give a plug on using debuggers.
- PEP8 is a common nitpick, and this would test for it before submission. I felt it should be encouraged, but optional.
=> WORKFLOW: Added sections regarding PDB and PEP8

word-count/example.py, word-count/word_count_test.py
I saw multiple solutions that passed the current tests but would fail this one
=> word-count: add test_tabs()

allergies/allergies_test.py, allergies/example.py
I changed ```test_allergic_to_everything()``` because I thought it was broken.
I also re-named a ```list``` property to the more Pythonic ```lst```, since Python has ```list()```
=> Allergies: sort expected and actual vals in a particular test, and rename list -> lst

meetup/meetup_test.py
=> meetup: ADD test for last Sunday of a month with only 4 weeks.

house/example.py, house/house_test.py
I also add a double \n at the end of the rhyme
=> house: more test

config.json, poker/example.py, poker/poker_test.py
I submitted a new exercise about ranking between different poker hand. I wrote a part of the example code with the help of this course: https://www.udacity.com/course/viewer#!/c-cs212/l-48688918
Is there anything to do to add it to the exercises list?
=> Poker : new exercises

rectangles/example.py, rectangles/rectangles_count_test.py
The exercise `rectangles` had plenty inconsistencies with PEP8 which I fixed.
```
tmo$ flake8 rectangles/ --ignore=E501
rectangles/example.py:1:1: F403 'from types import *' used; unable to detect undefined names
rectangles/example.py:4:1: E302 expected 2 blank lines, found 1
rectangles/example.py:5:3: E111 indentation is not a multiple of four
rectangles/example.py:9:3: E111 indentation is not a multiple of four
rectangles/example.py:9:3: E301 expected 1 blank line, found 0
rectangles/example.py:13:1: E302 expected 2 blank lines, found 1
rectangles/example.py:14:3: E111 indentation is not a multiple of four
rectangles/example.py:16:7: E111 indentation is not a multiple of four
rectangles/example.py:17:1: W293 blank line contains whitespace
rectangles/example.py:19:1: E302 expected 2 …
```
=> rectangles: PEP8 compliance updated

hello-world/hello_world_test.py
Fix test class name to reflect exercise name.
Update tests to reflect Hello World metadata in x-common.
=> hello-world: Fix Hello World test class name & update test

word-count/word_count_test.py
See https://github.com/exercism/xpython/issues/234
=> word-count: Update test mixed case

bracket-push/bracket_push_test.py, bracket-push/example.py, config.json
I implemented the **x-common/bracket-push** exercise. [README.md](https://github.com/exercism/x-common/blob/master/bracket-push.md)
=> bracket-push: Implemented new exercise

config.json, run-length-encoding/example.py, run-length-encoding/run_length_test.py
Example solution for new proposed exercise exercism/x-common#134.
Will be updated later based on possible feedback there.
=> run-length-encoding: Implemented new exercise

config.json, say/example.py, say/say_test.py
I implemented the **x-common/say** exercise. [README.md](https://github.com/exercism/x-common/blob/master/say.md)
=> say: Implement new exercise

sum-of-multiples/sum_of_multiples_test.py
=> add missing test to sum of multiples exercise

docs/ABOUT.md
Corrected typo for 'interactive' and reworded introductory sentences to include input from @kytrinyx about resources available for Python, from https://github.com/exercism/xpython/pull/275.
=> Wording changes in ABOUT.md

exercises/binary/binary_test.py
see https://github.com/exercism/x-common/issues/95
=> binary: Expand invalid input tests

config.json, exercises/acronym/acronym_test.py, exercises/acronym/example.py
Implementation of the acronym exercise closes #260
=> acronym: implement new exercise

exercises/largest-series-product/largest_series_product_test.py
In response to #317 this adds the missing test cases from the standard test data (x-common/json).
=> largest-series-product: Add additional test cases

exercises/sum-of-multiples/example.py, exercises/sum-of-multiples/sum_of_multiples_test.py
=> No default values for sum of multiples

README.md, docs/TOOLS.md
Still needs the new reference for git workflow introduction.
references #323
=> Remove old help site links

config.json, exercises/clock/clock_test.py, exercises/clock/example.py
My first pull request for exercism, check it twice.
=> clock: Added the exercise

circular-buffer/circular_buffer_test.py, circular-buffer/example.py, config.json
I implemented the **x-common/circular-buffer** exercise. [README.md](https://github.com/exercism/x-common/blob/master/circular-buffer.md)
=> circular-buffer: Implemented new exercise

config.json, perfect-numbers/example.py, perfect-numbers/perfect_numbers_test.py
I implemented the **x-common/perfect-numbers** ([md](https://github.com/exercism/x-common/blob/master/perfect-numbers.md), [yml](https://github.com/exercism/x-common/blob/master/perfect-numbers.yml)) exercise.
=> perfect-numbers: Implement new exercise

config.json, rail-fence-cipher/example.py, rail-fence-cipher/rail_fence_cipher_test.py
Example solution for new proposed exercise exercism/x-common#144.
Will be updated later based on possible feedback there.
=> rail-fence-cipher: Implement new exercise

exercises/bob/bob_test.py
As suggested by @matts-code
Resolves #312
=> bob: Adding non-question trailing whitespace test

exercises/pangram/pangram_test.py
Updates the pangram test suite to match the new json file in x-common.
Resolves #337
=> pangram: Update pangram test suite

exercises/clock/clock_test.py
These four tests are repeated immediately above
=> Clock: remove duplicated tests

exercises/beer-song/beer_song_test.py, exercises/circular-buffer/circular_buffer_test.py, exercises/grade-school/grade_school_test.py, exercises/kindergarten-garden/kindergarten_garden_test.py, exercises/largest-series-product/largest_series_product_test.py, exercises/leap/leap_test.py, exercises/nth-prime/nth_prime_test.py, exercises/nucleotide-count/nucleotide_count_test.py, exercises/ocr-numbers/ocr_test.py, exercises/palindrome-products/palindrome_products_test.py, exercises/perfect-numbers/perfect_numbers_test.py, exercises/phone-number/phone_number_test.py, exercises/point-mutations/point_mutations_test.py, exercises/rna-transcription/rna_transcription_test.py, exercises/robot-name/robot_name_test.py, exercises/roman-numerals/roman_numerals_test.py, exercises/scrabble-score/scrabble_score_test.py, exercises/secret-handshake/handshake_test.py, exercises/simple-cipher/simple_cipher_test.py, exercises/word-count/word_count_test.py
=> Standardizing exercise names #344

config.json
=> add topics to hello-world exercise in config.json

config.json
This addresses issue #353 
I was tempted to push the difficulty of this up to 2. Only because I seem to remember confronting this early on in my programming experience (with no CS background), and taking some time wrapping my head around the logic of it. The problem seems easy now, though I wonder if it only is because I know the answer, it may be good to have someone who has more recently attempted this to comment on it's difficulty.
I guess, as well, as more problems receive difficulty ratings, it will be easier to compare the levels of difficulty.
=> add topics to leap exercise in config.json

README.md
The Travis build fails if PRs don't pass the style checker. (See #341). This is just adding that requirement to the README section on style.
=> style: Update README for style requirements

README.md
...from exercism.io/ATTRIBUTION.md, noting the permission they gave us
a step in fixing https://github.com/exercism/exercism.io/issues/3112.
=> Add attribution for the track icon

config.json
this keeps it in line with the TOPICS list
=> change if-statements to if-else statements

config.json
=> add topics to word-count exercise in config.json

config.json
=> add topics to hamming exercise in config.json

config.json
=> add topics to rna-transcription exercise in config.json

config.json
=> add topics to pangram exercise in config.json

config.json, exercises/list-ops/example.py, exercises/list-ops/list_ops.py, exercises/list-ops/list_ops_test.py
*(2nd try)* I updated the abandoned pr #170, added some minor tests and created a stub file.
=> Continue list-ops exercise

config.json, exercises/diamond/diamond_test.py, exercises/diamond/example.py
Implements the **x-common/diamond** exercise. [description.md](https://github.com/exercism/x-common/blob/master/exercises/diamond/description.md)
=> diamond: Implement new exercise

exercises/rectangles/rectangles_count_test.py
* used self.assertEqual (for easier debugging and consistency)
* beautified closing brackets and removed superfluous comma
=> rectangles: improved unit-tests

exercises/linked-list/example.py, exercises/linked-list/linked_list.py, exercises/linked-list/linked_list_test.py
- Add tests for `__iter__()` and `__len__()`
- References #389 
- Commits have additional context
=> linked-list: Extra credit iter() and len() 

exercises/acronym/acronym_test.py
Adds one missing test case from the canonical test data and
stores the test data version.
=> acronym: Update test cases

README.md
=> README: Cleanup Working on the Exercises

exercises/sum-of-multiples/example.py, exercises/sum-of-multiples/sum_of_multiples_test.py
Updates the test cases according to the canonical test data
and stores the test data version.
=> sum-of-multiples: Update test cases and example

config.json
- moves the clock exercise later (down) in the exercise suite
=> Move the clock exercise later in fetch order

docs/INSTALLATION.md
=> Update Installation with supported Python versions

exercises/pangram/pangram_test.py
Removes the unicode test and adds one missing test from the canonical test data and stores the test data version.
=> pangram: Update test cases

exercises/prime-factors/prime_factors_test.py
Updates the test cases according to the canonical test data and stores the test data version.
=> prime-factors: Update test cases

exercises/nth-prime/example.py, exercises/nth-prime/nth_prime_test.py
Adds missing test cases from the canonical test data,
adapts the example implementation and stores the test data version.
=> nth-prim: Update test cases and example

config.json, exercises/protein-translation/example.py, exercises/protein-translation/protein_translation.py, exercises/protein-translation/protein_translation_test.py
Hi! This is my first time ever making a pull request. Thought I would start learning to contribute to projects, and porting some code looks like a fun place to start. I'm not very experienced with github.
I'm trying to follow the instructions for contributing code here:
https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#porting-an-exercise-to-another-language-track
Please let me know if I'm doing it right, and if not, what I need to change. Thanks :)
=> dibs: implement protein-translation

config.json, exercises/grade-school/grade_school_test.py, exercises/scale-generator/example.py, exercises/scale-generator/scale_generator.py, exercises/scale-generator/scale_generator_test.py
Thanks for all your excellent help and advice on the protein-translation exercise. I'll bear it in mind when implementing this one.
=> dibs: I will implement exercise scale-generator

docs/ABOUT.md
Updates ABOUT.md formatting as described in exercism/meta#85
=> Python: Updates ABOUT.md formatting for Nextercism

config.json, exercises/collatz-conjecture/README.md, exercises/collatz-conjecture/collatz_conjecture.py, exercises/collatz-conjecture/collatz_conjecture_test.py, exercises/collatz-conjecture/example.py
First time porting a new exercise into Python, so let me know if there's anything I screwed up or any best practices I didn't follow. (Very new to Git so I wasn't sure how to make the commit history less messy.)
I'm not sure if I added the exercise to `config.json` correctly, but I ran configlet against it and didn't get any messages back, which I assume is a good thing?
Thanks!
=> collatz-conjecture: add exercise

exercises/isogram/isogram_test.py
when testing the exercise i found i could cheat by bypassing all nonletter challeges
=> isogram: test with duplicate letter and nonletter character

exercises/scale-generator/example.py, exercises/scale-generator/scale_generator_test.py
=> scale-generator: a new test added

exercises/isogram/isogram.py
I added parameter string to template question. viz #509
=> isogram: added parameter to template question

exercises/change/change_test.py
There were two identical tests.  I modified this one to be more reflective of the name.
=> change: Fixed duplicate test in change_test.py

exercises/saddle-points/README.md
=> saddle-points: readme grammar

.gitignore, exercises/accumulate/accumulate.py, exercises/allergies/allergies.py, exercises/alphametics/alphametics.py, exercises/anagram/anagram.py, exercises/atbash-cipher/atbash_cipher.py, exercises/beer-song/beer_song.py, exercises/binary-search/binary_search.py, exercises/binary/binary.py, exercises/bob/bob.py, exercises/book-store/book_store.py, exercises/bracket-push/bracket_push.py
=> adding parameters to template  A - B

exercises/simple-cipher/README.md
The test looks for a `ValueError`.
=> simple-cipher: 'ArgumentError' -> 'ValueError'

exercises/alphametics/alphametics_test.py
A test method name must begin or end in 'test'.
Closes #530
=> alphametics: run all tests

exercises/atbash-cipher/atbash_cipher.py
=> atbash-cipher: add parameters to exercise placeholder

exercises/wordy/wordy.py
=> wordy: Add parameters to exercise placeholder

exercises/meetup/meetup.py
#598 Proposing pull request for this one
Fixes #598
=> meetup: added default params

exercises/all-your-base/all_your_base.py
Closes #538 
By 'example' I mean placeholder
=> all_your_base: add placeholder file with parameters

exercises/leap/leap.py
=> leap: Add parameter to exercise placeholder (#568)

exercises/hamming/hamming.py
Signed-off-by: Ian Dexter D Marquez <iandexter@users.noreply.github.com>
Fixes #562
=> hamming: Add parameters to exercise placeholder (#562)

exercises/gigasecond/gigasecond.py
Added the parameter birth_date to the exercise placeholder
Fixes #558
=> gigasecond: add parameters to exercise placeholder

exercises/rna-transcription/rna_transcription.py
Added parameter for issue #620
Resolves #620
=> rna-transcription: added parameter for issue #620

exercises/saddle-points/saddle_points.py
=> saddle-points: add parameters to exercise placeholder

exercises/run-length-encoding/run_length_encoding.py
run-length-encoding: add parameters to exercise placeholder #625
Fixes #625
=> run-length-encoding: add parameters to exercise placeholder

exercises/trinary/trinary.py
Solving issue #648 
Fixes #648
=> trinary: added parameter name

exercises/space-age/space_age.py
=> Add parameter to exercise Space Age

exercises/say/say.py
=> Add parameter to exercise Say

exercises/grep/grep.py
=> add template with expected parameter to grep exercise

exercises/diamond/diamond.py
Added parameter placeholder 'string' for the diamond exercise
Resolves #554
=> diamond: Added parameter placeholder (#554)

exercises/nucleotide-count/nucleotide_count.py
=> nucleotide-count: add parameters to exercise placeholder

exercises/word-count/word_count.py
Hi, I went ahead and added the necessary parameter to fix #652 in word_count.
=> word_count: Fix #652 add parameters to placeholder

exercises/ocr-numbers/ocr_numbers.py
=> ocr_numbers: Add parameters to exercise placeholder #602

exercises/largest-series-product/largest_series_product.py
Signed-off-by: Ian Dexter D Marquez <iandexter@users.noreply.github.com>
Closes #567
=> largest-series-product: Add parameter to exercise placeholder (#567)

exercises/poker/poker.py
=> poker: Add parameters to exercise placeholder

exercises/pangram/pangram.py
=> pangram: Add parameter to exercise placeholder

exercises/proverb/proverb.py
=> proverb: Add parameter to exercise placeholder

exercises/collatz-conjecture/collatz_conjecture.py
Closes #552, I decided on `n` instead of `number` this time as it matches the README which calls the integer n
=> collatz-conjecture: Add parameter to placeholder file

exercises/octal/octal.py
=> Octal: add parameters to function placeholder

exercises/rail-fence-cipher/rail_fence_cipher.py
=> Rail fence cypher: Add parameters to placeholder functions

exercises/prime-factors/prime_factors.py
prime-factors: add parameters to exercise placeholder #612 
Resolves #612
=> prime-factors: add parameters to exercise placeholder

exercises/crypto-square/crypto_square.py
Added a words parameter to the abbreviate method to ensure clarity to future users. This change was discussed in issue #553 .
Fixes #553
=> Crypto-square: Update function to have params as in #553

exercises/binary-search/binary_search.py
=> binary-search: Add parameters to exercise placeholder

exercises/pascals-triangle/pascals_triangle.py
=> pascals-triangle: add parameters to exercise placeholder

exercises/binary/binary.py
This is for #545 . Not sure if too wordy, I like `binary` but not sure if that is to general?
Fixes #545
=> binary: updated placeholder parameters to be more specific

exercises/accumulate/accumulate.py
=> accumulate: Add parameters to exercise placeholder (closes #537)

exercises/allergies/allergies.py
(Hopefully, the new parameter names are more meaningful.)
=> allergies: Revise parameters in exercise placeholder (closes #539)

exercises/secret-handshake/secret_handshake.py
=> secret-handshake: Add parameters to exercise placeholder

exercises/anagram/anagram.py
I added parameter string to template question. #541 
Fixes #541
=> anagram: added parameter to template question

exercises/roman-numerals/roman_numerals.py
I added parameter string to template question. #623
Fixes #623
=> roman-numerals: added parameter to template question 

exercises/rotational-cipher/rotational_cipher.py
rotational-cipher: add parameters to exercise placeholder #624
Fixes #624
=> rotational-cipher: add parameters to exercise placeholder

exercises/pythagorean-triplet/pythagorean_triplet.py
=> pythagorean-triplet: add parameters to exercise placeholder

exercises/transpose/transpose.py
=> transpose: add parameters to exercise placeholder

exercises/perfect-numbers/perfect_numbers.py
=> perfect-number: added parameters to exercise placeholder

exercises/raindrops/raindrops.py
Proposing PR for #618 
Fixes #618
=> raindrops : added default params to exercise template

exercises/scale-generator/scale_generator.py
Proposing PR for #635 
Resolves #635
=> scale generator: added default params to scale exercise template

exercises/sieve/sieve.py
Proposing PR for #639
Fixes #639
=> sieve: added default params

exercises/palindrome-products/palindrome_products.py
=> palindrome-product: Add parameter to exercise placeholder

exercises/flatten-array/flatten_array.py
Solving issue #557 
Resolves #557
=> flatten-array: added parameters to exercise placeholder

config.json, exercises/two-bucket/example.py, exercises/two-bucket/two_bucket.py, exercises/two-bucket/two_bucket_test.py
Implemented the "two-bucket" exercise.
Resolves #734
=> two-bucket: implemented exercise

exercises/circular-buffer/circular_buffer.py
=> Add parameter capacity to circular-buffer example

exercises/clock/clock.py
=> Add parameters to init in clock example

exercises/grade-school/grade_school.py
=> grade-school: Add expected parameter name to init method

exercises/kindergarten-garden/kindergarten_garden.py
=> kindergarten-garden: Add parameters to exercise placeholder kindergarten-garden

exercises/sum-of-multiples/sum_of_multiples.py
=> sum-of-multiples: Add parameters to exercise placeholder for sum-of-multiples

exercises/rectangles/rectangles.py
=> rectangles: fixed #619

exercises/etl/etl.py
=> etl: Add expected parameter old to etl example

exercises/linked-list/linked_list.py
=> linked-list: Add parameters to init function in linked-list example

exercises/grains/grains.py
Added a parameter to the grains.py file.
Fixes #560
=> grains: Add the 'integer' parameter to the grains.py exercise file

exercises/robot-simulator/robot_simulator.py
=> robot-simulator: add parameters to exercise placeholder

exercises/leap/leap_test.py
=> leap: replace assertFalse with assertIs

exercises/series/series.py
=> series: add parameters to exercise placeholder

exercises/bracket-push/bracket_push.py
…erences Issue #548
-----
Resolves #548
=> bracket-push: Update the param name to clarify further to users

config.json
=> Add Isogram topics

config.json
=> Add topics for run-length-encoding

config.json
=> fixes #815 - anagram: add topics #815

config.json
=> gigasecond: Add topics

config.json
=> Add topics for 'Beer Song'

config.json
=> Add topics for 'Say'

config.json
=> Add topics for 'tournament'

config.json
=> Add Series topics

config.json
=> Add topics for transpose

config.json
=> Atbash-cipher: add topics

config.json
=> Robot-simulator: add topics

config.json
=> zebra-puzzle: add topics

config.json
=> rectangles: add topics

exercises/luhn/luhn_test.py
=> luhn: replace assertFalse with assertIs

config.json
=> list-ops: add topics

config.json
=> sublist: Add topics

config.json
Added topics with correct rebase of exercism/python master branch
Resolves #870
=> added topics for alphametic

config.json
=> triangle: add topics

config.json
=> added topics for phone-number exercises

config.json
=> crypto-square: add topics

config.json
=> prime-factors: added topics

config.json
=> simple-cipher: added topics

config.json
=> added topics for acronym exercise

config.json
=> Sieve: add topics

config.json
=> added topics for nth-prime exercise

config.json
=> allergies: added topics

exercises/pythagorean-triplet/pythagorean_triplet_test.py
=> pythagorean-triplet: replace assertFalse with assertIs

exercises/perfect-numbers/perfect_numbers_test.py
=> perfect-numbers: replace assertFalse with assertIs

exercises/pascals-triangle/pascals_triangle_test.py
=> pascals-triangle: replace assertFalse with assertIs

exercises/queen-attack/queen_attack_test.py
replace assertFalse with assertIs because the test passes if the tested method returns None
replace assertTrue with assertIs for consistency.
=> queen_attack: replace assertFalse with assertIs

config.json
Add topics to queen attack in `config.json`
closes #854
=> queen-attack: Added topics

config.json
=> Added topics for largest-series-product

config.json
=> sum-of-multiples: Add topics

config.json
=> pig-latin: Add topics

config.json
=> binary-search: Add topics

config.json
=> house : add topics

config.json
=> twelve-days: add topics to resolve #850

config.json
Closes https://github.com/exercism/python/issues/839
=> Add topics for pythagorean triple.

config.json
Fixes issue #842 by adding topics to `robot-name`
=> Added Topics for robot-name

exercises/change/README.md, exercises/two-bucket/README.md
It turned out that there are some exercises in this track which didn't have README.md files as mentioned in https://github.com/exercism/discussions/issues/200#issuecomment-336596103
This PR solves the issue
=> Add missing README.md files for change and two-bucket

config.json
I'll take this if I may.
Fixes #825 // m-a-ge
=> Add topics for kindergarten-garden as per issue #825

config.json
=> palindrome-products: add topics

config.json
=> add topics for scrabble-score

config.json
Add topics to roman-numerals exercise.
Fixes #828
=> Add topics to roman-numerals exercise

config.json
Add topics for secret-handshake exercise.
Fixes #849
=> Add topics for secret-handshake exercise

config.json
=> etl: add topics

config.json
Add topics for grade school exercise.
Fixes #826
=> Add topics for grade school exercise

config.json
Given #808 this PR adds topics to the "flatten-array" problem in `config.json`
Closes #827
=> Adds topics-flatten-array

README.md
Added license information to README.md
=> Added license information to README.md

config.json
Topics are added to config.json. They are more accurate and precise. Thanks
=> Add topics: perfect numbers

config.json
=> bob: add topics

config.json
=> Added topics for Meetup

config.json
This PR add topics for circular buffer exercise described at #840 .  Merging this PR will eventually close #840
=> circular-buffer: add topics

config.json
This PR should implement related topics for saddle-points exercise in config.json as per description in issue #846 . This PR will close #846.
=> saddle-points: add topics

config.json
=> rail-fence-cipher: add topics

exercises/point-mutations/point_mutations.py
Closes https://github.com/exercism/python/issues/610
=> Point-emulations: Add parameters to exercise placeholder

config.json
=> ocr-numbers : add topics

config.json
=> minesweeper : add topics

config.json
=> bracket-push : add topics

exercises/pangram/pangram_test.py
=> pangram: replace assertFalse with assertIs

exercises/allergies/allergies_test.py, exercises/allergies/example.py
=> allergies: replace assertFalse with assertIs

exercises/complex-numbers/complex_numbers_test.py
=> complex_numbers: Fix spelling mistake

exercises/isogram/isogram_test.py
=> isogram: update tests to version 1.2.0

exercises/clock/clock_test.py
Added missing test version comment to match current tests cases.
Verified test content order and completion. Closes #992
=> clock: update tests to version 1.0.0

exercises/two-bucket/two_bucket_test.py
=> two-bucket: Add version string

exercises/two-fer/two_fer_test.py
=> Updating two_fer_test to match canonical-data

config.json, exercises/tree-building/README.md, exercises/tree-building/example.py, exercises/tree-building/tree_building.py, exercises/tree-building/tree_building_test.py
=> tree-building : implement exercise

exercises/wordy/wordy_test.py
=> wordy: added test version and updated tests to match canonical

exercises/word-count/example.py
Updates the example code for `word-count` to resolve #1045.
(CC: #1044)
=> word-count: Update example to work with new tests

exercises/change/change_test.py
Added missing test version comment using format for current test cases.
Verified test content order and completion. Closes #990
=> change: update tests to version 1.1.0

exercises/robot-simulator/robot_simulator_test.py
=> robot-simulator: Updated test order to match canonical-data.json

exercises/nth-prime/nth_prime.py
=> nth-prime: add parameters to exercise placeholder

exercises/crypto-square/crypto_square_test.py, exercises/crypto-square/example.py
Update the `crypto square` testes following the recomandations of issue #994
=> crypto-square: Update the tests following the canonical data

exercises/alphametics/example.py
Faster example...
Resolves #1066 // m-a-ge
Resolves #524 // m-a-ge
=> alphametics: Update example solution to be more performance efficient 

exercises/kindergarten-garden/kindergarten_garden_test.py
Renamed existing tests to match test case descriptions.
Deleted and added test cases to bring test list into agreement with data.
Added missing test version comment. Closes #997
=> kindergarten-garden: update tests to version 1.0.0

test/check-exercises.py
=> update check-exercises.py to run skipped tests

config/maintainers.json
Updating my own information in the maintainers.json file.
=> Added information to maintainers.json

exercises/phone-number/example.py, exercises/phone-number/phone_number_test.py
Resolves #471
- raise ValueError instead of returning "0000000000"
- normalized extensions to properties
=> phone-number: refactor errors and extensions

config.json
This change pertains to https://github.com/exercism/configlet/issues/99
=> config.json: Fix invalid UUIDs

config.json
This PR resolves #1102 by adding a blurb to `config.json`.
The blurb reads:
> Python is a clear and powerful object-oriented programming language with an elegant and easy-to-read syntax. It is ideal for prototyping and ad-hoc tasks, but also sees wide use in scientific computing, web development, and automation.
=> config.json: Add blurb to resolve #1102

exercises/book-store/book_store_test.py
=> book-store: update tests to version 1.1.0

config.json, exercises/armstrong-numbers/README.md, exercises/armstrong-numbers/armstrong_numbers.py, exercises/armstrong-numbers/armstrong_numbers_test.py, exercises/armstrong-numbers/example.py
=> add new exercise: armstrong-numbers (closes  #1131)

exercises/difference-of-squares/difference_of_squares.py, exercises/difference-of-squares/example.py
=> difference-of-squares: add parameters to exercise template

exercises/transpose/example.py, exercises/transpose/transpose_test.py
* also make tests a bit more uniform
(needed to update example solution)
[https://github.com/exercism/problem-specifications/commits/master/exercises/transpose/canonical-data.json](https://github.com/exercism/problem-specifications/commits/master/exercises/transpose/canonical-data.json)
=> transpose: update tests to 1.1.0

exercises/dot-dsl/dot_dsl_test.py
This PR resolves #1151 by fixing two errors in the tests, and implements exception message checks as-per #1080.
=> dot-dsl: Fix error and implement exception message checks

exercises/triangle/example.py, exercises/triangle/triangle.py, exercises/triangle/triangle_test.py
Fixes #1008 
[Canonical data](https://github.com/exercism/problem-specifications/blob/506de961e642c1cd4c7489d394b6dd148410b7fb/exercises/triangle/canonical-data.json)
=> triangle: update tests to canonical-data v1.0.0

exercises/grep/grep_test.py
=> grep: replace usage of real files

exercises/luhn/example.py, exercises/luhn/luhn.py
=> luhn: add parameters to exercise placeholder

exercises/house/example.py, exercises/house/house.py
=> house: add parameters to exercise placeholder

config.json
=> bowling: move to appropriate spot in exercise list

exercises/beer-song/beer_song.py, exercises/beer-song/beer_song_test.py, exercises/beer-song/example.py
Fixes #1128 
[Canonical data](https://github.com/exercism/problem-specifications/blob/506de961e642c1cd4c7489d394b6dd148410b7fb/exercises/beer-song/canonical-data.json)
=> beer-song: update tests to canonical data v2.1.0

exercises/acronym/acronym_test.py
Closes #1201. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/acronym/canonical-data.json).
* Remove outdated test case
* Rename test method `test_hyphenated`
=> acronym: update tests to v1.3.0

exercises/pov/example.py, exercises/pov/pov.py, exercises/pov/pov_test.py
Closes #1256. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/pov/canonical-data.json).
- Move utility `assertTreeEquals` to right place
- Apply 'snake_case' naming style
=> pov: update tests to v1.2.0

exercises/change/change_test.py, exercises/change/example.py
Closes #1246. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/change/canonical-data.json).
=> change: update tests to v1.1.0

exercises/book-store/book_store_test.py, exercises/book-store/example.py
Closes #1235. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/book-store/canonical-data.json).
=> book-store: update tests to v1.3.0

exercises/roman-numerals/roman_numerals_test.py
Closes #1206. [Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/roman-numerals/canonical-data.json)
* Add test case 49
=> roman-numerals: update tests to v1.2.0

exercises/luhn/luhn.py, exercises/luhn/luhn_test.py
Closes #1208. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/luhn/canonical-data.json).
* Change file encoding from Windows 1252 to UTF-8
=> luhn: update tests to v1.1.0

exercises/markdown/markdown_test.py
Closes #1251. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/markdown/canonical-data.json).
=> markdown: update tests to v1.2.0

exercises/binary-search-tree/binary_search_tree.py, exercises/binary-search-tree/binary_search_tree_test.py, exercises/binary-search-tree/example.py
Closes #1258. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search-tree/canonical-data.json).
=> binary-search-tree: re-implement exercise according to canonical data

exercises/phone-number/phone_number_test.py
Closes #1227. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json).
=> phone-number: update tests to v1.4.0

exercises/clock/clock.py, exercises/clock/clock_test.py, exercises/clock/example.py
Closes #1239. [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/clock/canonical-data.json).
=> clock: update tests to v2.2.1

exercises/word-count/word_count_test.py
Solves #1189. Add missing version number.
=> word-count: update tests to v1.2.0

config.json
Closes #1099 
I started with the curriculum in the C# track, accounted for exercises that are deprecated in this track but not that one, then did some reasonable reordering. I also added a couple topics to exercises that should have had them anyway.
[Visualization tool by @jonmcalder.](https://jonmcalder.shinyapps.io/exercism-config-viz/) (https://github.com/exercism/discussions/issues/175#issuecomment-318243990) Simply upload [config.json](https://raw.githubusercontent.com/cmccandless/python/curriculum/config.json).
=> Curriculum

exercises/go-counting/README.md
Update README according to this [commit](https://github.com/exercism/problem-specifications/commit/56c7a3dc8409009351ce546d3aac2c22b4894a8a).
=> go-counting: update README to latest description

exercises/bracket-push/bracket_push_test.py
Add a new test case mentioned in exercism/problem-specifications#1219.
=> bracket-push: update tests to v1.3.0

exercises/pov/pov_test.py
See this [commit](https://github.com/exercism/problem-specifications/commit/ff3dbd92e5cf2db5b362a5fe8637f85992b61c1c).
=> pov: update tests to v1.3.0

exercises/series/README.md, exercises/series/example.py, exercises/series/series_test.py
Close #1109. 
Close #1117. 
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/series/canonical-data.json). 
[Description](https://github.com/exercism/problem-specifications/blob/master/exercises/series/description.md).
=> series: re-implement according to canonical data

exercises/yacht/README.md
See this [commit](https://github.com/exercism/problem-specifications/commit/4acb203b74c65930a8e101c6e24fdf209ed10317).
=> yacht: remove redundant whitespaces in README

exercises/yacht/yacht_test.py
Check out this [commit](https://github.com/exercism/problem-specifications/commit/6eb19d22259376a3166d605a416023ab6f5c0cc7).
=> yacht: add test case "Four of a kind is not a full house"

exercises/markdown/markdown.py
=> markdown: unordered lists test of inital implementation fails when it should pass

exercises/armstrong-numbers/README.md
See this [commit](https://github.com/exercism/problem-specifications/commit/c2e0b3defcc600fe16d73f2ad4b4cad30e313dbe).
=> armstrong-number: Fix math error in description

exercises/bracket-push/README.md
See this [commit](https://github.com/exercism/problem-specifications/commit/5bee5e629ebc50af349996a6b5cc82330d49cced).
=> bracket-push: update README

exercises/hamming/README.md
Checkout this [commit](https://github.com/exercism/problem-specifications/commit/bdf420cca82218b319c67f2c76342dd459cebf51).
=> hamming: rewrite info on sequences of different length in README

exercises/diffie-hellman/diffie_hellman_test.py
=> diffie-helman: update tests to v1.0.0

config.json
Added auto_approve to hello-world for issue #1401 [see https://github.com/exercism/c/issues/303#issuecomment-396647726]
=> Added auto_approve to hello-world

docs/ABOUT.md
=> conform ABOUT.md to formatting guidelines

exercises/simple-cipher/example.py, exercises/simple-cipher/simple_cipher.py, exercises/simple-cipher/simple_cipher_test.py
=> simple-cipher: update tests to canonical data 1.0.0

exercises/simple-cipher/simple_cipher_test.py
See exercism/problem-specifications#1253
=> simple-cipher: update tests to v1.1.0

config.json, exercises/ledger/README.md, exercises/ledger/example.py, exercises/ledger/ledger.py, exercises/ledger/ledger_test.py
Resolves #737 
Tests based on [C# implementation](https://github.com/exercism/csharp/blob/master/exercises/ledger/LedgerTest.cs), with the addition of test case `test_dutch_locale_and_euros`.
As this is a refactoring exercise, review comments regarding further de-improving `ledger.py` are especially welcome.
=> ledger: implement exercise

docs/LEARNING.md, docs/TESTS.md
=> Fix documentation heading formatting for v2

exercises/house/example.py, exercises/house/house_test.py
=> house: fix spacing

exercises/grade-school/example.py, exercises/grade-school/grade_school.py, exercises/grade-school/grade_school_test.py
=> grade-school: update tests to v1.0.0

README.md
Exercism.io link no longer exists.
=> Fix link for unimplemented issues

config.json, exercises/rest-api/README.md, exercises/rest-api/example.py, exercises/rest-api/rest_api.py, exercises/rest-api/rest_api_test.py
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/rest-api/canonical-data.json)
=> rest-api: implement exercise

exercises/complex-numbers/complex_numbers_test.py, exercises/complex-numbers/example.py
=> complex-numbers: don't require user implementation to round values

exercises/isogram/isogram_test.py
=> isogram: updates tests to v1.4.0

exercises/list-ops/list_ops_test.py
=> list-ops: updates tests to v2.3.0

exercises/tree-building/tree_building.py
As a refactor exercise, the initial solution must pass all tests. When the test suite was updated to require exception messages, the initial solution was not updated*. This PR resolves this.
*As noted in https://github.com/exercism/problem-specifications/issues/1296
=> tree-building: add error messages

exercises/kindergarten-garden/kindergarten_garden_test.py
Resolves #1438. No changes were made since the diff between 1.1.0 and 1.1.1 shows only a comment being removed:
https://github.com/exercism/problem-specifications/pull/1222/files
=> kindergarten-garden: updates tests to v1.1.1

exercises/protein-translation/protein_translation_test.py
=> protein-translation: updates tests to v1.1.1

exercises/collatz-conjecture/collatz_conjecture_test.py
Resolves #1452. No changes were made since the diff between 1.2.0 and 1.2.1 shows only the description styling updated:
https://github.com/exercism/problem-specifications/pull/1292/files
=> collatz-conjecture: updates tests to v1.2.1

exercises/acronym/acronym_test.py
=> acronym: updates tests to v1.4.0

exercises/rna-transcription/rna_transcription_test.py
=> rna-transcription: updates tests to v1.3.0

exercises/book-store/book_store_test.py, exercises/book-store/example.py
=> book-store: updates tests to v1.4.0

exercises/sgf-parsing/example.py, exercises/sgf-parsing/sgf_parsing_test.py
=> update-sgf-parsing: updates tests to v1.0.0

exercises/word-search/word_search_test.py
Resolves #1439. From v1.2.0 to v1.2.1, only the comments changed: https://github.com/exercism/problem-specifications/commit/2b022518f763bd5b223f4e578a440ae5e3184346
=> update-word-search: updates tests to v1.2.1

exercises/pangram/pangram_test.py
Resolves #1470. From v1.4.0 to v1.4.1 only the description was changed: https://github.com/exercism/problem-specifications/commit/2c020bcf8a115319bf418ced459e7636ae202bf4#diff-98967529f5adf348fce12448bdd991a7
=> pangram: updates tests to v1.4.1

exercises/bob/bob_test.py
=> bob: updates tests to v1.3.0

exercises/allergies/allergies_test.py
=> allergies: updates tests to v1.2.0

exercises/anagram/anagram.py, exercises/anagram/anagram_test.py, exercises/anagram/example.py
Resolves #1472. Going from 1.2.0 to 1.3.0 removed comments and changed property naming:
https://github.com/exercism/problem-specifications/commit/725b76723b14391724ba711c45d6610b0d32feb2#diff-455d887764697eedf47c8297997dc4ff
https://github.com/exercism/problem-specifications/commit/3faf343b955dd86fed103364314b8b29b64c7761#diff-455d887764697eedf47c8297997dc4ff
=> anagram: updates tests to v1.3.0

exercises/bracket-push/bracket_push_test.py
=> update-bracket-push: updates tests to v1.4.0

exercises/clock/clock_test.py
=> update-clock: updates tests to v2.3.0

exercises/isogram/isogram_test.py
=> update-isogram: updates tests to v1.5.0

exercises/isogram/isogram_test.py
New to this project, but noticed this test was out-of-date. Modified it to match new test suite.
=> isogram: updates tests to v1.6.0

exercises/bob/bob_test.py
Closes https://github.com/exercism/python/issues/1500.
=> bob: updates tests to 1.4.0

exercises/twelve-days/README.md, exercises/twelve-days/example.py, exercises/twelve-days/twelve_days_test.py
The specification for Twelve Days has changed and this pull request brings the python implementation up to date. Closes #1509.
https://github.com/exercism/problem-specifications/pull/1329
=> twelve-days: update tests to match specification

exercises/phone-number/phone_number_test.py
=> phone-number: Update tests to v1.6.0

exercises/variable-length-quantity/variable_length_quantity_test.py
=> variable-length-quantity: Updated tests to 1.2.0

exercises/binary-search/binary_search_test.py
Update binary search to 1.2.0
Fix #1528
=> binary-search: update tests to v1.2.0

exercises/largest-series-product/largest_series_product_test.py
Largest product update.
Fix #1529
=> largest-series-product: update tests to v1.2.0

exercises/say/say_test.py
Update say to 1.2.0.
Fix #1523
=> say: update tests to v1.2.0

exercises/queen-attack/queen_attack_test.py
Update queen attack test.
Fix #1526
=> queen-attack: update tests to v2.2.0

exercises/rest-api/README.md, exercises/rest-api/rest_api_test.py
Change README.md to conform with latest canonical data.
Resolves #1521
=> rest-api: Update exercise to v1.0.1

exercises/acronym/acronym_test.py
=> acronym: Update tests to v1.5.0

exercises/forth/forth_test.py
=> forth: update tests to v1.7.0

exercises/forth/forth_test.py, exercises/ocr-numbers/ocr_numbers_test.py
=> ocr-numbers: update tests to v1.2.0

exercises/queen-attack/queen_attack_test.py, exercises/robot-simulator/robot_simulator_test.py
Updated tests to v2.3.0 , added Exception tests for invalid directions/instructions as well as tests for each direction the robot can go
Closes #1525
=> robot-simulator: updated tests to v3.0.0

exercises/anagram/anagram_test.py
=> anagram: update tests to v1.4.0

exercises/robot-simulator/robot_simulator_test.py
Updated robot simulator test cases to v3.1.0 and added comments to describe tests.
Resolves #1555
=> Updated robot simulator test cases to v3.1.0

exercises/simple-cipher/README.md, exercises/simple-cipher/example.py, exercises/simple-cipher/simple_cipher_test.py
https://github.com/exercism/problem-specifications/commit/f7f365965726c5c22177df31738a09441b2bfc4a#diff-3a8d30da249c3e567543e378169d466b
=> simple-cipher: update tests to v1.2.0

exercises/grep/example.py, exercises/grep/grep_test.py
https://github.com/exercism/problem-specifications/commit/4f2efaa7a18fce99e91b01b3b11f13cac795735c#diff-593bb60c24b63589316b40f4cb8decd2
=> Update grep tests to v1.2.0

exercises/custom-set/custom_set.py
=> custom-set: Corrected Function Names to match Test

exercises/hamming/hamming_test.py
Fixes #1579
* Version increment
=> hamming: update tests to v2.1.1 

exercises/acronym/acronym_test.py, exercises/acronym/example.py
Updated test case for apostrophes in [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/acronym/canonical-data.json) and updated example.py to correctly solve the new apostrophe test case.
=> acronym: update tests to v1.6.0

exercises/wordy/wordy_test.py
=> wordy: test suite update to v1.5.0

exercises/wordy/wordy_test.py
=> wordy: bump canonical version

exercises/bank-account/bank_account_test.py, exercises/bank-account/example.py
- Use `assertRaisesWithMessage` instead of `assertRaises`
- Add test case for closing already closed account
- Add test case for opening already opened account
- Refactor tests to use local instances of BankAccount instead of shared one
- Refactor `example.py` to pass new tests
=> bank-account: refactor

exercises/book-store/example.py
Faster solution to reduce Travis build times
=> book-store: refactor for speed

README.md
This has been established for a while now, but was never officially added as a track convention.
=> README: add convention for exception messages

exercises/pythagorean-triplet/example.py
...and speed. Turns out, there was a lot of room for improvement. Rough estimate, this solution runs ~15 times faster than the current one.
Resolves #1598
@yawpitch, as you raised #1598, I welcome your input in particular on this one. As always, input from others is also welcome.
=> pythagorean-triplet: refactor for readability

exercises/phone-number/phone_number_test.py
Fixes #1582
* Version increment.
=> phone-number: update tests to v1.6.1

exercises/react/react.py
=> react: expect_callback_values removed

exercises/isogram/isogram_test.py
=> isogram: update tests to v1.7.0

exercises/luhn/luhn_test.py
=> luhn: update tests to v1.3.0

exercises/bracket-push/bracket_push_test.py
=> bracket-push: update tests to v1.5.0

exercises/bank-account/bank_account_test.py
If a solution passes after 1 pass of 1000 concurrent transactions,
9 additional passes will not cause that solution to fail. These extra
passes only waste processing time, both for the student and for
contributors.
=> bank-account: remove redundant iteration

exercises/triangle/triangle_test.py
=> triangle: update tests to v1.2.0

test/check-exercises.py
=> test/check_exercises.py: improve portability

exercises/sgf-parsing/sgf_parsing.py, exercises/sgf-parsing/sgf_parsing_test.py
=> sgf-parsing: update tests to 1.2.0

exercises/high-scores/example.py, exercises/high-scores/high_scores_test.py
Fixes #1616
* Update _test.py test case names to fit with canonical data 
* Update example.py to fit with new test case names.
=> high-scores: update tests to v2.0.0

exercises/gigasecond/example.py, exercises/gigasecond/gigasecond.py, exercises/gigasecond/gigasecond_test.py
Fixes #1619
* Increment version number in _test.py
* Changed template function argument to match canonical data
* Changed example.py function argument to better match template
=> gigasecond: update tests to v2.0.0

exercises/clock/clock_test.py
Fixes #1618
* Updated test suite to test for exactly negative 1 hour.
=> clock: update tests to v2.4.0

exercises/scale-generator/example.py, exercises/scale-generator/scale_generator.py, exercises/scale-generator/scale_generator_test.py
=> scale-generator: update tests to v2.0.0

exercises/raindrops/raindrops_test.py
=> raindrops: update test to v1.1.0

exercises/hamming/hamming_test.py
Updated hamming test cases to v2.2.0. Fixes #1621
=> hamming: updated tests to v2.2.0

exercises/luhn/luhn_test.py
=> Luhn: update tests to 1.4.0

exercises/phone-number/phone_number_test.py
=> phone-numbers: update tests to 1.7.0

exercises/matrix/README.md, exercises/matrix/example.py, exercises/matrix/matrix_test.py
=> Matrix: update tests to 1.1.0

exercises/binary-search/binary_search_test.py
=> binary-search: updated tests to 1.3.0

exercises/pythagorean-triplet/example.py
`is_triplet` is not used in the solution
=> pythagorean-triplet: remove unused code

exercises/saddle-points/README.md
The indexes were changed for matrices in multiple exercises, but I missed it in the README.md for saddle-point
=> saddle-point: update README.md

exercises/hamming/README.md, exercises/hamming/hamming_test.py
Update hamming to v2.3.0 (closes #1675)
[Problem Specification](https://github.com/exercism/problem-specifications/tree/master/exercises/hamming)
**Changes:**
1. Updated **README.md**
2. Update version to **v2.3.0** on **hamming_test.py**
3. Added 2 new tests (**test_disallow_left_empty_strand** and **test_disallow_right_empty_strand**) according to the Problem Specification
=> Update hamming to v2.3.0 (closes #1675)

exercises/high-scores/README.md, exercises/high-scores/example.py, exercises/high-scores/high_scores_test.py
Update exercise high-scores to v4.0.0 (closes #1672)
[Problem Specification](https://github.com/exercism/problem-specifications/tree/master/exercises/high-scores)
**Changes**:
1. Removed **report** part from **README**
2. Renamed function **personal_top()** to **personal_top_three()** on **example.py** and **high_scores_test.py**
3. Removed **deprecated** test cases from **high_scores_test.py** according to problem specification
4. Removed function **report()** on **example.py**
5. Updated test version header to **v4.0.0** on **high_scores_test.py**
=> high-scores: update test suite to v4.0.0 (closes #1672)

.travis.yml
See the following for more details:
- https://docs.travis-ci.com/user/reference/trusty#container-based-infrastructure
- https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures
=> Switch Travis builds to VM-based infrastructure

.travis.yml
=> Remove Python2.7 from Travis build matrix

exercises/rest-api/rest_api_test.py
=> rest-api: update tests to v1.1.1

test/check-exercises.py
Fixes #1706
Changed shebang
Removed unnecessary print_function import
=> Update check-exercises.py to Python 3

exercises/darts/darts_test.py
Fixes canonical data comment to fix FP.
Closes #1726
=> darts: Fixes FP for out of date test suite

exercises/satellite/satellite_test.py
Fixes #1728 as renames were done in a different commit.
=> satellite: update tests to v2.0.0

exercises/leap/leap_test.py
=> leap: update tests to v1.5.1

exercises/rational-numbers/rational_numbers_test.py
=> rational-numbers: update tests to v1.1.0

exercises/simple-cipher/simple_cipher_test.py
=> simple-cipher: update tests to v2.0.0

docs/ABOUT.md
=> ABOUT.md: remove Python 2 references

exercises/sgf-parsing/README.md
=> sgf-parsing: regenerate README

exercises/matrix/.meta/HINTS.md, exercises/matrix/README.md
Previously it was included in High-Scores.
Now this is the first exercise that contain classes.
Made this change as separate PR as discussed in #1764
=> Add class HINTS to Matrix.

exercises/luhn/luhn_test.py
=> luhn: update tests to v1.5.0

exercises/triangle/triangle_test.py
=> triangle: update tests to v1.2.1 (#1757)

exercises/alphametics/alphametics_test.py, exercises/alphametics/example.py
Issue: https://github.com/exercism/python/issues/1762
Update `alphametics` exercise so it matches [canonical-data.json](https://github.com/exercism/problem-specifications/blob/51418ec78bcca075b586d4c38d66d2c322b488fe/exercises/alphametics/canonical-data.json)
=> alphametics: sync with problem-specifications

exercises/queen-attack/queen_attack_test.py
=> queen-attack: update tests to v2.3.0

exercises/resistor-color-duo/resistor_color_duo_test.py
=> resistor-color-duo: update tests to v2.0.0

exercises/darts/darts_test.py
=> darts: update tests to v2.0.0

exercises/tournament/example.py, exercises/tournament/tournament_test.py
The file is now more like the problem-specifications file
=> Changed tournament_tests files

exercises/allergies/allergies.py, exercises/allergies/allergies_test.py, exercises/allergies/example.py
Updated it for canonical-data v2.0.0
Fixes #1756
=> allergies: update tests to v2.0.0

exercises/collatz-conjecture/collatz_conjecture.py, exercises/collatz-conjecture/collatz_conjecture_test.py, exercises/collatz-conjecture/example.py
Issue #1762 
Changes the name of the function to implement from `collatz_steps` to `steps`.
=> collatz-conjecture: sync with problem-specifications

exercises/triangle/example.py, exercises/triangle/triangle.py, exercises/triangle/triangle_test.py
Issue #1762
Changes the name of the functions to implement and the names of the test suites.
=> triangle: sync with problem-specifications

exercises/markdown/example.py, exercises/markdown/markdown.py, exercises/markdown/markdown_test.py
=> markdown: update tests to v1.4.0

exercises/gigasecond/example.py, exercises/gigasecond/gigasecond.py, exercises/gigasecond/gigasecond_test.py
- Changed function name in tests, `example.py`, and exercise stub to **add** - to conform with `canonical-data.json`.
=> Gigasecond : sync expected test results and input data with problem-specifications

exercises/pythagorean-triplet/example.py, exercises/pythagorean-triplet/pythagorean_triplet.py, exercises/pythagorean-triplet/pythagorean_triplet_test.py
- Changed name of function arguments to **number**, **start**, **end**, and **triplet** in `example.py` and exercise stub to conform with `canonical-data.json`.
- Changed **expected data type** of tests to **list of lists** to conform to `canonical-data.json`.
- Due to the very mathematical nature of the functions, **did not** change single letter variable names in the `example.py` file, as it would not have clarified things.
- Changed `example.py` to return a `sorted()` **list of lists** to match the expected results in tests.
=> Pythagorean triplet: sync expected test results and input data with problem-specifications.

exercises/wordy/example.py, exercises/wordy/wordy_test.py
Minor cleanup of the wordy exercise:
- fixed inconsistent use of quotations in the `wordy_test.py` file.
- fixed indentation
- variable name changes in the `example.py`
=> wordy: cleanup

config/maintainers.json
As per @kytrinyx adding myself as mentor.
=> Adds yawpitch as maintainer

config.json
Discussion in this PR is a continuation of the discussion in #1827; reviewers should read the conversation there before commenting here. This PR must not be merged until consensus in #1827 is reached.
Resolves #1827
=> Do not unlock side exercises with hello-world

exercises/complex-numbers/complex_numbers_test.py
A requested follow-up to #1834
=> complex-numbers: handle different real and imaginary parts separately in inequality test

exercises/etl/etl_test.py
No changes to tests; spec format was modified without changing content.
Closes #1842
=> etl: update spec reference to 2.0.0

.travis.yml
Experiment to try running canonical sync check script in CI.
Note to other maintainers: please feel free to review, but do not merge this PR yet.
=> Add Travis job to check sync with canonical data

exercises/darts/darts_test.py
Fixes #1840 
- Changed test names, test cases and test arguments to fit with [canonical data] (https://github.com/exercism/problem-specifications/blob/master/exercises/darts/canonical-data.json)2.2.0
- Deleted several redundant tests that remained after updates (tested the same thing twice)
- Moved the remainder of tests (and added one new one) to "additional" as in my opinion they are non-trivial
=> darts: update tests to canonical data 2.2.0

bin/generate_tests.py, config/generator_macros.j2, exercises/hamming/.meta/template.j2, exercises/hamming/hamming_test.py
- add 'is error_case' Jinja2 test
- create Jinja2 macros file, add utility method macro
=> hamming: add test template

exercises/nth-prime/nth_prime.py
The tests are expecting the function to be named prime and not nth_prime:
https://github.com/exercism/python/blob/master/exercises/nth-prime/nth_prime_test.py
=> Fix function name in nth prime

exercises/word-count/word_count_test.py
closes #1876 
link to [problem-specifications](https://github.com/exercism/problem-specifications/commit/055a260854943e612ce4d828a6dc4ec88b4682b5)
=> word-count: Updated to 1.4.0

exercises/raindrops/README.md, exercises/raindrops/example.py
Updates the example.py and README.md to conform to new position in the Core exercises.
Closes #1859 and closes #1878.
=> raindrops: update for track anatomy

config/generator_macros.j2, exercises/isogram/.meta/template.j2, exercises/isogram/isogram_test.py
- add canonical_ref() generator macro
=> isogram: add test template

exercises/resistor-color-duo/.meta/template.j2, exercises/resistor-color-duo/resistor_color_duo_test.py
=> resistor-color-duo: add test template

exercises/circular-buffer/.meta/template.j2, exercises/circular-buffer/circular_buffer_test.py
=> circular-buffer: add test template

exercises/two-bucket/.meta/template.j2, exercises/two-bucket/two_bucket_test.py
Add template for two-bucket #1999
=> two-bucket: add test template

exercises/transpose/.meta/template.j2, exercises/transpose/transpose_test.py
Add template for transpose #1997
=> transpose: add test template

.gitignore, exercises/crypto-square/.meta/template.j2, exercises/crypto-square/crypto_square_test.py
This pull request adds test template for crypto-square task. 
Closes #1939
=> Added crypto-square test template

exercises/word-search/.meta/template.j2, exercises/word-search/word_search_test.py
This PR adds a test for word-search #2001
=> word-search: add test template

exercises/variable-length-quantity/.meta/template.j2, exercises/variable-length-quantity/variable_length_quantity_test.py
Add template for variable-length-quantity Closes #2000
=> variable-length-quantity: add test template

exercises/binary-search/.meta/template.j2, exercises/binary-search/binary_search_test.py
=> binary-search : add test template

exercises/zebra-puzzle/.meta/template.j2, exercises/zebra-puzzle/zebra_puzzle_test.py
This pull request adds test template for the zebra-puzzle exercise.
Resolves #2004
=> Zebra-puzzle: add test template

exercises/prime-factors/.meta/template.j2, exercises/prime-factors/prime_factors_test.py
=> prime-factors: add test template

exercises/spiral-matrix/.meta/template.j2, exercises/spiral-matrix/spiral_matrix_test.py
Resolves #1994 
Sorry that the test file changes so much on this one - Black enforces this formatting even if I try to format it better with the Jinja template.
=> spiral-matrix: add test template

config/generator_macros.j2, exercises/yacht/.meta/template.j2, exercises/yacht/yacht_test.py
- Added Jinja template 
- Updated header macro
- Replace given test file with Jinja generated test file
Resolves #2003
=> yacht: add test template

exercises/wordy/.meta/additional_tests.json, exercises/wordy/.meta/template.j2, exercises/wordy/example.py, exercises/wordy/wordy_test.py
After some digging, here is a template for wordy exercise #2002
=> wordy: add test template

exercises/sublist/.meta/additional_tests.json, exercises/sublist/.meta/template.j2, exercises/sublist/sublist_test.py
Add template for Sublist (Closes #1995)
=> sublist: add test template

exercises/difference-of-squares/.meta/template.j2, exercises/difference-of-squares/difference_of_squares_test.py
=> difference-of-squares: Add test template.

exercises/pig-latin/.meta/template.j2, exercises/pig-latin/pig_latin_test.py
=> pig-latin: Add test template.

exercises/protein-translation/.meta/template.j2, exercises/protein-translation/protein_translation_test.py
Add `exercises/protein-translation/.meta/template.j2` and generate a new test module using template.
Closes: #1971
=> protein-translation: Add test template

exercises/satellite/.meta/template.j2, exercises/satellite/satellite_test.py
=> satellite: add test template

exercises/series/.meta/template.j2, exercises/series/series_test.py
=> series: add test template

exercises/robot-simulator/.meta/template.j2, exercises/robot-simulator/example.py, exercises/robot-simulator/robot_simulator.py, exercises/robot-simulator/robot_simulator_test.py
Issue: #1980
Canonical data: https://github.com/exercism/problem-specifications/tree/master/exercises/robot-simulator
I've changed also method name `simulate` to `move` to follow up canonical data.
=> robot-simulator add test template

exercises/matching-brackets/.meta/template.j2, exercises/matching-brackets/matching_brackets_test.py
=> matching-brackets: add test template (#1959)

exercises/scale-generator/.meta/template.j2, exercises/scale-generator/scale_generator_test.py
=> scale-generator: add test template

exercises/rna-transcription/.meta/template.j2, exercises/rna-transcription/rna_transcription_test.py
=> rna_transcription: add test template

exercises/isbn-verifier/.meta/template.j2, exercises/isbn-verifier/isbn_verifier_test.py
=> isbn-verifier: add test template

exercises/perfect-numbers/.meta/template.j2, exercises/perfect-numbers/perfect_numbers_test.py
Add test template to generate perfect numbers tests from canonical-data.json. Closes #1965
=> perfect-numbers: Add Test Template.

exercises/food-chain/.meta/template.j2, exercises/food-chain/food_chain_test.py
=> food-chain: add test template(#1948)

exercises/raindrops/example.py
Fixed indentation error in example file.
=> raindrops: fix example indentation

exercises/knapsack/.meta/template.j2, exercises/knapsack/knapsack_test.py
=> knapsack: add test template (#1956)

exercises/bob/.meta/template.j2, exercises/bob/bob_test.py
=> bob: add test template

exercises/diamond/.meta/template.j2, exercises/diamond/diamond_test.py
Most of the differences are because I used double quotes instead of single quotes.
=> diamond: add test template

exercises/binary-search-tree/example.py, exercises/change/.meta/template.j2, exercises/change/change_test.py
=> Change: add new test template

exercises/palindrome-products/.meta/hints.md, exercises/palindrome-products/.meta/template.j2, exercises/palindrome-products/README.md, exercises/palindrome-products/palindrome_products_test.py
=> palindrome-products: Add test template

exercises/affine-cipher/.meta/template.j2, exercises/affine-cipher/affine_cipher_test.py
=> affine-cipher: add test template

exercises/pov/.meta/template.j2, exercises/pov/pov_test.py
=> pov: add test template

exercises/flatten-array/.meta/template.j2, exercises/flatten-array/flatten_array_test.py
=> flatten-array: add test template

exercises/darts/.meta/template.j2, exercises/darts/darts_test.py
=> darts: add test template

exercises/all-your-base/.meta/template.j2, exercises/all-your-base/all_your_base_test.py, exercises/all-your-base/example.py
=> all-your-base: add test template

exercises/collatz-conjecture/.meta/template.j2, exercises/collatz-conjecture/collatz_conjecture_test.py
=> collatz-conjecture: add test template

bin/generate_tests.py
removed unused import from generate_tests code
=> Removed unused import

exercises/largest-series-product/.meta/hints.md, exercises/largest-series-product/.meta/template.j2, exercises/largest-series-product/README.md, exercises/largest-series-product/largest_series_product_test.py
=> largest-series-product: add test template

exercises/poker/.meta/template.j2, exercises/poker/poker_test.py
=> poker: add test template (#1968)

exercises/rectangles/.meta/template.j2, exercises/rectangles/rectangles_test.py
=> rectangles: add test template (#1977)

exercises/house/.meta/template.j2, exercises/house/house_test.py
=> house: add test template (#1954)

bin/generate_tests.py
Add more details to generate_tests.py --check failure.
Related: #1958
=> generator: detailed output for --check

exercises/go-counting/.meta/template.j2, exercises/go-counting/go_counting_test.py
=> Go counting add test template

exercises/ocr-numbers/.meta/hints.md, exercises/ocr-numbers/.meta/template.j2, exercises/ocr-numbers/README.md, exercises/ocr-numbers/ocr_numbers_test.py
Resolve #1963 . #2051 seems not to be active so I finished it for them.
=> Add test template for ocr-numbers

exercises/connect/.meta/template.j2, exercises/connect/connect_test.py, exercises/connect/example.py
My IDE suggests some changes to example.py that seems OK to me. I included them as a separate commit.
Are these changes OK for exercism ? Do you want me to create another PR for them ?
Resolves: #1938
=> connect: add test template

bin/check-readmes.sh, exercises/collatz-conjecture/README.md, exercises/complex-numbers/README.md, exercises/diffie-hellman/README.md, exercises/dot-dsl/README.md, exercises/error-handling/README.md, exercises/matrix/README.md, exercises/minesweeper/README.md, exercises/ocr-numbers/README.md, exercises/simple-cipher/README.md, exercises/simple-linked-list/README.md
Also regenerate READMEs that have hints files so CI will pass.
Resolves #2131
Prefer merge commit over squash-merge.
=> Fix hole in CI README check

config/generator_macros.j2, exercises/custom-set/.meta/local_macros.j2, exercises/custom-set/.meta/template.j2, exercises/custom-set/custom_set_test.py
Resolve #1940. The test template is correct but very repetitive. It would be nice if someone can help me refactor it.
- I would like to create a local macros to use in the test template but I don't know how to import it. Can anyone help me?
- How to strip the unnecessary newline?
=> Custom set add test template

docs/GENERATOR.md
Site moved to palletsprojects.com
=> docs: update Jinja link

exercises/phone-number/phone_number.py
Template was created and renamed the class Phone to PhoneNumber... the example.py was already updated, but the slug file was overlooked.
Fixes #2151
=> phone-number: fix ImportError in slug file

config/maintainers.json
Add davidgerva in maintainers list
=> Add davidgerva in maintainers list

exercises/luhn/luhn_test.py
Bump `luhn` to latest version of the canonical data.
Closes #2170
=> [luhn] bump to 1.7.0

exercises/book-store/.meta/template.j2, exercises/book-store/book_store_test.py
Fixes #2172 by updating some variable names to relate to the exercise.
=> [book-store] update template names

bin/fetch-configlet
=> Print configlet download info

config/maintainers.json
Unfortunately, for most of the rest of this year, I'm not able to dedicate the minimum weekly time to help with the v3 drive and maintaining the track, so I'm removing myself as maintainer. Please revoke my GitHub privileges also.
=> Remove `paparomeo` from maintainers.

config/maintainers.json
On second thought @paparomeo what I'll do is mark you as an alumnus here (V2), but remove you from the V3 file. Does that work for you?
Reverts exercism/python#2185
=> Revert "Remove `paparomeo` from maintainers."

.travis.yml, bin/fetch-configlet
Closes #2182.  Also removed dependency on requests module.
=> fetch-configlet: Honor rate limits and errors.

exercises/pangram/.meta/additional_tests.json, exercises/pangram/.meta/template.j2, exercises/pangram/pangram_test.py
Resolves #2190
Closes #2191 by mutual exclusion.
=> pangram: add tests for alphabetical min/max

config/maintainers.json
I would like to add myself to the maintainers list. :)
=> Add J08K (Job van der Wal)

exercises/robot-name/robot_name_test.py
Noticed a small typo in a comment in the test.
=> robot-name: Typo in comment

exercises/phone-number/.meta/additional_tests.json, exercises/phone-number/example.py, exercises/phone-number/phone_number_test.py
=> phone-number: standardize pretty format

.github/workflows/ci-workflow.yml
exercism/problem-specifications is undergoing significant changes; will update and restore these checks as appropriate once the changes there are complete.
=> Temporarily disable generator checks

.github/workflows/ci-workflow.yml
See https://github.com/exercism/github-actions/tree/master/configlet-ci
Thanks @SaschaMann
=> Use configlet-ci action to Fetch configlet

.github/workflows/ci-workflow.yml
Also add blank lines between steps for readability
=> Remove unneeded token for configlet-ci action

.github/workflows/ci-workflow.yml, test/check-exercises.py
- Check for exemplar.py (>=v3), then example.py (<v3)
- See https://github.com/exercism/v3/pull/3086
- Use pathlib instead of os.path
=> Update CI test runner for v3

config.json
Added the following `tags` to the Python track `config.json`:
- "paradigm/imperative",
- "paradigm/object_oriented",
- "paradigm/functional",
- "typing/dynamic",
- "typing/strong",
- "execution_mode/interpreted",
- "platform/windows",
- "platform/mac",
- "platform/linux",
- "runtime/language_specific",
- "used_for/artificial_intelligence",
- "used_for/backends",
- "used_for/cross_platform_development",
- "used_for/embedded_systems",
- "used_for/games",
- "used_for/robotics",
- "used_for/scientific_calculations",
- "used_for/scripts"
=> Added track language tags for Python.

.github/workflows/ci-workflow.yml, bin/generate_tests.py, bin/githelp.py, bin/template_status.py
Closes #2266 by mutual exclusion
=> various tooling improvements

bin/data.py
See https://github.com/exercism/docs/blob/main/anatomy/tracks/config-json.md#key-features
=> add dataclass for config.key_features

exercises/concept/guidos-gorgeous-lasagna/lasagna_test.py, exercises/concept/pretty-leaflet/string_formatting_test.py
Cleaned up some test files for concept exercises:
1.  Added subtests and user-facing error messages for `guidos-gorgeous-lasagna`
2. Added missing configuration entries for `pretty-leaflet` under `.meta/config.json`
3. Corrected the casing of the Classname in `pretty_leaflet_test.py` to conform with PyTest test discovery and Python classname standards.
=> Concept Exercise test files cleanup

.github/ISSUE_TEMPLATE/new_concept_exercise_template.md
Last try for new concept issue template.
=> Last try for issue template

README.md
Updated readme to remove links to outdated documentation.  Put up request/warning to only PR for issues flagged `[help wanted]`.
=> Update README to warn about Repo Re-org

.github/labels.yml
Added a `.yaml` file for the labels we're currently using.
=> Added file for labels used in the repo.

.github/labels.yml
Reformatted file so that strings were double-quoted.
=> [Repo Labels] Re formatted file to quote strings properly.

bin/data.py
Per discussion in:
- https://github.com/exercism/configlet/issues/186
- https://github.com/exercism/configlet/issues/207
=> Default TestCaseTOML.include to True

exercises/concept/chaitanas-colossal-coaster/.meta/config.json, exercises/concept/conditionals/.meta/config.json, exercises/concept/currency-exchange/.meta/config.json, exercises/concept/elyses-enchantments/.meta/config.json, exercises/concept/ghost-gobble-arcade-game/.meta/config.json, exercises/concept/guidos-gorgeous-lasagna/.meta/config.json, exercises/concept/inventory-management/.meta/config.json, exercises/concept/little-sisters-essay/.meta/config.json, exercises/concept/log-levels/.meta/config.json, exercises/concept/making-the-grade/.meta/config.json, exercises/concept/pretty-leaflet/.meta/config.json, exercises/concept/processing-logs/.meta/config.json, exercises/concept/restaurant-rozalynn/.meta/config.json, exercises/concept/tisbury-treasure-hunt/.meta/config.json
Added blurbs for the implemented concept exercises.
=> Added Concept Exercise Blurbs.

exercises/concept/chaitanas-colossal-coaster/.meta/config.json, exercises/concept/conditionals/.meta/config.json, exercises/concept/currency-exchange/.meta/config.json, exercises/concept/elyses-enchantments/.meta/config.json, exercises/concept/ghost-gobble-arcade-game/.meta/config.json, exercises/concept/guidos-gorgeous-lasagna/.meta/config.json, exercises/concept/inventory-management/.meta/config.json, exercises/concept/little-sisters-essay/.meta/config.json, exercises/concept/log-levels/.meta/config.json, exercises/concept/making-the-grade/.meta/config.json, exercises/concept/pretty-leaflet/.meta/config.json, exercises/concept/processing-logs/.meta/config.json, exercises/concept/restaurant-rozalynn/.meta/config.json, exercises/concept/sets/.meta/config.json, exercises/concept/tisbury-treasure-hunt/.meta/config.json
The authors and contributors of exercises are stored in an array of objects in the exercises' `.meta/config.json` files.
Each author/contributor used to have two properties: their GitHub username _and_ their Exercism username.
As we're only using the GitHub username, we're flattening the `authors` and `contributors` array to an array of strings representing the GitHub usernames.
We will update `configlet` to validate the new structure, so you might be seeing build failures once we've implemented this change. 
See https://github.com/exercism/docs/pull/90/files
We will automatically merge this PR immediately to be able to submit a different PR in which we'll add the authors/contributors for practice exercises.
https://github.com/exercism/v3-launch/issues/26
=> 🤖 Flatten authors and contributors in .meta/config.json files

config.json
I'm doing this to trigger the CI, to see if it complains. If we merge, I hope that, if the site doesn't update, we can figure out why.
=> Remove double spaces

concepts/basics/about.md, concepts/basics/introduction.md, exercises/practice/forth/.meta/tests.toml, exercises/practice/forth/forth_test.py
- Cleaned up code comment formatting.
- Separated out some code examples for readability.
- Edited down introduction a bit for clarity.
- Added default parameter code example.
- Cleaned up dead reference links from `introduction.md`
=> Cleaned up about.md & introduction.md for Basics Concept

exercises/concept/guidos-gorgeous-lasagna/.docs/hints.md, exercises/concept/guidos-gorgeous-lasagna/.docs/instructions.md, exercises/concept/guidos-gorgeous-lasagna/.docs/introduction.md, exercises/concept/guidos-gorgeous-lasagna/lasagna.py, exercises/concept/guidos-gorgeous-lasagna/lasagna_test.py
Cleaned up code comment formatting.
Separated out some code examples for readability.
Edited down introduction a bit for clarity.
Added default parameter code example.
Cleaned up dead reference links
=> Edits to Guido's Gorgeous Lasagna Concept Exercise

.github/workflows/ci-workflow.yml, .github/workflows/configlet.yml, .github/workflows/test-runner.yml
=> Revert "Bump actions/checkout from 2 to 2.3.4"

.github/workflows/stale.yml
=> Revert "Bump actions/stale from 3 to 3.0.18"

concepts/loops/.meta/config.json, concepts/loops/about.md, concepts/loops/introduction.md, concepts/loops/links.json
- Added an `about.md` for the `loops` concept.
- Added an `introduction.md` for the loops concept.
- Added `links.json` for the loops concept.
- Added `.meta/config.json` for loops concept.
=> Loops spiffying

concepts/loops/about.md, concepts/loops/introduction.md
Had to clean up a messy merge for loops.  Hopefully this did the trick.
Conflicts resolved:
- `about.md` wile loop code and enumerate examples.
-  `links.json` added Ned Batchelder on looping.
-  `introduction.md` Cleaned up intro paragraph.
=> Loops merge cleanup

concepts/list-methods/about.md, concepts/list-methods/introduction.md
Removed references to "you" and "you will" in docs and made the "voice"  less personal.
=> [Concept List-Methods] Further edited language in about.md and introduction.md.

exercises/concept/little-sisters-essay/.docs/introduction.md
Added string method code examples to the `introduction.md` doc.
=> [Little Sisters Essay (String Methods)] Added code examples to introduction doc.

concepts/strings/about.md
Edited `about.md` file for the `strings` concept.
=> Edited strings about.md file.

exercises/concept/little-sisters-vocab/.docs/introduction.md
Closed code block on line 138.
=> [Little Sisters Vocab] Update introduction.md to close Code Block

config.json
Renamed Elyses Enchantments  --> Card Games, per the exercise folder.
=> Update config.json File

config.json
...or at least I hope I did.  Once more, with feeling.
=> Reduced Practices Arrays to 8 Exercise References per concept.

exercises/concept/ghost-gobble-arcade-game/.meta/config.json, exercises/concept/guidos-gorgeous-lasagna/.meta/config.json, exercises/concept/log-levels/.meta/config.json
I hope you'll forgive me this unsolicited contribution 😉
=> Fix forked_from after exercise renames

exercises/practice/hello-world/hello_world.py
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
=> 🤖 Simplify `hello-world` stub

bin/data.py
Hopefully, this makes the CI check happy.
=> Added Concept Exercise Icon Field to Test Runner `data.py` File

exercises/shared/help.md, exercises/shared/tests.md
Closes #2468 & #2469.
- created `exercises/shared/` directory
- created `help.md`
- created `tests.md`
=> Extract help & test info into shared docs directory

config.json
Added icon references for track features to `config.json`.
=> Added track features icons.

config.json, exercises/concept/little-sisters-essay/.docs/instructions.md, exercises/concept/little-sisters-essay/string_methods.py
As noted in [Issue 2479](https://github.com/exercism/python/issues/2479) and in V3-beta [Issue #158](https://github.com/exercism/v3-beta/issues/158), a method was mis-named in the instructions, and two parameters were swapped in the stub file.
Closes #2479 and https://github.com/exercism/v3-beta/issues/158
=> Fix Little Sister's Essay Issues

exercises/concept/making-the-grade/.docs/hints.md
This hopefully fixes https://github.com/exercism/website/issues/1435
=> Remove empty hint items from making-the-grade

concepts/bools/about.md, concepts/bools/introduction.md, exercises/concept/ghost-gobble-arcade-game/.docs/hints.md, exercises/concept/ghost-gobble-arcade-game/.docs/instructions.md, exercises/concept/ghost-gobble-arcade-game/.docs/introduction.md, exercises/concept/ghost-gobble-arcade-game/.meta/config.json, exercises/concept/ghost-gobble-arcade-game/.meta/design.md, exercises/concept/ghost-gobble-arcade-game/arcade_game.py
Went through the docs for the `bools` concept & `Ghost Gobble Arcade Game` concept exercise, editing for the following:
Also added more formal docstrings to the stub file.
=> Bools  and Ghost-Gobble Arcade Game Typos and Revisions

concepts/string-methods/.meta/config.json, concepts/string-methods/about.md, concepts/string-methods/introduction.md, concepts/string-methods/links.json, concepts/strings/about.md, concepts/strings/introduction.md, exercises/concept/little-sisters-essay/.docs/instructions.md, exercises/concept/little-sisters-essay/.docs/introduction.md, exercises/concept/little-sisters-essay/.meta/exemplar.py, exercises/concept/little-sisters-essay/string_methods.py, exercises/concept/little-sisters-essay/string_methods_test.py, exercises/concept/little-sisters-vocab/.docs/instructions.md, exercises/concept/little-sisters-vocab/.docs/introduction.md, exercises/concept/little-sisters-vocab/.meta/exemplar.py, exercises/concept/little-sisters-vocab/strings.py, exercises/concept/little-sisters-vocab/strings_test.py
Went through the docs for  the `strings` & `string-methods` concepts and the corresponding `Little Sister's Essay` & `Little Sister's Vocab` concept exercises, editing for the following:
Also added more formal docstrings to the `exemplar.py` and stub files for each exercise.
=> Strings and String-Methods (Little Sister's Essay & Little Sister's Vocab) Typos & Revisions

concepts/list-methods/about.md, concepts/list-methods/introduction.md, concepts/lists/.meta/config.json, concepts/lists/about.md, concepts/lists/introduction.md, exercises/concept/card-games/.docs/hints.md, exercises/concept/card-games/.docs/instructions.md, exercises/concept/card-games/.docs/introduction.md, exercises/concept/card-games/.meta/exemplar.py, exercises/concept/card-games/lists.py, exercises/concept/card-games/lists_test.py, exercises/concept/chaitanas-colossal-coaster/.docs/hints.md, exercises/concept/chaitanas-colossal-coaster/.docs/instructions.md, exercises/concept/chaitanas-colossal-coaster/.docs/introduction.md, exercises/concept/chaitanas-colossal-coaster/.meta/config.json, exercises/concept/chaitanas-colossal-coaster/.meta/design.md, exercises/concept/chaitanas-colossal-coaster/.meta/exemplar.py, exercises/concept/chaitanas-colossal-coaster/list_methods.py
Went through the docs for  the `lists` & `list-methods` concepts and the corresponding `Card Games` & `Chiatanas Colossal Coaster` concept exercises, editing for the following:
Also added more formal docstrings to the stub files for each exercise.
=> Lists & List-Methods (Card Games & Chiatanas Colossal Coaster) Typos and Revisions

exercises/concept/cater-waiter/.meta/exemplar.py, exercises/concept/cater-waiter/sets.py
Fixed code in `exemplar.py`, to conform to Pylint nagging and resolve a parameter bug. 
Added docstrings to `exemplar.py` file.
Cleaned up stub file
=> Sets and Cater-Waiter Fixes

exercises/concept/card-games/lists.py, exercises/concept/chaitanas-colossal-coaster/.meta/exemplar.py, exercises/concept/chaitanas-colossal-coaster/list_methods.py
=> Added docstrings & Cleaned up stub files/exemplars 

exercises/concept/guidos-gorgeous-lasagna/lasagna.py
In `lasagna.py` -- stub solution file for `guidos gorgeous lasagna` concept exercise.
=> Added missing TODO for 'PREPARATION_TIME' constant.

exercises/concept/inventory-management/.meta/exemplar.py, exercises/concept/inventory-management/dicts.py
Added docstrings to `Inventory Management` (dicts) stub file and `exemplar.py`.
=> Added docstrings to exemplar and stub files for Inventory Management Exercise

exercises/concept/making-the-grade/.meta/exemplar.py, exercises/concept/making-the-grade/loops.py, exercises/concept/meltdown-mitigation/.meta/exemplar.py, exercises/concept/meltdown-mitigation/conditionals.py, exercises/concept/meltdown-mitigation/conditionals_test.py, exercises/concept/restaurant-rozalynn/.meta/exemplar.py, exercises/concept/restaurant-rozalynn/none.py, exercises/concept/tisbury-treasure-hunt/.meta/exemplar.py, exercises/concept/tisbury-treasure-hunt/tuples.py
Spell checked, edited per PyLInt, and added docstrings to the stub and exemplar files for these concept exercises:
- `Meltdown Mitigation` (conditionals)
- `Making the Grade` (loops)
- `Tisbury Treasure Hunt` (tuples)
- `Restaurant Rosalynn` (None)
=> Stub and Exemplar file Corrections and Docstrings

docs/ABOUT.md
=> Refreshed and Revised ABOUT.md for track.

docs/INSTALLATION.md
=> Updated INSTALLATION docs.

docs/RESOURCES.md
=> Refreshed RESOURCES.md

exercises/shared/.docs/help.md, exercises/shared/.docs/tests.md
=> Revised and refreshed help.md and tests.md.

docs/ABOUT.md, exercises/concept/making-the-grade/.docs/hints.md
Fixed broken links and refs in hints file.
=> Making the mini fix

exercises/concept/card-games/.docs/instructions.md, exercises/concept/card-games/.meta/exemplar.py, exercises/concept/card-games/lists.py
Fix issue #2528:
- fix return types and descriptions in docstrings,
- capitalize Boolean
=> Card-Games: Fix return types and descriptions in the docstring

exercises/concept/making-the-grade/.docs/instructions.md, exercises/concept/making-the-grade/loops_test.py
Closing issue #2532 
- Changed `ints` to `int`s
- Added slashes before `<` and `>` to display them properly
-  Changed "No perfect scores." to "No perfect score." in instructions
- Removed one element from the scores list in **test_student_ranking** to make it's length even with names list
=> Fixed 'making-the-grade' (#2532)

config.json
Closes #2542 
Need to remove these three exercises from the site right now Their missing prerequisites are causing confusion.
=> Remove pretty-leaflet, restaurant-rozalynn, and log-levels 

concepts/basics/about.md, concepts/basics/introduction.md, exercises/concept/guidos-gorgeous-lasagna/.docs/hints.md, exercises/concept/guidos-gorgeous-lasagna/.docs/instructions.md, exercises/concept/guidos-gorgeous-lasagna/.docs/introduction.md, exercises/concept/guidos-gorgeous-lasagna/.meta/exemplar.py, exercises/concept/guidos-gorgeous-lasagna/lasagna.py, exercises/concept/guidos-gorgeous-lasagna/lasagna_test.py
=> Fix for Issue 2540:  PEP257 Changes in Guidos Gorgeous Lasagna 

config.json
Removed the prerequisites from all exercises that were flagged  `"deprecated"` in the track `config.json`.
=> Removed prerequisite listings from depricated exercises.

exercises/concept/restaurant-rozalynn/.docs/instructions.md, exercises/concept/restaurant-rozalynn/.meta/exemplar.py, exercises/concept/restaurant-rozalynn/none.py, exercises/concept/restaurant-rozalynn/none_test.py
For `Restaurant Rozalynn` (none) concept exercise, needed to do the following cleanup:
=> [Restaurant Rozalynn] Docstring, document, and code changes to conform to Pylinting.

exercises/concept/guidos-gorgeous-lasagna/lasagna.py
A few extra comments, addresses #2576.
=> Explain `PREPARATION_TIME` in `guidos-gorgeous-lasagna`

config.json, exercises/concept/pretty-leaflet/.docs/hints.md, exercises/concept/pretty-leaflet/.docs/instructions.md, exercises/concept/pretty-leaflet/.meta/design.md, exercises/concept/pretty-leaflet/.meta/exemplar.py, exercises/concept/pretty-leaflet/string_formatting.py, exercises/concept/pretty-leaflet/string_formatting_test.py
From issue #2438, I removed the use of `classes` and replaced them with 4 functions instead. I kept the same tasks with some minor changes.
=> Pretty leaflet fixes

exercises/concept/meltdown-mitigation/.docs/instructions.md
=> Fix a typo in `meltdown-mitigation` instructions

exercises/concept/meltdown-mitigation/conditionals.py
It was slightly misaligned without this.
=> Fix typo in docstring

exercises/concept/meltdown-mitigation/.docs/instructions.md
Small fixes to markdown to correct rendering issues in instruction pane in UI.
=> [Meltdown Mitigation]: Small Markdown Highlight fixes

exercises/concept/little-sisters-vocab/.docs/instructions.md
Found this complaint in one of the mysterious bug submissions that we just received :)
=> Fix fittle sister's vocab instructions typo

exercises/concept/card-games/.docs/instructions.md
=> Change Phrasing of Task 5 To Clarify Return

exercises/concept/meltdown-mitigation/.docs/instructions.md, exercises/concept/meltdown-mitigation/.meta/exemplar.py, exercises/concept/meltdown-mitigation/conditionals.py, exercises/concept/meltdown-mitigation/conditionals_test.py
Addresses #2585.
Everything still makes logical sense (as explained in the referenced issue) but due to preceding PRs I had to slightly change tests as well.
=> Adjust task 3 of `meltdown-mitigation`

exercises/concept/guidos-gorgeous-lasagna/lasagna_test.py
The `ImportError` messages were awkward, and needed a bit of rephrasing.  Should be fixed now.
=> [Guido's Gorgeous Lasagna] Changed ImportError messaging to be less awkward.

.github/workflows/pr-commenter.yml
The new PR-Commenter for the repo, codename: `Porcupine Revenger`. Made together with @BethanyG ❤️
Splitting this into two parts, for sharing of REP purposes.
Required files have been merged in #2707.
=> [New Workflow] PR-Commenter Part 1/2

exercises/concept/making-the-grade/.docs/instructions.md
There is a mistaken space before the colon in the instructions
Please rename the PR commit to whatever you (would) normally write
=> Docs: align task 5 instructions with tests

exercises/concept/little-sisters-essay/.meta/exemplar.py, exercises/concept/little-sisters-essay/string_methods.py
=> Fix little sisters essay parameter order

exercises/practice/transpose/.meta/template.j2, exercises/practice/transpose/.meta/tests.toml, exercises/practice/transpose/transpose_test.py
=> [Transpose]: Update from Problem Specifications

exercises/practice/tournament/.meta/template.j2, exercises/practice/tournament/.meta/tests.toml, exercises/practice/tournament/tournament_test.py
=> [Tournament]: Update from Problem Specifications

exercises/practice/sublist/.docs/instructions.md, exercises/practice/sublist/.meta/template.j2, exercises/practice/sublist/.meta/tests.toml, exercises/practice/sublist/sublist_test.py
=> [Sublist]: Update from Problem Specifications

exercises/practice/resistor-color-duo/.docs/instructions.md, exercises/practice/resistor-color-duo/.meta/template.j2, exercises/practice/resistor-color-duo/.meta/tests.toml, exercises/practice/resistor-color-duo/resistor_color_duo_test.py
=> [Resistor-Color-Duo]: Update from Problem Specifications

exercises/practice/rational-numbers/.docs/instructions.md, exercises/practice/rational-numbers/.meta/tests.toml, exercises/practice/rational-numbers/rational_numbers_test.py
=> [Rational-Numbers]: Update from Problem Specifications

exercises/practice/prime-factors/.docs/instructions.md, exercises/practice/prime-factors/.meta/template.j2, exercises/practice/prime-factors/.meta/tests.toml, exercises/practice/prime-factors/prime_factors.py, exercises/practice/prime-factors/prime_factors_test.py
=> [Prime-Factors]: Update from Problem Specifications

exercises/practice/markdown/.meta/template.j2, exercises/practice/markdown/.meta/tests.toml, exercises/practice/markdown/markdown_test.py
=> [Markdown]: Update from Problem Specifications

exercises/practice/luhn/.docs/instructions.md, exercises/practice/luhn/.meta/template.j2, exercises/practice/luhn/.meta/tests.toml, exercises/practice/luhn/luhn.py, exercises/practice/luhn/luhn_test.py
=> [Luhn]: Update from Problem Specifications

exercises/practice/kindergarten-garden/.meta/template.j2, exercises/practice/kindergarten-garden/.meta/tests.toml, exercises/practice/kindergarten-garden/kindergarten_garden_test.py
=> [Kindergarten-Garden]: Update from Problem Specifications

exercises/practice/isogram/.docs/instructions.md, exercises/practice/isogram/.meta/template.j2, exercises/practice/isogram/.meta/tests.toml, exercises/practice/isogram/isogram_test.py
=> [Isogram]: Update from Problem Specifications

exercises/practice/high-scores/.meta/example.py, exercises/practice/high-scores/.meta/template.j2, exercises/practice/high-scores/.meta/tests.toml, exercises/practice/high-scores/high_scores.py, exercises/practice/high-scores/high_scores_test.py
Re-wrote `example.py` to pass new tests.
Updated stub file with new function names.
=> [High-Scores]: Update from Problem Specifications

exercises/practice/hamming/.docs/instructions.md, exercises/practice/hamming/.meta/tests.toml, exercises/practice/hamming/hamming_test.py
=> [Hamming]: Update from Problem Specifications

exercises/practice/grade-school/.docs/instructions.md, exercises/practice/grade-school/.meta/example.py, exercises/practice/grade-school/.meta/template.j2, exercises/practice/grade-school/.meta/tests.toml, exercises/practice/grade-school/grade_school_test.py
Pulled down updates from problem-specifications. 
Updated Jinja2 template & regenerated test file. 
Re-wrote `example.py` to pass new tests.
=> [Grade-School]: Update from Problem Specifications

exercises/practice/anagram/.meta/tests.toml, exercises/practice/anagram/anagram_test.py
Pulled down updates from problem-specifications.  
=> [Anagram] : Update from Problem Specifications

exercises/practice/change/.meta/tests.toml, exercises/practice/change/change_test.py
=> [Change]: Update from Problem Specifications

exercises/practice/complex-numbers/.docs/instructions.md, exercises/practice/complex-numbers/.meta/example.py, exercises/practice/complex-numbers/.meta/template.j2, exercises/practice/complex-numbers/.meta/tests.toml, exercises/practice/complex-numbers/complex_numbers_test.py
Updated `example.py` to pass new tests.
=> [Complex-Numbers]: Update from Problem Specifications

exercises/practice/diffie-hellman/.meta/template.j2, exercises/practice/diffie-hellman/.meta/tests.toml, exercises/practice/diffie-hellman/diffie_hellman_test.py
=> [Diffie-Hellman]: Update from Problem Specifications

exercises/practice/forth/.meta/tests.toml, exercises/practice/forth/forth_test.py
=> [Forth]: Update from Problem Specifications

CONTRIBUTING.md
=> Updated pre-commit checklist as per issue 2700.

exercises/concept/currency-exchange/.docs/hints.md, exercises/concept/tisbury-treasure-hunt/.docs/hints.md
Changed the hint titles to match the instruction task titles so they would show on the website.
=> [Currency Exchange & Tisbury]:  Fixed Hint Files

.github/issue-comment.md, .github/pr-commenter.yml, CONTRIBUTING.md, README.md
Fixes issue #2760 
Added to: 
`CONTRIBUTING`
`README`
issue auto-responder text
PR auto-repsonder text
Also tidied up the issue auto-responder text a bit.
=> [🤖 Auto-Responders 🤖 ]: Added Links to New "How to Make a Good PR" Docs

docs/TESTS.md
Part of the review for PR 2776.
=> [TESTING Docs]: Added intro and a few suggestions.

docs/TESTS.md, docs/TOOLS.md, docs/config.json
This would fix both #2721 and #2726. Also I cleaned up the docs a little bit and fixed some weird stuff and did a spell check.
=> [Docs]: Cleanup, Push to site, and Spell check

exercises/practice/markdown/markdown.py
Hi! I found out that after changes in https://github.com/exercism/python/pull/2753 3 tests didn't pass despite of the task statement:
> Even though this code is confusingly written and hard to follow, somehow it works and all the tests are passing!
This PR fixes this and adds required conditions.
Signed-off-by: Jasstkn <jasssstkn@yahoo.com>
=> [Markdown]: Fix markdown stub code to pass newly added tests

exercises/practice/twelve-days/.meta/template.j2, exercises/practice/twelve-days/twelve_days_test.py
=> [Twelve-Days]:  Add Note to Test File Warning about Implicit Line Joining in Results Lists

exercises/concept/making-the-grade/.docs/instructions.md, exercises/concept/making-the-grade/loops.py
=> [Making the Grade]: Clarified Grading Intervals & Added Detail to Examples for  Task 4

.github/pr-commenter.yml
=> [PR Auto-Comments]: Will the teeny-tiny typo madness never end??

exercises/practice/darts/.meta/example.py, exercises/practice/diffie-hellman/.meta/example.py, exercises/practice/dnd-character/.meta/example.py, exercises/practice/dominoes/.meta/example.py, exercises/practice/dot-dsl/.meta/example.py, exercises/practice/error-handling/.meta/example.py, exercises/practice/etl/.meta/example.py, exercises/practice/food-chain/.meta/example.py, exercises/practice/forth/.meta/example.py
=> [Linting]: Lint practice stub files (3 / ?)

exercises/practice/prime-factors/prime_factors.py
The solution for this exercise was left in the stub file by accident.  Fixes #2796.
=> [Prime Factors]: Solution left in Stub File

exercises/practice/queen-attack/.meta/example.py, exercises/practice/rail-fence-cipher/.meta/example.py, exercises/practice/rational-numbers/.meta/example.py, exercises/practice/rational-numbers/rational_numbers.py, exercises/practice/react/.meta/example.py, exercises/practice/rectangles/.meta/example.py, exercises/practice/rest-api/.meta/example.py, exercises/practice/rna-transcription/.meta/example.py, exercises/practice/robot-name/.meta/example.py, exercises/practice/robot-simulator/.meta/example.py, exercises/practice/robot-simulator/robot_simulator.py, exercises/practice/roman-numerals/.meta/example.py, exercises/practice/rotational-cipher/.meta/example.py, exercises/practice/run-length-encoding/.meta/example.py
Hopefully fixes rebase conflicts in #2793.
=> [Linting]: Lint practice stub files (6 / ?)

.github/issue-comment.md, .github/pr-commenter.yml
Let's really hope this fixes stuff and DOESN'T have rebase issues. 💙 Love you git 💙
=> [Automation]: Fixing some bots :P

exercises/practice/saddle-points/.meta/example.py, exercises/practice/satellite/.meta/example.py, exercises/practice/say/.meta/example.py, exercises/practice/scale-generator/.meta/example.py, exercises/practice/scale-generator/scale_generator.py, exercises/practice/secret-handshake/.meta/example.py, exercises/practice/series/.meta/example.py, exercises/practice/sgf-parsing/.meta/example.py, exercises/practice/sieve/.meta/example.py, exercises/practice/simple-cipher/.meta/example.py, exercises/practice/simple-linked-list/.meta/example.py, exercises/practice/space-age/.meta/example.py, exercises/practice/spiral-matrix/.meta/example.py, exercises/practice/strain/.meta/example.py, exercises/practice/sublist/.meta/example.py
=> [Linting]: Lint practice stub files (7 / 8)

exercises/concept/little-sisters-vocab/.docs/instructions.md
Corrected "a adjective" to "an adjective"
=> Update typo in instructions.md

exercises/concept/chaitanas-colossal-coaster/.docs/instructions.md
Added indication about what value should be returned by the functions.
Note/Opinion: Some sentences indicates the return value as the ending action after a bullet list, in others the information is mixed in the phrase; while this makes it more 'casual' or friendly, it could confuse the reader who's at the start of his/her programming journey
=> Add indication of return values

concepts/functions/.meta/config.json, concepts/functions/about.md, concepts/functions/introduction.md, concepts/functions/links.json
Adding functions `concept`, as discussed in #2353
=> [New Concept] : functions

exercises/concept/card-games/.docs/instructions.md, exercises/concept/card-games/.meta/exemplar.py, exercises/concept/card-games/lists.py, exercises/concept/card-games/lists_test.py
I would like to apologize to the lovey @BethanyG, for me being wayyy to late with this. 💙 
Anyway... This should close #2625.
**Note: I also re-formatted the test file to make them a little more read-able.**
=> [Card Games]: Exercise Improvements

exercises/concept/currency-exchange/.docs/instructions.md
Removing extra whitespace in exercise instructions.
=> docs: remove whitespace

exercises/concept/cater-waiter/sets_test.py
=> [Cater Waiter]Tests: Modified subtest headlines to omit test data for brevity.

exercises/practice/yacht/yacht.py
=> [Yacht] Removed Deprecated Python 2.x Stub Note

exercises/concept/tisbury-treasure-hunt/.docs/hints.md
Hints for task 5 being dropped on site.
=> [Tisbury Treasure Hunt] Correct Mis-Match Between Hint Title & Task Title

exercises/concept/inventory-management/.docs/hints.md
Change the hint titles to match the titles in instructions.md
=> [Inventory Management] Update hints.md

exercises/practice/complex-numbers/.docs/instructions.append.md
Since this track uses Python 3, maybe it would be better to reference the docs for the Python 3.
=> [Complex Numbers] Update Hints link from Python 2 to Python 3 Docs

exercises/concept/black-jack/.docs/instructions.md
I was working on this exercise, and I found it confusing that it is not mentioned whether it is possible to already have an ace in hand, and if that was the case, what should be it's value. So I checked the test file and i saw that one example has an Ace in it and that it behaves as an 11,so,for clarification, I added a hint that initial Aces in hand should be considered as 11.
=> Update instructions.md of the python Black-jack exercice

concepts/numbers/introduction.md
Attempting to clarify the difference between an int and a float by defining precision. Adding a section outlining the use of underscores in numeric literals.
First attempt at a PR clarifying the documentation around the numbers concept. Keep PRs small while I learn exercism best practices
=> Updating the the concept introduction for numbers

concepts/numbers/introduction.md
This pull requests makes a grammatical correction described in issue #2878.
=> Make grammatical correction to the numbers intro page

exercises/practice/bowling/.meta/config.json
Invited to add my name by @BethanyG (ref: [PR 2840](https://github.com/exercism/python/pull/2840)), though it honestly feels like my contribution was pretty minor!
=> Bowling: Add RNeilsen to contributors list

exercises/concept/tisbury-treasure-hunt/.docs/instructions.md
Changed table heading "Quandrant" to "Quadrant" according to  #2895
=> [Tisbury Treasure Hunt] Corrected spelling mistake in the introduction

exercises/practice/hello-world/.docs/instructions.md
I get lots of people confused specifically on Python's hello world because it asks people to write a function, whereas in reality they just need to change the existing code. This brings Python in line with other tracks and will hopefully reduce the volume of emails I get!
=> Bring hello-world in line with problem-specs

concepts/strings/.meta/config.json
moved the "," and deleted whitespace   #2902
=> [Strings] Corrected typo

exercises/practice/kindergarten-garden/.docs/instructions.append.md
Adds track-specific details:
* Explain interface expected by tests.
* Link to Python docs for classes, constructors, and default parameters.
For Issue #2856
=> [Kindergaten Garden] Add explanation of Python specific details

concepts/list-methods/.meta/config.json
Remove unnecessary Quotation mark in blurb of "List Methods" #2922
=> [List Methods] Remove unnecessary Quotation mark in blurb

exercises/concept/meltdown-mitigation/.docs/instructions.md, exercises/concept/meltdown-mitigation/.meta/exemplar.py, exercises/concept/meltdown-mitigation/conditionals.py
As requested in issue #2918 updated temperature with units (kelvin).
=> meltdown-mitigation: Add unit of measure for temperature (#2918)

exercises/concept/meltdown-mitigation/conditionals_test.py
=> [Meltdown Mitigation]: Space on line 69 in test.

exercises/concept/ellens-alien-game/classes.py, exercises/concept/ellens-alien-game/classes_test.py
The function `new_alien_list()` was renamed to `new_aliens_collection()`.  
This PR changes the initial solution and the error message accordingly.
=> Fix: update old name new_alien_list

exercises/concept/black-jack/black_jack_test.py, exercises/concept/card-games/.docs/instructions.md
Just a few spacing and newline fixes as per title.
=> [Black Jack]: Some spacing and consistency fixes in test.

exercises/concept/card-games/.docs/instructions.md, exercises/concept/making-the-grade/.meta/exemplar.py, exercises/concept/making-the-grade/loops.py
Consistent with other code files in concepts that include a docstring
=> Making the Grade: Added newlines in code file docstrings

exercises/concept/making-the-grade/loops.py
I missed this one when doing the code review
=> Making the Grade: stub and exemplar docstring mismatch

exercises/practice/hamming/.meta/tests.toml, exercises/practice/hamming/hamming_test.py
Corrected `test.toml` file.  Regenerated `hamming_test.py` file for hamming exercise.
Closes #2948.
=> Fix for Issue 2948:  Hamming

exercises/concept/card-games/.meta/exemplar.py, exercises/concept/card-games/lists.py
- Continuation changes based on #2947.
=> [Card Games]: Added summary first line sentences to docstrings

exercises/concept/card-games/.meta/exemplar.py, exercises/concept/card-games/lists.py
=> [Card Games]: Imperative mood for docstring start

exercises/concept/ellens-alien-game/.meta/exemplar.py, exercises/concept/ellens-alien-game/classes.py, exercises/concept/ellens-alien-game/classes_test.py
- Changed test for task number 2 to check if health value is in a set of values, rather than one value.
- Changed Stub file docstring.
- Changed Exemplar file to include a note about two viable solutions for hit method task, and added docstrings.
=> [Ellens Alien Game] Per discussion in issue 2954, Updated Tests for Task 2 and Code Files

exercises/concept/ellens-alien-game/.docs/hints.md
Add a hint to #7 to put new_aliens_collection() outside of the Alien class.
=> [Ellen's Alien Game] Update hints.md

exercises/practice/darts/.docs/hints.md
General hints do not appear to support either reflink nor nested bullets, so I re-arranged the file to omit them.
=> [Darts]: Fixes for reflinks and nested bullets

.gitignore, exercises/practice/meetup/.meta/additional_tests.json, exercises/practice/meetup/.meta/example.py, exercises/practice/meetup/.meta/template.j2, exercises/practice/meetup/meetup_test.py
Fixes #3005
Modified the necessary files and regenerated the test files.  Tested against the new example.py,  passing all 103 test.
=> [Meetup] Fixes Issue #3005 Descriptors for Week of Month not matching

exercises/practice/word-count/.docs/hints.md
This is a first pass test of a potential hints.md file for word-count.
Since V3 hints for practice exercises is new, we're going to pilot them with this file.
=> First pass at a hints.md file for Word-Count.

concepts/functools/.meta/config.json
- Added blurb
- Added Tarun193 as Author and moved BethanyG and cmccandless to contributors.
=> [Functools Concept]:Update Contributors & Blurb

config.json
Closes #2985 
Adjusts the prerequisites of the `Clock` exercise to add `classes` to them.
=> [Clock] Added `classes` as a Prerequisite

docs/TOOLS.md
=> [TOOLS.md]: Formatting updates

exercises/practice/gigasecond/.docs/hints.md, exercises/practice/gigasecond/.docs/instructions.append.md
=> Gigasecond adding hints and appending instructions

docs/TOOLS.md
For future reference: https://exercism.org/docs/building/markdown/markdown
=> admonition typo.

exercises/practice/yacht/.meta/tests.toml, exercises/practice/yacht/yacht_test.py
=> [Yacht]: Synced Exercise to Problem Specifications

exercises/practice/word-count/.meta/tests.toml, exercises/practice/word-count/word_count_test.py
=> [Word Count]: Synced Exercise to Problem Specifications

exercises/practice/phone-number/.meta/tests.toml, exercises/practice/phone-number/phone_number_test.py
=> [Phone Number]: Synced Exercise to Problem Specifications

exercises/practice/allergies/.meta/tests.toml, exercises/practice/allergies/allergies_test.py
=> [Allergies]: Synced Exercise to Problem Specifications

exercises/practice/isbn-verifier/.docs/instructions.md, exercises/practice/isbn-verifier/.meta/tests.toml, exercises/practice/isbn-verifier/isbn_verifier_test.py
=> [ISBN-Verifier]: Synced Exercise to Problem Specifications

exercises/practice/twelve-days/.docs/hints.md, exercises/practice/twelve-days/.docs/instructions.append.md
First draft of suggested additions.
=> Twelve Days: add instructions.append and hints

exercises/practice/gigasecond/.docs/hints.md
The two first-level headers was breaking website display and the hints 💡 and hints file were not displaying.
=> Correct 2nd-Level Header So Website Display Works

exercises/concept/ellens-alien-game/.docs/instructions.md, exercises/concept/ellens-alien-game/classes.py, exercises/concept/ellens-alien-game/classes_test.py
=> [Ellens Alien Game]: Error Message & Instructions Clarification (Issue 2992)

concepts/function-arguments/.meta/config.json, concepts/function-arguments/links.json
=> [Fuction-Arguments]: Updated `links.json`. Added blurb and authors to `config.json`

concepts/functions/.meta/config.json, concepts/functions/links.json
=> [Functions]: Config and Info Updates

concepts/recursion/.meta/config.json, concepts/recursion/links.json
=> [Recursion]: Added links in `links.json` and  added bethanyg to contributors

bin/generate_tests.py
See https://github.com/pallets/jinja/issues/767 for the reason why this workaround was necessary.
JinJa2 was failing to "find" the test generation templates due to not understanding Windows file paths.
While this was not _technically_ a bug in our test generator, it did prevent the script from successfully running on Windows.
Tests now successfully run on Windows 10 pro, was unable to test on Windows 11.
=> [Test Generator]: Added  jinja2 `systemfileloader` Workaround for Windows Paths.

exercises/practice/grade-school/.meta/config.json, exercises/practice/high-scores/.docs/instructions.md
=> [High Scores & Grade School]:  Synced to Problem Specifications

concepts/decorators/.meta/config.json, concepts/decorators/introduction.md, concepts/decorators/links.json
Improve docs for Decorators concept
Related issue: #3120
=> Improve docs for Decorators concept

exercises/practice/triangle/.meta/tests.toml, exercises/practice/triangle/triangle_test.py
=> [Triangle]: Synced New Test Cases & Regenerated Test File.

exercises/practice/palindrome-products/palindrome_products_test.py, exercises/practice/poker/poker_test.py
Ran the generator - changes came out the other end.
=> Regenerate Tests

exercises/concept/cater-waiter/.docs/instructions.md, exercises/concept/cater-waiter/sets.py
Fix `dish_ingredients` param type on `categorize_dish` docstring as described in issue #3186
=> [Cater Waiter] Fix dish_ingredients type on categorize_dish docstring

exercises/practice/bob/.approaches/answer-list/content.md, exercises/practice/bob/.approaches/answer-list/snippet.txt, exercises/practice/bob/.approaches/if-statements-nested/content.md, exercises/practice/bob/.approaches/if-statements-nested/snippet.txt, exercises/practice/bob/.approaches/if-statements/content.md, exercises/practice/bob/.approaches/if-statements/snippet.txt, exercises/practice/bob/.approaches/introduction.md, exercises/practice/bob/.articles/performance/code/Benchmark.py
Fixes
- snake case names
- removes leading underscore and private info
- adds info on tuples
=> Bob approaches fixes

CONTRIBUTING.md, README.md
- Updated the Python track README and CONTRIBUTING docs to reflect the community pause.
- Added a badge for Discourse
- Added a badge for PAUSE (with link to blog post)
- Added in-test links and notes for pause and forum
- Updated the Python versions and other typos, etc.
=> Contributing and README Updated for Contribution Pause

exercises/practice/bob/.approaches/if-statements-nested/content.md, exercises/practice/bob/.approaches/if-statements-nested/snippet.txt, exercises/practice/bob/.approaches/introduction.md, exercises/practice/bob/.articles/performance/code/Benchmark.py
Removed a superfluous `else` from the nested `if` statements approach.
=> Bob approaches tweak

exercises/practice/linked-list/.docs/instructions.apped.md, exercises/practice/linked-list/.meta/additional_tests.json, exercises/practice/linked-list/.meta/config.json, exercises/practice/linked-list/.meta/example.py, exercises/practice/linked-list/.meta/template.j2, exercises/practice/linked-list/.meta/tests.toml, exercises/practice/linked-list/linked_list_test.py
=> [Maintenance]: Update linked-list

exercises/practice/wordy/.approaches/dunder-getattribute/content.md
Changed `This concept is also aparat of` to `This concept is also a part of`.
=> wordy-approach-typo-fix

exercises/practice/sgf-parsing/.meta/config.json, exercises/practice/sgf-parsing/.meta/example.py, exercises/practice/sgf-parsing/.meta/template.j2, exercises/practice/sgf-parsing/.meta/tests.toml, exercises/practice/sgf-parsing/sgf_parsing_test.py, requirements-generator.txt
Creating a PR per my conversation with @BethanyG
=> Update SGF Parsing template, tests and escape function

exercises/practice/dnd-character/.meta/template.j2, exercises/practice/dnd-character/dnd_character.py, exercises/practice/dnd-character/dnd_character_test.py
This pr is a suggestion for some changes for dnd-character.
That includes:
- Using `assertTrue(<something>)` instead of `assertIs(<something>, True)`
- Use a macro to follow other jinja templates and removed macro footer
- Also that the modifier function is given
=> [dnd-character]: minor improvments

exercises/practice/palindrome-products/.meta/tests.toml, exercises/practice/palindrome-products/palindrome_products_test.py, exercises/practice/phone-number/.docs/instructions.append.md, exercises/practice/phone-number/.meta/example.py, exercises/practice/phone-number/.meta/tests.toml, exercises/practice/phone-number/phone_number_test.py, exercises/practice/resistor-color-trio/.docs/instructions.md, exercises/practice/resistor-color-trio/.meta/example.py, exercises/practice/resistor-color-trio/.meta/tests.toml, exercises/practice/resistor-color-trio/resistor_color_trio_test.py, exercises/practice/roman-numerals/roman_numerals_test.py
* Palindrome Products (toml and tests)
* Roman Numerals (tests)
* Phone Number (toml, tests, and example solution)
* Resistor Color Trio (intro, toml, tests, and example solution)
=> Updated Exercise docs, toml files, test files and example solutions

concepts/basics/about.md, concepts/basics/introduction.md, concepts/basics/links.json, exercises/concept/guidos-gorgeous-lasagna/.docs/hints.md, exercises/concept/guidos-gorgeous-lasagna/.docs/instructions.md, exercises/concept/guidos-gorgeous-lasagna/.docs/introduction.md, exercises/concept/guidos-gorgeous-lasagna/lasagna.py
Edits and clarifications in line with comments from [this forum thread](http://forum.exercism.org/t/i-am-struggling-with-the-lasagna-exercise/2091/27).
Combined with #3339 and [python-test-runner #110](https://github.com/exercism/python-test-runner/pull/110), this should wrap up the "revamp" of this exercise.
**Edited to add**
Edits to the corresponding concept `introduction.md` (it is now a copy of the exercise introduction), `about.md`, and `links.md` (shortened the list, but might need more shortening).
=> [Lasagna] Rewrites & Clarification to Introduction, Instructions, and Stub File

exercises/practice/pascals-triangle/.docs/instructions.md, exercises/practice/pascals-triangle/.meta/config.json
Synced Pascals Triangle to Problem Specs.
=> [Pascals Triangle] Synced Instructions & Metadata from Problem Specs.

exercises/practice/matching-brackets/.docs/instructions.md, exercises/practice/say/.docs/instructions.md, exercises/practice/simple-cipher/.docs/instructions.md, exercises/practice/space-age/.docs/instructions.md
Synced Instructions for the following exercises:
- `matching-brackets`
- `say`
- `simple-cipher`
- `space-age`
=> [Multiple Exercises] Synced instructions.md from problem specifications.

exercises/practice/poker/.meta/config.json, exercises/practice/spiral-matrix/.meta/config.json
Synced exercise metadata for the following exercises:
- poker
- spiral-matrix
=> [Multiple Exercises] Sync metadata with problem specs.

exercises/practice/rotational-cipher/.approaches/introduction.md
One of the examples was missing double quotes. (Approach: Str translate)
=> Adding missing double quotes

exercises/concept/locomotive-engineer/locomotive_engineer.py
Most of the other concept exercises up to this one communicate the requirement to implement the functions by using docstrings and `pass`, so I think it makes sense to be consistent and do it here as well.
=> Remove TODO comments

exercises/concept/making-the-grade/.docs/instructions.md
Fractional parts of 0.5 and above round up, whereas the documentation had examples of 0.5 rounding both up and down!
=> Correct rounding explanation

exercises/practice/darts/darts_test.py
This is causing all new PRs to fail CI.  
Since it might be a bit before any additional PRs that also include the change are reviewed, decided to do this in its own PR.
=> [Darts] Regenerated Test File

config.json, exercises/concept/cater-waiter/sets_test.py
Fixes #3190 by adding a `self.assertIsInstance` check on line **106** under the `test_separate_appetizers` test.
=> [Cater-Waiter] Fixes type issue raised in 3190

exercises/concept/guidos-gorgeous-lasagna/.docs/instructions.md
=> fix typo in the instruction of guidos-gorgeous

concepts/strings/about.md
Per PR 3394, fixed the Ukraninian example in the concept `about.md`, to match the corrected on in the exercise `introduction.md`.
=> [Strings Concept] Update about.md to fix Ukrainian Example

concepts/tuples/links.json
@BethanyG Thanks for reviewing my pull request and for your feedback! I've made the changes to the stale link based on the is issue #3389. Whereas I have checked the preview of the url and added the preview title under the link by updating the description.
=> Replace stale link by working link with valuable informtion

exercises/practice/binary/.meta/config.json, exercises/practice/etl/.meta/config.json, exercises/practice/hexadecimal/.meta/config.json, exercises/practice/nucleotide-count/.meta/config.json, exercises/practice/octal/.meta/config.json, exercises/practice/point-mutations/.meta/config.json, exercises/practice/trinary/.meta/config.json
Updated the metadata for the following exercises:
=> Metadata Updates from Problem Specs

concepts/generators/.meta/config.json, concepts/generators/about.md, concepts/generators/introduction.md, concepts/generators/links.json, config.json, exercises/concept/plane-tickets/.docs/hints.md, exercises/concept/plane-tickets/.docs/instructions.md, exercises/concept/plane-tickets/.docs/introduction.md, exercises/concept/plane-tickets/.meta/config.json, exercises/concept/plane-tickets/.meta/design.md, exercises/concept/plane-tickets/.meta/exemplar.py, exercises/concept/plane-tickets/plane_tickets.py, exercises/concept/plane-tickets/plane_tickets_test.py
This pr is meant to improve the **unreleased** exercise "plane ticket" and its concept to achieve a better state.
As of this has the following changes been made:
- Changed the code format.
- Changed the link formating
What is left:
- Add an introduction for the exercise
- Add/improve hints
- Add a blurb for the concept
- Various improvements for the exercise and concept
=> [Plane_ticket & generator]: improvments

exercises/practice/yacht/.approaches/introduction.md
=> Remove duplicate line

concepts/dict-methods/about.md, concepts/dict-methods/introduction.md, concepts/dicts/about.md, concepts/dicts/introduction.md, exercises/concept/mecha-munch-management/.docs/introduction.md
=> [Dict and Dict-Methods] Concept tidy-up & Typo Fixes.

concepts/sets/about.md, exercises/concept/cater-waiter/.docs/introduction.md
Code example fixes for this [fourm issue](https://forum.exercism.org/t/error-in-explaing-the-result-of-a-learning-concept-sets/6371).
=> [Cater-Waiter and Sets]: Code Example Fixes

exercises/practice/robot-name/.approaches/config.json, exercises/practice/robot-name/.approaches/introduction.md, exercises/practice/robot-name/.approaches/mass-name-generation/content.md, exercises/practice/robot-name/.approaches/mass-name-generation/snippet.txt, exercises/practice/robot-name/.approaches/name-on-the-fly/content.md, exercises/practice/robot-name/.approaches/name-on-the-fly/snippet.txt
=> Approaches for Robot Name

exercises/practice/book-store/.docs/instructions.md, exercises/practice/darts/.docs/instructions.md, exercises/practice/gigasecond/.docs/introduction.md
These three are active practice exercises on the track.  
This is only an instruction update, and should not trigger solution re-queue.
=> [Book-Store, Darts, & Gigasecond]: Synced Instructions for Active Practice Exercises

exercises/practice/gigasecond/.docs/hints.md
Corrected broken/mis-spelled `datetime.datetime` reflink.
=> [Gigasecond]: Update hints.md

exercises/practice/gigasecond/.docs/hints.md
Pushing this change again to see if it fixes the sync error.
=> [Gigasecond]: Correct Typo in Reflink for Hints file.  Try 2

config.json
Per [discussion](https://forum.exercism.org/t/syllabus-and-overview-isnt-syncronized/6812/14) in forum.  Definitely a WIP, but we'll give it a try and see how things settle.
=> [Track Config]:  Another pass at re-ordering practice exercises.

exercises/practice/atbash-cipher/.approaches/introduction.md, exercises/practice/robot-name/.approaches/introduction.md
Three links in the approaches I authored weren't being rendered. I think this should fix them.
=> Fix link rendering

exercises/practice/atbash-cipher/.approaches/introduction.md
_I don't know what's wrong with me_.
Please mark this as no rep if you can ;).
=> another typo

exercises/practice/binary-search-tree/.meta/config.json, exercises/practice/clock/.meta/config.json, exercises/practice/meetup/.meta/config.json
Synced the metadata for the following practice exercises:
=> [Problem Specifications] Synced practice exercise metadata.

concepts/sets/about.md, concepts/sets/introduction.md, exercises/concept/cater-waiter/.docs/hints.md, exercises/concept/cater-waiter/.docs/introduction.md, exercises/concept/cater-waiter/sets_test.py
Reworked concept docs and exercise introduction.
=> [Sets/Cater-Waiter]:  Rework Concept Docs

concepts/generators/.meta/config.json
Added Bethany, Kytrinyx, and Meatball133 as contributors and updated the concept blurb.
=> [Generator Concept]: Updated config.json

concepts/conditionals/about.md
=> [Conditionals]: Update about.md spelling of Boolean

config.json
Added Fractions as a Concept entry in the track.
=> [Track Config]: Update config.json to add Fractions Concept

concepts/secrets/.meta/config.json, concepts/secrets/about.md, concepts/secrets/introduction.md, concepts/secrets/links.json, config.json
A teeny, tiny concept. I wish they were all this quick to put together.
=> The `secrets` concept

concepts/secrets/introduction.md
=> [Secrets Concept]: Update introduction.md

exercises/practice/perfect-numbers/.docs/instructions.md, exercises/practice/phone-number/.docs/instructions.md, exercises/practice/queen-attack/.docs/instructions.md, exercises/practice/rest-api/.docs/instructions.md
Synced the instructions docs for the following exercises:
=> [Practice Exercises]: Synced Practice Exercise Docs to Problem Specifications

exercises/practice/hello-world/.meta/config.json, exercises/practice/pop-count/.meta/config.json, exercises/practice/pythagorean-triplet/.meta/config.json, exercises/practice/spiral-matrix/.meta/config.json, exercises/practice/transpose/.meta/config.json
Updated the metadata for the following exercises:
=> [Practice Exercises]: Synced Exercise Metadata to Problem Specifications.

exercises/practice/dnd-character/.meta/tests.toml, exercises/practice/dnd-character/dnd_character_test.py
=> [DnD Character]: Synced Exercise Tests to Problem Specifications

exercises/practice/knapsack/.meta/tests.toml, exercises/practice/knapsack/knapsack_test.py
=> [Knapsack]: Synced Exercise Tests to Problem Specifications.

exercises/practice/ledger/.meta/tests.toml, exercises/practice/ledger/ledger_test.py
=> [Ledger]: Synced Exercise Tests to Problem Specifications.

exercises/practice/poker/.meta/tests.toml, exercises/practice/poker/poker_test.py
=> [Poker]: Synced Exercise Tests to Problem Specifications.

exercises/practice/leap/.articles/performance/content.md
Noticed after the push that the image was showing as broken on dark theme.  Hoping this helps.
=> Update content.md remove <p> tag from around svg image

exercises/practice/leap/.docs/instructions.md, exercises/practice/leap/.docs/introduction.md, exercises/practice/leap/.meta/config.json
=> [leap]: Synced Problem Specifications.

exercises/practice/square-root/.docs/instructions.append.md
Clarifies that the solutions are natural numbers.  Fixes #3594
=> [Square Root]:  Add that Solutions are Natural Numbers

exercises/concept/meltdown-mitigation/.docs/introduction.md
Small typo on the intro to the exercise "meltdown mitigation"
=> [Meltdown Mitigation] Typo

docs/INSTALLATION.md
Changed version from Python `3.11.2` to `3.11.5`
=> [Python Docs]:  Update Python Version in INSTALLATION.md

exercises/practice/raindrops/.docs/instructions.append.md
=> [Raindrops]: Added Instruction Append for `divmod()`, `math.fmod()`, `math.remainder()`, `%` & `operator.modulo`

exercises/concept/making-the-grade/loops.py
Correct ascending to descending in stub file.
=> [Making the Grade]:  Correct Ascending to descending in stub file.

exercises/practice/acronym/approaches/config.json
corrected author name to see if it changed rep awarded.
=> Update config.json for approaches

exercises/practice/meetup/.meta/config.json, exercises/practice/raindrops/.meta/config.json, exercises/practice/say/.docs/instructions.md
=> [Raindrops, Meetup, Say]: Synced docs & metadata to Problem Specifications.

exercises/practice/anagram/.meta/tests.toml, exercises/practice/anagram/anagram.py, exercises/practice/anagram/anagram_test.py
This PR is also a test of the changes discussed [here](http://forum.exercism.org/t/workflow-to-suggest-no-important-files-changed/8298/63) on the forum.  With any luck, the new workflow will run with the correct permissions and without errors.  🙂
=> [Anagram]: Updated Tests from `problem-specifications`

exercises/practice/reverse-string/.meta/tests.toml, exercises/practice/reverse-string/reverse_string_test.py
=> [Reverse String]: Updated Tests from `problem-specifications`

exercises/concept/black-jack/.docs/instructions.md
Per [forum discussion](http://forum.exercism.org/t/suggested-changes-to-python-learning-exercise-instructions/9896/11).
=> [BlackJack]: Clarify  Blackjack Hand Definition in instructions.md

exercises/concept/mecha-munch-management/dict_methods_test.py
=> [Mecha Munch Management] Add tests for send_to_store extra aisle_mapping items

exercises/concept/mecha-munch-management/dict_methods_test.py
Trivial, but it was bugging me.
=> [Mecha Munch Management]: Corrected Brackets in dict_methods_test.py

exercises/practice/two-bucket/.docs/instructions.md
Only `instructions.md` has changed.
=> [Two Bucket]: Synced Instructions to Problem Specs.

exercises/practice/roman-numerals/.approaches/introduction.md
As discussed on the forum: http://forum.exercism.org/t/48in24-exercise-02-06-roman-numerals/9399/23
=> Fix maximum length of a roman numeral

concepts/basics/about.md, concepts/basics/introduction.md, exercises/concept/guidos-gorgeous-lasagna/.docs/introduction.md
See [forum discussion](http://forum.exercism.org/t/missing-print-in-python-basics-functions-return/11025/4) for additional information.
=> [Basics Concept/Lasagna Exercise]: Changed `return` keyword Examples

exercises/practice/affine-cipher/.docs/instructions.md, exercises/practice/alphametics/.docs/instructions.md, exercises/practice/alphametics/.meta/config.json
=> [Exercise Sync] Docs and Metadata for Affine-Cipher & Alphametics.

exercises/concept/guidos-gorgeous-lasagna/.docs/introduction.md
Corrected example/sum on line 107 to 11.
=> [Guido's Gorgeous Lasagna] Update introduction.md

concepts/basics/about.md
Corrected sum in example on line 155.
=> [Basics] Update about.md

exercises/practice/dnd-character/dnd_character.py
Per [this discussion](https://forum.exercism.org/t/d-d-character-test-bug/11237/3) on the forum.  Decided to amend the stub, as it was the easiest an least confusing solution.
=> [Update DnD Character] Add Missing Function to Stub

config.json
Per [note](http://forum.exercism.org/t/48in24-exercise-08-27-pascals-triangle/12056/6) on the forum.
=> [Python Track Config] Changed `Pascals Triangle` to `Pascal's Triangle` for the Exercise name.

exercises/concept/little-sisters-vocab/.docs/instructions.md
Rephrased line 7 to omit the usage of `there's`.
=> [Little Sisters Vocabulary] Update instructions.md

.github/workflows/test-runner.yml
[Exercism Forum Post](http://forum.exercism.org/t/github-ci-docker-compose-not-found-error-for-python/12487)
=> [CI Errors]: Attempt at Fix for Issue Described in Forum Post

concepts/basics/introduction.md, concepts/classes/about.md, concepts/conditionals/about.md, exercises/concept/black-jack/.docs/instructions.md, exercises/concept/ellens-alien-game/.docs/introduction.md, exercises/concept/guidos-gorgeous-lasagna/.docs/introduction.md
Minor typos and other fixes for the following concepts/exercises:
[x]   `basics` introduction.md
[x]  `classe` about.md
[x]  `conditionals`  about.md
[x]  `black-jack`  instructions.md
[x]  `ellens-alien-game` introduction.md
[x] `guidos-gorgeous-lasagna` introduction.md
=> [Concepts & Concept Exericses]: Misc. Spelling & Grammar Fixes

exercises/practice/pov/.docs/instructions.append.md
Massaged the phrasing a bit to point students to both raising the specific error type, and including a specific error message.
=> [POV]: Update instructions.append.md

concepts/conditionals/about.md
=> [Conditionals Concept] Update about.md

concepts/basics/introduction.md, exercises/concept/guidos-gorgeous-lasagna/.docs/hints.md, exercises/concept/guidos-gorgeous-lasagna/.docs/instructions.md, exercises/concept/guidos-gorgeous-lasagna/.docs/introduction.md, exercises/concept/guidos-gorgeous-lasagna/lasagna.py
Made small changes to wording and links in:
1.  `Introduction.md`
2.  `concepts/basics/introduction.md`
3.  `instructions.md`
4.  `hints.md`
Also adjusted wording in the stub file and edited TODOs.
=> [Guido's Gorgeous Lasagna]: Touch Ups & Edits for Clarity in Instructions, Intros, and Hints, etc.

exercises/concept/plane-tickets/generators_test.py
Per [forum post](https://forum.exercism.org/t/seemingly-wrong-error-message-in-the-plane-tickets-exercise-on-the-python-track/13386).  _Sometimes, I am an idiot._ 🤦🏽‍♀️
=> [Plane Tickets]: Fixed Final Test & Error Message.  

exercises/practice/acronym/.approaches/introduction.md
For some reason, the performance article was pointing to another problem, this got me confused when I was studying the `dig deeper`.
=> [Acronym]:  Incorrect Reference to Isogram Performance Article

exercises/practice/hamming/.docs/instructions.md, exercises/practice/hamming/.meta/config.json, exercises/practice/luhn/.docs/instructions.md, exercises/practice/pov/.meta/config.json, exercises/practice/rna-transcription/.docs/instructions.md, exercises/practice/sublist/.docs/instructions.md
Updated the following files from `Problem Specifications`:
-  [x]  exercises/practice/hamming/.docs/instructions.md
-  [x]  exercises/practice/hamming/.meta/config.json
-  [x]  exercises/practice/luhn/.docs/instructions.md
-  [x]   exercises/practice/pov/.meta/config.json
-  [x]   exercises/practice/rna-transcription/.docs/instructions.md
-  [x]   exercises/practice/sublist/.docs/instructions.md
=> [November Maintenance]: Updated Metadata & Instructions from Problem Specifications

exercises/practice/forth/.meta/tests.toml, exercises/practice/forth/forth_test.py
See [this PR](https://github.com/exercism/problem-specifications/pull/2477) for more information.
Updated tests.toml file.
Tested example.py file and regenerated forth_test.py.
=> [Forth]: Updated Tests from Problem Specs.

exercises/practice/scrabble-score/.approaches/enum/content.md, exercises/practice/scrabble-score/.approaches/nested-tuple/content.md
Add missing URI for "dictionary approach"
[Forum Discussion](https://forum.exercism.org/t/markdown-error-typo-in-enum-dig-deeper/13940/4).
=> [Scrabble Score]: Update content.md to Fix Broken Links

exercises/practice/simple-linked-list/.meta/config.json, exercises/practice/simple-linked-list/simple_linked_list.py
As an outflow of this [forum discussion](http://forum.exercism.org/t/should-our-templates-better-exemplify-best-practices/14017), made the following changes:
1. Moved the Exception stub to the top of the file
2. Added the `__iter__()` special method stub to the `LinkedList` class.
3. Changed the LinkedList `__init__()` default argument to `values=None`.
=> [Simple Linked List]: Updated Stub File

.github/workflows/no-important-files-changed.yml
Reverts exercism/python#3824
Forgot to revert this now that the fix has been merged.  Reverting now.
=> Revert "[No Important Files Changed Workflow]: Testing Fix for `no-important-files-changed` Workflow."

exercises/practice/bob/.meta/tests.toml, exercises/practice/bob/bob_test.py
Updated bob `tests.toml` and regenerated test file.
=> [Bob]: January Sync to Canonical Data from Problem Specifications

exercises/practice/atbash-cipher/.meta/config.json, exercises/practice/collatz-conjecture/.meta/config.json, exercises/practice/pythagorean-triplet/.meta/config.json
Synced metadata for the following practice exercises:
=> [January Sync]:  Updated Metadata from Problem Specifications

exercises/practice/affine-cipher/.docs/instructions.md, exercises/practice/atbash-cipher/.docs/instructions.md, exercises/practice/change/.docs/instructions.md, exercises/practice/change/.docs/introduction.md, exercises/practice/collatz-conjecture/.docs/instructions.md, exercises/practice/collatz-conjecture/.docs/introduction.md, exercises/practice/complex-numbers/.docs/instructions.md, exercises/practice/dominoes/.docs/instructions.md, exercises/practice/dominoes/.docs/introduction.md, exercises/practice/eliuds-eggs/.docs/introduction.md, exercises/practice/grade-school/.docs/instructions.md, exercises/practice/hamming/.docs/instructions.md, exercises/practice/hamming/.docs/introduction.md, exercises/practice/knapsack/.docs/instructions.md, exercises/practice/knapsack/.docs/introduction.md, exercises/practice/luhn/.docs/instructions.md, exercises/practice/luhn/.docs/introduction.md, exercises/practice/pascals-triangle/.docs/introduction.md, exercises/practice/phone-number/.docs/introduction.md, exercises/practice/protein-translation/.docs/instructions.md, exercises/practice/pythagorean-triplet/.docs/instructions.md, exercises/practice/pythagorean-triplet/.docs/introduction.md, exercises/practice/square-root/.docs/instructions.md, exercises/practice/square-root/.docs/introduction.md
Synced the following practice exercise intros and instructions to problem-specs:
**Introduction**
_____________________
**Instructions**
=> [January Sync]:  Updated Introductions and Instructions for Practice Exercises from Problem Specifications

exercises/practice/anagram/.docs/instructions.md
See [forum discussion](https://forum.exercism.org/t/anagram-exercise-instructions-and-tests-dont-align-on-ordering/14816/58) for more details.
Tests for this exercise do not check for ordering or data structure - only correct anagrams.  This is by design.
=> [Anagram]: Synced Instructions to Problem Specifications.

docs/TESTS.md
Forum reference: [PR Closed on GitHub](https://forum.exercism.org/t/pr-closed-on-github/15231)
=> [TESTS.md]:  Change Smart Quotes to Plain Double Quotes

exercises/concept/mecha-munch-management/.docs/hints.md
=> [Mecha Munch Management]: Added link to <dict.keys> for Hints File

CONTRIBUTING.md, README.md
Also updated Python versions and the PSF copyright notice,
=> [CONTRIBUTING & README]: Added Admonition for not Accepting Community Contributions

exercises/practice/affine-cipher/.docs/instructions.md, exercises/practice/flatten-array/.docs/instructions.md, exercises/practice/flatten-array/.docs/introduction.md, exercises/practice/grains/.docs/instructions.md, exercises/practice/grains/.docs/introduction.md, exercises/practice/saddle-points/.docs/instructions.md, exercises/practice/sieve/.docs/instructions.md, exercises/practice/simple-cipher/.docs/instructions.md
Synced the following exercises to Problem Specifications:
=> [March Docs Sync]: Practice Exercise Intros and Instructions

exercises/practice/binary-search-tree/.docs/instructions.md, exercises/practice/dot-dsl/.docs/instructions.md, exercises/practice/luhn/.docs/instructions.md, exercises/practice/meetup/.docs/instructions.md, exercises/practice/phone-number/.docs/instructions.md, exercises/practice/protein-translation/.docs/instructions.md, exercises/practice/simple-cipher/.docs/instructions.md
Synced the following practice exercise instruction files:
=> [June Problem-Spec Sync]: Practice Exercise Instructions

config.json
Added Nth Prime and Largest Series Product for practicing generators instead.
=> [Track Config (Generators Concept)]: Removed Scale Generator from Practices Generators

exercises/practice/variable-length-quantity/.meta/tests.toml, exercises/practice/variable-length-quantity/variable_length_quantity_test.py
Updated test cases per https://github.com/exercism/problem-specifications/pull/2576/files, which added 5 new non-1 and non-0 test cases.
=> [Variable Length Quantity]: Updated tests.toml & Regenerated Test Cases
